// Module parser
function parser_init(){ console.log("Initializing parser"); }
function parser_func_0(x){ let y = x + 656; y += lexer_helper(33); return y; }
function parser_func_1(x){ let y = x + 570; y += emitter_helper(33); return y; }
function parser_func_2(x){ let y = x + 926; y += optimizer_helper(29); return y; }
function parser_func_3(x){ let y = x + 591; y += parser_helper(8); return y; }
function parser_func_4(x){ let y = x + 21; y += parser_helper(35); return y; }
function parser_func_5(x){ let y = x + 921; y += ast_helper(39); return y; }
function parser_func_6(x){ let y = x + 76; y += lexer_helper(42); return y; }
function parser_func_7(x){ let y = x + 469; y += lexer_helper(33); return y; }
function parser_func_8(x){ let y = x + 117; y += ast_helper(15); return y; }
function parser_func_9(x){ let y = x + 177; y += optimizer_helper(40); return y; }
function parser_func_10(x){ let y = x + 971; y += ast_helper(9); return y; }
function parser_func_11(x){ let y = x + 302; y += parser_helper(45); return y; }
function parser_func_12(x){ let y = x + 244; y += lexer_helper(32); return y; }
function parser_func_13(x){ let y = x + 543; y += parser_helper(11); return y; }
function parser_func_14(x){ let y = x + 37; y += lexer_helper(13); return y; }
function parser_func_15(x){ let y = x + 722; y += ast_helper(19); return y; }
function parser_func_16(x){ let y = x + 573; y += ast_helper(20); return y; }
function parser_func_17(x){ let y = x + 69; y += optimizer_helper(21); return y; }
function parser_func_18(x){ let y = x + 503; y += emitter_helper(47); return y; }
function parser_func_19(x){ let y = x + 801; y += lexer_helper(36); return y; }
function parser_func_20(x){ let y = x + 921; y += ast_helper(19); return y; }
function parser_func_21(x){ let y = x + 597; y += ast_helper(45); return y; }
function parser_func_22(x){ let y = x + 256; y += parser_helper(49); return y; }
function parser_func_23(x){ let y = x + 573; y += emitter_helper(38); return y; }
function parser_func_24(x){ let y = x + 2; y += ast_helper(1); return y; }
function parser_func_25(x){ let y = x + 183; y += optimizer_helper(1); return y; }
function parser_func_26(x){ let y = x + 276; y += ast_helper(4); return y; }
function parser_func_27(x){ let y = x + 916; y += parser_helper(0); return y; }
function parser_func_28(x){ let y = x + 905; y += ast_helper(2); return y; }
function parser_func_29(x){ let y = x + 494; y += optimizer_helper(21); return y; }
function parser_func_30(x){ let y = x + 220; y += parser_helper(31); return y; }
function parser_func_31(x){ let y = x + 89; y += optimizer_helper(42); return y; }
function parser_func_32(x){ let y = x + 599; y += ast_helper(19); return y; }
function parser_func_33(x){ let y = x + 386; y += emitter_helper(48); return y; }
function parser_func_34(x){ let y = x + 120; y += ast_helper(2); return y; }
function parser_func_35(x){ let y = x + 389; y += emitter_helper(43); return y; }
function parser_func_36(x){ let y = x + 84; y += lexer_helper(44); return y; }
function parser_func_37(x){ let y = x + 988; y += parser_helper(24); return y; }
function parser_func_38(x){ let y = x + 888; y += parser_helper(1); return y; }
function parser_func_39(x){ let y = x + 556; y += optimizer_helper(18); return y; }
function parser_func_40(x){ let y = x + 406; y += optimizer_helper(1); return y; }
function parser_func_41(x){ let y = x + 830; y += parser_helper(20); return y; }
function parser_func_42(x){ let y = x + 209; y += optimizer_helper(12); return y; }
function parser_func_43(x){ let y = x + 239; y += lexer_helper(21); return y; }
function parser_func_44(x){ let y = x + 61; y += emitter_helper(49); return y; }
function parser_func_45(x){ let y = x + 815; y += ast_helper(10); return y; }
function parser_func_46(x){ let y = x + 575; y += ast_helper(24); return y; }
function parser_func_47(x){ let y = x + 94; y += optimizer_helper(8); return y; }
function parser_func_48(x){ let y = x + 432; y += optimizer_helper(13); return y; }
function parser_func_49(x){ let y = x + 363; y += lexer_helper(48); return y; }
function parser_func_50(x){ let y = x + 136; y += ast_helper(10); return y; }
function parser_func_51(x){ let y = x + 34; y += ast_helper(20); return y; }
function parser_func_52(x){ let y = x + 356; y += ast_helper(28); return y; }
function parser_func_53(x){ let y = x + 628; y += emitter_helper(7); return y; }
function parser_func_54(x){ let y = x + 558; y += emitter_helper(48); return y; }
function parser_func_55(x){ let y = x + 995; y += emitter_helper(3); return y; }
function parser_func_56(x){ let y = x + 74; y += lexer_helper(8); return y; }
function parser_func_57(x){ let y = x + 83; y += parser_helper(0); return y; }
function parser_func_58(x){ let y = x + 691; y += ast_helper(14); return y; }
function parser_func_59(x){ let y = x + 306; y += emitter_helper(8); return y; }
function parser_func_60(x){ let y = x + 462; y += emitter_helper(45); return y; }
function parser_func_61(x){ let y = x + 683; y += ast_helper(27); return y; }
function parser_func_62(x){ let y = x + 229; y += parser_helper(25); return y; }
function parser_func_63(x){ let y = x + 724; y += parser_helper(17); return y; }
function parser_func_64(x){ let y = x + 342; y += optimizer_helper(31); return y; }
function parser_func_65(x){ let y = x + 432; y += parser_helper(24); return y; }
function parser_func_66(x){ let y = x + 814; y += optimizer_helper(26); return y; }
function parser_func_67(x){ let y = x + 648; y += ast_helper(49); return y; }
function parser_func_68(x){ let y = x + 421; y += emitter_helper(39); return y; }
function parser_func_69(x){ let y = x + 809; y += optimizer_helper(6); return y; }
function parser_func_70(x){ let y = x + 663; y += ast_helper(17); return y; }
function parser_func_71(x){ let y = x + 584; y += lexer_helper(23); return y; }
function parser_func_72(x){ let y = x + 358; y += ast_helper(44); return y; }
function parser_func_73(x){ let y = x + 166; y += ast_helper(17); return y; }
function parser_func_74(x){ let y = x + 34; y += parser_helper(4); return y; }
function parser_func_75(x){ let y = x + 123; y += parser_helper(31); return y; }
function parser_func_76(x){ let y = x + 992; y += optimizer_helper(4); return y; }
function parser_func_77(x){ let y = x + 406; y += emitter_helper(47); return y; }
function parser_func_78(x){ let y = x + 702; y += parser_helper(40); return y; }
function parser_func_79(x){ let y = x + 514; y += parser_helper(39); return y; }
function parser_func_80(x){ let y = x + 33; y += lexer_helper(7); return y; }
function parser_func_81(x){ let y = x + 401; y += ast_helper(16); return y; }
function parser_func_82(x){ let y = x + 882; y += emitter_helper(19); return y; }
function parser_func_83(x){ let y = x + 476; y += ast_helper(41); return y; }
function parser_func_84(x){ let y = x + 374; y += emitter_helper(31); return y; }
function parser_func_85(x){ let y = x + 776; y += emitter_helper(47); return y; }
function parser_func_86(x){ let y = x + 222; y += emitter_helper(11); return y; }
function parser_func_87(x){ let y = x + 416; y += optimizer_helper(33); return y; }
function parser_func_88(x){ let y = x + 565; y += lexer_helper(33); return y; }
function parser_func_89(x){ let y = x + 214; y += parser_helper(11); return y; }
function parser_func_90(x){ let y = x + 858; y += emitter_helper(20); return y; }
function parser_func_91(x){ let y = x + 306; y += lexer_helper(36); return y; }
function parser_func_92(x){ let y = x + 502; y += emitter_helper(12); return y; }
function parser_func_93(x){ let y = x + 738; y += emitter_helper(34); return y; }
function parser_func_94(x){ let y = x + 665; y += ast_helper(33); return y; }
function parser_func_95(x){ let y = x + 568; y += emitter_helper(0); return y; }
function parser_func_96(x){ let y = x + 33; y += parser_helper(16); return y; }
function parser_func_97(x){ let y = x + 647; y += parser_helper(49); return y; }
function parser_func_98(x){ let y = x + 736; y += lexer_helper(40); return y; }
function parser_func_99(x){ let y = x + 689; y += parser_helper(47); return y; }
function parser_func_100(x){ let y = x + 0; y += optimizer_helper(4); return y; }
function parser_func_101(x){ let y = x + 842; y += lexer_helper(44); return y; }
function parser_func_102(x){ let y = x + 952; y += emitter_helper(14); return y; }
function parser_func_103(x){ let y = x + 376; y += lexer_helper(31); return y; }
function parser_func_104(x){ let y = x + 271; y += parser_helper(40); return y; }
function parser_func_105(x){ let y = x + 177; y += lexer_helper(21); return y; }
function parser_func_106(x){ let y = x + 606; y += optimizer_helper(46); return y; }
function parser_func_107(x){ let y = x + 797; y += ast_helper(46); return y; }
function parser_func_108(x){ let y = x + 769; y += ast_helper(16); return y; }
function parser_func_109(x){ let y = x + 818; y += lexer_helper(27); return y; }
function parser_func_110(x){ let y = x + 308; y += emitter_helper(3); return y; }
function parser_func_111(x){ let y = x + 631; y += optimizer_helper(13); return y; }
function parser_func_112(x){ let y = x + 286; y += parser_helper(3); return y; }
function parser_func_113(x){ let y = x + 736; y += lexer_helper(3); return y; }
function parser_func_114(x){ let y = x + 717; y += optimizer_helper(49); return y; }
function parser_func_115(x){ let y = x + 430; y += optimizer_helper(39); return y; }
function parser_func_116(x){ let y = x + 95; y += optimizer_helper(46); return y; }
function parser_func_117(x){ let y = x + 999; y += lexer_helper(2); return y; }
function parser_func_118(x){ let y = x + 546; y += optimizer_helper(0); return y; }
function parser_func_119(x){ let y = x + 61; y += parser_helper(1); return y; }
function parser_func_120(x){ let y = x + 625; y += parser_helper(26); return y; }
function parser_func_121(x){ let y = x + 458; y += parser_helper(7); return y; }
function parser_func_122(x){ let y = x + 527; y += lexer_helper(6); return y; }
function parser_func_123(x){ let y = x + 683; y += lexer_helper(25); return y; }
function parser_func_124(x){ let y = x + 817; y += ast_helper(21); return y; }
function parser_func_125(x){ let y = x + 995; y += lexer_helper(37); return y; }
function parser_func_126(x){ let y = x + 858; y += lexer_helper(34); return y; }
function parser_func_127(x){ let y = x + 773; y += lexer_helper(21); return y; }
function parser_func_128(x){ let y = x + 115; y += lexer_helper(15); return y; }
function parser_func_129(x){ let y = x + 777; y += ast_helper(39); return y; }
function parser_func_130(x){ let y = x + 312; y += parser_helper(28); return y; }
function parser_func_131(x){ let y = x + 28; y += emitter_helper(34); return y; }
function parser_func_132(x){ let y = x + 625; y += ast_helper(45); return y; }
function parser_func_133(x){ let y = x + 765; y += ast_helper(16); return y; }
function parser_func_134(x){ let y = x + 891; y += ast_helper(48); return y; }
function parser_func_135(x){ let y = x + 997; y += optimizer_helper(17); return y; }
function parser_func_136(x){ let y = x + 481; y += ast_helper(22); return y; }
function parser_func_137(x){ let y = x + 922; y += optimizer_helper(6); return y; }
function parser_func_138(x){ let y = x + 665; y += emitter_helper(24); return y; }
function parser_func_139(x){ let y = x + 41; y += emitter_helper(28); return y; }
function parser_func_140(x){ let y = x + 642; y += parser_helper(16); return y; }
function parser_func_141(x){ let y = x + 282; y += emitter_helper(45); return y; }
function parser_func_142(x){ let y = x + 711; y += parser_helper(44); return y; }
function parser_func_143(x){ let y = x + 978; y += parser_helper(17); return y; }
function parser_func_144(x){ let y = x + 860; y += emitter_helper(18); return y; }
function parser_func_145(x){ let y = x + 547; y += optimizer_helper(39); return y; }
function parser_func_146(x){ let y = x + 199; y += lexer_helper(28); return y; }
function parser_func_147(x){ let y = x + 411; y += optimizer_helper(34); return y; }
function parser_func_148(x){ let y = x + 666; y += optimizer_helper(24); return y; }
function parser_func_149(x){ let y = x + 428; y += ast_helper(6); return y; }
function parser_func_150(x){ let y = x + 819; y += optimizer_helper(47); return y; }
function parser_func_151(x){ let y = x + 162; y += lexer_helper(46); return y; }
function parser_func_152(x){ let y = x + 29; y += optimizer_helper(26); return y; }
function parser_func_153(x){ let y = x + 531; y += ast_helper(21); return y; }
function parser_func_154(x){ let y = x + 675; y += ast_helper(4); return y; }
function parser_func_155(x){ let y = x + 121; y += ast_helper(30); return y; }
function parser_func_156(x){ let y = x + 415; y += emitter_helper(12); return y; }
function parser_func_157(x){ let y = x + 449; y += emitter_helper(31); return y; }
function parser_func_158(x){ let y = x + 940; y += optimizer_helper(12); return y; }
function parser_func_159(x){ let y = x + 214; y += parser_helper(46); return y; }
function parser_func_160(x){ let y = x + 644; y += emitter_helper(27); return y; }
function parser_func_161(x){ let y = x + 113; y += optimizer_helper(22); return y; }
function parser_func_162(x){ let y = x + 29; y += parser_helper(18); return y; }
function parser_func_163(x){ let y = x + 846; y += emitter_helper(21); return y; }
function parser_func_164(x){ let y = x + 585; y += parser_helper(32); return y; }
function parser_func_165(x){ let y = x + 818; y += emitter_helper(35); return y; }
function parser_func_166(x){ let y = x + 371; y += parser_helper(13); return y; }
function parser_func_167(x){ let y = x + 6; y += emitter_helper(45); return y; }
function parser_func_168(x){ let y = x + 237; y += emitter_helper(0); return y; }
function parser_func_169(x){ let y = x + 732; y += optimizer_helper(23); return y; }
function parser_func_170(x){ let y = x + 613; y += emitter_helper(41); return y; }
function parser_func_171(x){ let y = x + 1; y += ast_helper(25); return y; }
function parser_func_172(x){ let y = x + 563; y += lexer_helper(38); return y; }
function parser_func_173(x){ let y = x + 477; y += parser_helper(49); return y; }
function parser_func_174(x){ let y = x + 951; y += emitter_helper(28); return y; }
function parser_func_175(x){ let y = x + 297; y += ast_helper(1); return y; }
function parser_func_176(x){ let y = x + 789; y += parser_helper(5); return y; }
function parser_func_177(x){ let y = x + 316; y += optimizer_helper(1); return y; }
function parser_func_178(x){ let y = x + 203; y += lexer_helper(34); return y; }
function parser_func_179(x){ let y = x + 685; y += emitter_helper(3); return y; }
function parser_func_180(x){ let y = x + 922; y += emitter_helper(46); return y; }
function parser_func_181(x){ let y = x + 576; y += lexer_helper(2); return y; }
function parser_func_182(x){ let y = x + 338; y += lexer_helper(4); return y; }
function parser_func_183(x){ let y = x + 134; y += optimizer_helper(6); return y; }
function parser_func_184(x){ let y = x + 792; y += optimizer_helper(7); return y; }
function parser_func_185(x){ let y = x + 556; y += ast_helper(38); return y; }
function parser_func_186(x){ let y = x + 628; y += parser_helper(22); return y; }
function parser_func_187(x){ let y = x + 723; y += optimizer_helper(49); return y; }
function parser_func_188(x){ let y = x + 573; y += lexer_helper(27); return y; }
function parser_func_189(x){ let y = x + 752; y += lexer_helper(18); return y; }
function parser_func_190(x){ let y = x + 149; y += lexer_helper(28); return y; }
function parser_func_191(x){ let y = x + 779; y += parser_helper(49); return y; }
function parser_func_192(x){ let y = x + 472; y += ast_helper(23); return y; }
function parser_func_193(x){ let y = x + 374; y += parser_helper(38); return y; }
function parser_func_194(x){ let y = x + 686; y += parser_helper(9); return y; }
function parser_func_195(x){ let y = x + 50; y += parser_helper(30); return y; }
function parser_func_196(x){ let y = x + 126; y += optimizer_helper(19); return y; }
function parser_func_197(x){ let y = x + 375; y += lexer_helper(14); return y; }
function parser_func_198(x){ let y = x + 345; y += lexer_helper(35); return y; }
function parser_func_199(x){ let y = x + 762; y += emitter_helper(10); return y; }
function parser_func_200(x){ let y = x + 974; y += optimizer_helper(29); return y; }
function parser_func_201(x){ let y = x + 98; y += ast_helper(49); return y; }
function parser_func_202(x){ let y = x + 640; y += optimizer_helper(40); return y; }
function parser_func_203(x){ let y = x + 115; y += lexer_helper(20); return y; }
function parser_func_204(x){ let y = x + 597; y += ast_helper(49); return y; }
function parser_func_205(x){ let y = x + 866; y += lexer_helper(4); return y; }
function parser_func_206(x){ let y = x + 335; y += parser_helper(25); return y; }
function parser_func_207(x){ let y = x + 756; y += lexer_helper(17); return y; }
function parser_func_208(x){ let y = x + 472; y += optimizer_helper(12); return y; }
function parser_func_209(x){ let y = x + 12; y += emitter_helper(26); return y; }
function parser_func_210(x){ let y = x + 584; y += ast_helper(43); return y; }
function parser_func_211(x){ let y = x + 805; y += lexer_helper(16); return y; }
function parser_func_212(x){ let y = x + 755; y += parser_helper(13); return y; }
function parser_func_213(x){ let y = x + 499; y += parser_helper(37); return y; }
function parser_func_214(x){ let y = x + 681; y += emitter_helper(46); return y; }
function parser_func_215(x){ let y = x + 461; y += ast_helper(24); return y; }
function parser_func_216(x){ let y = x + 19; y += optimizer_helper(29); return y; }
function parser_func_217(x){ let y = x + 697; y += emitter_helper(40); return y; }
function parser_func_218(x){ let y = x + 240; y += optimizer_helper(30); return y; }
function parser_func_219(x){ let y = x + 583; y += optimizer_helper(23); return y; }
function parser_func_220(x){ let y = x + 546; y += parser_helper(25); return y; }
function parser_func_221(x){ let y = x + 271; y += parser_helper(19); return y; }
function parser_func_222(x){ let y = x + 906; y += lexer_helper(40); return y; }
function parser_func_223(x){ let y = x + 46; y += lexer_helper(15); return y; }
function parser_func_224(x){ let y = x + 143; y += emitter_helper(20); return y; }
function parser_func_225(x){ let y = x + 734; y += emitter_helper(16); return y; }
function parser_func_226(x){ let y = x + 837; y += emitter_helper(6); return y; }
function parser_func_227(x){ let y = x + 849; y += ast_helper(2); return y; }
function parser_func_228(x){ let y = x + 716; y += emitter_helper(19); return y; }
function parser_func_229(x){ let y = x + 931; y += optimizer_helper(35); return y; }
function parser_func_230(x){ let y = x + 897; y += parser_helper(44); return y; }
function parser_func_231(x){ let y = x + 240; y += parser_helper(32); return y; }
function parser_func_232(x){ let y = x + 979; y += parser_helper(3); return y; }
function parser_func_233(x){ let y = x + 712; y += parser_helper(12); return y; }
function parser_func_234(x){ let y = x + 799; y += ast_helper(30); return y; }
function parser_func_235(x){ let y = x + 451; y += emitter_helper(20); return y; }
function parser_func_236(x){ let y = x + 263; y += optimizer_helper(5); return y; }
function parser_func_237(x){ let y = x + 481; y += emitter_helper(9); return y; }
function parser_func_238(x){ let y = x + 484; y += lexer_helper(25); return y; }
function parser_func_239(x){ let y = x + 468; y += parser_helper(13); return y; }
function parser_func_240(x){ let y = x + 953; y += emitter_helper(37); return y; }
function parser_func_241(x){ let y = x + 762; y += lexer_helper(44); return y; }
function parser_func_242(x){ let y = x + 47; y += optimizer_helper(20); return y; }
function parser_func_243(x){ let y = x + 223; y += optimizer_helper(31); return y; }
function parser_func_244(x){ let y = x + 700; y += emitter_helper(8); return y; }
function parser_func_245(x){ let y = x + 918; y += emitter_helper(31); return y; }
function parser_func_246(x){ let y = x + 30; y += lexer_helper(1); return y; }
function parser_func_247(x){ let y = x + 386; y += ast_helper(31); return y; }
function parser_func_248(x){ let y = x + 269; y += ast_helper(31); return y; }
function parser_func_249(x){ let y = x + 129; y += emitter_helper(13); return y; }
function parser_func_250(x){ let y = x + 748; y += optimizer_helper(17); return y; }
function parser_func_251(x){ let y = x + 430; y += emitter_helper(45); return y; }
function parser_func_252(x){ let y = x + 888; y += ast_helper(48); return y; }
function parser_func_253(x){ let y = x + 899; y += emitter_helper(17); return y; }
function parser_func_254(x){ let y = x + 423; y += parser_helper(29); return y; }
function parser_func_255(x){ let y = x + 441; y += optimizer_helper(0); return y; }
function parser_func_256(x){ let y = x + 270; y += emitter_helper(44); return y; }
function parser_func_257(x){ let y = x + 614; y += ast_helper(31); return y; }
function parser_func_258(x){ let y = x + 445; y += optimizer_helper(35); return y; }
function parser_func_259(x){ let y = x + 455; y += parser_helper(48); return y; }
function parser_func_260(x){ let y = x + 362; y += emitter_helper(22); return y; }
function parser_func_261(x){ let y = x + 923; y += emitter_helper(6); return y; }
function parser_func_262(x){ let y = x + 830; y += emitter_helper(10); return y; }
function parser_func_263(x){ let y = x + 503; y += lexer_helper(38); return y; }
function parser_func_264(x){ let y = x + 745; y += parser_helper(35); return y; }
function parser_func_265(x){ let y = x + 85; y += emitter_helper(39); return y; }
function parser_func_266(x){ let y = x + 349; y += lexer_helper(6); return y; }
function parser_func_267(x){ let y = x + 169; y += optimizer_helper(5); return y; }
function parser_func_268(x){ let y = x + 989; y += ast_helper(8); return y; }
function parser_func_269(x){ let y = x + 55; y += parser_helper(3); return y; }
function parser_func_270(x){ let y = x + 907; y += lexer_helper(4); return y; }
function parser_func_271(x){ let y = x + 150; y += lexer_helper(39); return y; }
function parser_func_272(x){ let y = x + 523; y += ast_helper(38); return y; }
function parser_func_273(x){ let y = x + 603; y += optimizer_helper(12); return y; }
function parser_func_274(x){ let y = x + 951; y += ast_helper(17); return y; }
function parser_func_275(x){ let y = x + 844; y += ast_helper(24); return y; }
function parser_func_276(x){ let y = x + 158; y += lexer_helper(40); return y; }
function parser_func_277(x){ let y = x + 633; y += parser_helper(5); return y; }
function parser_func_278(x){ let y = x + 849; y += lexer_helper(9); return y; }
function parser_func_279(x){ let y = x + 966; y += parser_helper(36); return y; }
function parser_func_280(x){ let y = x + 48; y += ast_helper(8); return y; }
function parser_func_281(x){ let y = x + 807; y += parser_helper(26); return y; }
function parser_func_282(x){ let y = x + 414; y += emitter_helper(22); return y; }
function parser_func_283(x){ let y = x + 98; y += parser_helper(15); return y; }
function parser_func_284(x){ let y = x + 617; y += parser_helper(49); return y; }
function parser_func_285(x){ let y = x + 256; y += ast_helper(7); return y; }
function parser_func_286(x){ let y = x + 132; y += ast_helper(33); return y; }
function parser_func_287(x){ let y = x + 889; y += emitter_helper(12); return y; }
function parser_func_288(x){ let y = x + 212; y += parser_helper(6); return y; }
function parser_func_289(x){ let y = x + 795; y += parser_helper(41); return y; }
function parser_func_290(x){ let y = x + 257; y += optimizer_helper(42); return y; }
function parser_func_291(x){ let y = x + 266; y += parser_helper(10); return y; }
function parser_func_292(x){ let y = x + 814; y += optimizer_helper(11); return y; }
function parser_func_293(x){ let y = x + 480; y += optimizer_helper(24); return y; }
function parser_func_294(x){ let y = x + 410; y += parser_helper(28); return y; }
function parser_func_295(x){ let y = x + 253; y += emitter_helper(17); return y; }
function parser_func_296(x){ let y = x + 651; y += lexer_helper(25); return y; }
function parser_func_297(x){ let y = x + 195; y += emitter_helper(39); return y; }
function parser_func_298(x){ let y = x + 31; y += optimizer_helper(38); return y; }
function parser_func_299(x){ let y = x + 481; y += emitter_helper(13); return y; }
function parser_func_300(x){ let y = x + 654; y += lexer_helper(23); return y; }
function parser_func_301(x){ let y = x + 664; y += emitter_helper(20); return y; }
function parser_func_302(x){ let y = x + 616; y += parser_helper(32); return y; }
function parser_func_303(x){ let y = x + 666; y += ast_helper(21); return y; }
function parser_func_304(x){ let y = x + 80; y += lexer_helper(10); return y; }
function parser_func_305(x){ let y = x + 565; y += optimizer_helper(36); return y; }
function parser_func_306(x){ let y = x + 568; y += lexer_helper(16); return y; }
function parser_func_307(x){ let y = x + 919; y += ast_helper(1); return y; }
function parser_func_308(x){ let y = x + 965; y += parser_helper(31); return y; }
function parser_func_309(x){ let y = x + 255; y += lexer_helper(6); return y; }
function parser_func_310(x){ let y = x + 109; y += ast_helper(4); return y; }
function parser_func_311(x){ let y = x + 376; y += ast_helper(34); return y; }
function parser_func_312(x){ let y = x + 823; y += parser_helper(48); return y; }
function parser_func_313(x){ let y = x + 717; y += lexer_helper(20); return y; }
function parser_func_314(x){ let y = x + 931; y += lexer_helper(39); return y; }
function parser_func_315(x){ let y = x + 369; y += optimizer_helper(24); return y; }
function parser_func_316(x){ let y = x + 724; y += parser_helper(32); return y; }
function parser_func_317(x){ let y = x + 358; y += emitter_helper(10); return y; }
function parser_func_318(x){ let y = x + 374; y += parser_helper(13); return y; }
function parser_func_319(x){ let y = x + 912; y += lexer_helper(41); return y; }
function parser_func_320(x){ let y = x + 635; y += ast_helper(36); return y; }
function parser_func_321(x){ let y = x + 504; y += parser_helper(25); return y; }
function parser_func_322(x){ let y = x + 106; y += optimizer_helper(10); return y; }
function parser_func_323(x){ let y = x + 773; y += parser_helper(2); return y; }
function parser_func_324(x){ let y = x + 848; y += emitter_helper(10); return y; }
function parser_func_325(x){ let y = x + 65; y += ast_helper(13); return y; }
function parser_func_326(x){ let y = x + 936; y += parser_helper(19); return y; }
function parser_func_327(x){ let y = x + 78; y += emitter_helper(42); return y; }
function parser_func_328(x){ let y = x + 680; y += lexer_helper(18); return y; }
function parser_func_329(x){ let y = x + 306; y += lexer_helper(23); return y; }
function parser_func_330(x){ let y = x + 144; y += lexer_helper(23); return y; }
function parser_func_331(x){ let y = x + 577; y += lexer_helper(9); return y; }
function parser_func_332(x){ let y = x + 868; y += optimizer_helper(28); return y; }
function parser_func_333(x){ let y = x + 413; y += ast_helper(11); return y; }
function parser_func_334(x){ let y = x + 404; y += lexer_helper(38); return y; }
function parser_func_335(x){ let y = x + 285; y += ast_helper(6); return y; }
function parser_func_336(x){ let y = x + 994; y += lexer_helper(7); return y; }
function parser_func_337(x){ let y = x + 419; y += parser_helper(35); return y; }
function parser_func_338(x){ let y = x + 528; y += ast_helper(43); return y; }
function parser_func_339(x){ let y = x + 982; y += lexer_helper(10); return y; }
function parser_func_340(x){ let y = x + 379; y += ast_helper(46); return y; }
function parser_func_341(x){ let y = x + 980; y += emitter_helper(26); return y; }
function parser_func_342(x){ let y = x + 934; y += ast_helper(18); return y; }
function parser_func_343(x){ let y = x + 773; y += emitter_helper(37); return y; }
function parser_func_344(x){ let y = x + 135; y += ast_helper(18); return y; }
function parser_func_345(x){ let y = x + 146; y += parser_helper(23); return y; }
function parser_func_346(x){ let y = x + 927; y += parser_helper(37); return y; }
function parser_func_347(x){ let y = x + 262; y += lexer_helper(17); return y; }
function parser_func_348(x){ let y = x + 219; y += lexer_helper(15); return y; }
function parser_func_349(x){ let y = x + 398; y += lexer_helper(44); return y; }
function parser_func_350(x){ let y = x + 682; y += parser_helper(44); return y; }
function parser_func_351(x){ let y = x + 454; y += emitter_helper(1); return y; }
function parser_func_352(x){ let y = x + 735; y += optimizer_helper(22); return y; }
function parser_func_353(x){ let y = x + 915; y += optimizer_helper(48); return y; }
function parser_func_354(x){ let y = x + 670; y += parser_helper(28); return y; }
function parser_func_355(x){ let y = x + 488; y += optimizer_helper(49); return y; }
function parser_func_356(x){ let y = x + 17; y += parser_helper(0); return y; }
function parser_func_357(x){ let y = x + 50; y += lexer_helper(36); return y; }
function parser_func_358(x){ let y = x + 593; y += lexer_helper(12); return y; }
function parser_func_359(x){ let y = x + 438; y += lexer_helper(30); return y; }
function parser_func_360(x){ let y = x + 197; y += ast_helper(19); return y; }
function parser_func_361(x){ let y = x + 766; y += ast_helper(30); return y; }
function parser_func_362(x){ let y = x + 121; y += optimizer_helper(24); return y; }
function parser_func_363(x){ let y = x + 727; y += optimizer_helper(27); return y; }
function parser_func_364(x){ let y = x + 945; y += ast_helper(2); return y; }
function parser_func_365(x){ let y = x + 872; y += lexer_helper(31); return y; }
function parser_func_366(x){ let y = x + 86; y += lexer_helper(49); return y; }
function parser_func_367(x){ let y = x + 250; y += parser_helper(7); return y; }
function parser_func_368(x){ let y = x + 544; y += parser_helper(17); return y; }
function parser_func_369(x){ let y = x + 856; y += emitter_helper(11); return y; }
function parser_func_370(x){ let y = x + 552; y += parser_helper(34); return y; }
function parser_func_371(x){ let y = x + 304; y += lexer_helper(0); return y; }
function parser_func_372(x){ let y = x + 814; y += optimizer_helper(44); return y; }
function parser_func_373(x){ let y = x + 117; y += lexer_helper(11); return y; }
function parser_func_374(x){ let y = x + 541; y += lexer_helper(3); return y; }
function parser_func_375(x){ let y = x + 691; y += parser_helper(20); return y; }
function parser_func_376(x){ let y = x + 854; y += optimizer_helper(36); return y; }
function parser_func_377(x){ let y = x + 212; y += optimizer_helper(41); return y; }
function parser_func_378(x){ let y = x + 51; y += optimizer_helper(13); return y; }
function parser_func_379(x){ let y = x + 627; y += lexer_helper(5); return y; }
function parser_func_380(x){ let y = x + 946; y += emitter_helper(7); return y; }
function parser_func_381(x){ let y = x + 733; y += lexer_helper(6); return y; }
function parser_func_382(x){ let y = x + 784; y += lexer_helper(45); return y; }
function parser_func_383(x){ let y = x + 438; y += lexer_helper(26); return y; }
function parser_func_384(x){ let y = x + 788; y += ast_helper(12); return y; }
function parser_func_385(x){ let y = x + 514; y += optimizer_helper(25); return y; }
function parser_func_386(x){ let y = x + 771; y += emitter_helper(20); return y; }
function parser_func_387(x){ let y = x + 40; y += ast_helper(27); return y; }
function parser_func_388(x){ let y = x + 908; y += emitter_helper(11); return y; }
function parser_func_389(x){ let y = x + 883; y += parser_helper(11); return y; }
function parser_func_390(x){ let y = x + 594; y += parser_helper(1); return y; }
function parser_func_391(x){ let y = x + 552; y += emitter_helper(29); return y; }
function parser_func_392(x){ let y = x + 547; y += parser_helper(23); return y; }
function parser_func_393(x){ let y = x + 276; y += ast_helper(8); return y; }
function parser_func_394(x){ let y = x + 978; y += optimizer_helper(24); return y; }
function parser_func_395(x){ let y = x + 493; y += lexer_helper(44); return y; }
function parser_func_396(x){ let y = x + 244; y += optimizer_helper(9); return y; }
function parser_func_397(x){ let y = x + 778; y += optimizer_helper(47); return y; }
function parser_func_398(x){ let y = x + 919; y += emitter_helper(7); return y; }
function parser_func_399(x){ let y = x + 58; y += lexer_helper(22); return y; }
function parser_func_400(x){ let y = x + 179; y += lexer_helper(7); return y; }
function parser_func_401(x){ let y = x + 874; y += emitter_helper(12); return y; }
function parser_func_402(x){ let y = x + 763; y += emitter_helper(48); return y; }
function parser_func_403(x){ let y = x + 32; y += lexer_helper(27); return y; }
function parser_func_404(x){ let y = x + 893; y += emitter_helper(28); return y; }
function parser_func_405(x){ let y = x + 286; y += lexer_helper(22); return y; }
function parser_func_406(x){ let y = x + 523; y += emitter_helper(40); return y; }
function parser_func_407(x){ let y = x + 718; y += emitter_helper(45); return y; }
function parser_func_408(x){ let y = x + 10; y += ast_helper(43); return y; }
function parser_func_409(x){ let y = x + 885; y += emitter_helper(37); return y; }
function parser_func_410(x){ let y = x + 391; y += parser_helper(23); return y; }
function parser_func_411(x){ let y = x + 493; y += emitter_helper(40); return y; }
function parser_func_412(x){ let y = x + 663; y += ast_helper(17); return y; }
function parser_func_413(x){ let y = x + 239; y += ast_helper(9); return y; }
function parser_func_414(x){ let y = x + 964; y += ast_helper(28); return y; }
function parser_func_415(x){ let y = x + 453; y += parser_helper(4); return y; }
function parser_func_416(x){ let y = x + 260; y += emitter_helper(49); return y; }
function parser_func_417(x){ let y = x + 190; y += lexer_helper(0); return y; }
function parser_func_418(x){ let y = x + 968; y += ast_helper(22); return y; }
function parser_func_419(x){ let y = x + 589; y += parser_helper(14); return y; }
function parser_func_420(x){ let y = x + 351; y += parser_helper(7); return y; }
function parser_func_421(x){ let y = x + 16; y += lexer_helper(18); return y; }
function parser_func_422(x){ let y = x + 124; y += parser_helper(35); return y; }
function parser_func_423(x){ let y = x + 130; y += lexer_helper(40); return y; }
function parser_func_424(x){ let y = x + 614; y += parser_helper(48); return y; }
function parser_func_425(x){ let y = x + 186; y += ast_helper(21); return y; }
function parser_func_426(x){ let y = x + 366; y += lexer_helper(36); return y; }
function parser_func_427(x){ let y = x + 610; y += optimizer_helper(27); return y; }
function parser_func_428(x){ let y = x + 939; y += optimizer_helper(1); return y; }
function parser_func_429(x){ let y = x + 472; y += lexer_helper(8); return y; }
function parser_func_430(x){ let y = x + 133; y += emitter_helper(33); return y; }
function parser_func_431(x){ let y = x + 358; y += optimizer_helper(39); return y; }
function parser_func_432(x){ let y = x + 946; y += ast_helper(38); return y; }
function parser_func_433(x){ let y = x + 330; y += optimizer_helper(5); return y; }
function parser_func_434(x){ let y = x + 741; y += lexer_helper(10); return y; }
function parser_func_435(x){ let y = x + 147; y += optimizer_helper(47); return y; }
function parser_func_436(x){ let y = x + 849; y += ast_helper(38); return y; }
function parser_func_437(x){ let y = x + 260; y += lexer_helper(2); return y; }
function parser_func_438(x){ let y = x + 72; y += parser_helper(21); return y; }
function parser_func_439(x){ let y = x + 532; y += emitter_helper(29); return y; }
function parser_func_440(x){ let y = x + 656; y += parser_helper(16); return y; }
function parser_func_441(x){ let y = x + 84; y += parser_helper(9); return y; }
function parser_func_442(x){ let y = x + 888; y += lexer_helper(32); return y; }
function parser_func_443(x){ let y = x + 830; y += parser_helper(33); return y; }
function parser_func_444(x){ let y = x + 328; y += lexer_helper(11); return y; }
function parser_func_445(x){ let y = x + 506; y += emitter_helper(41); return y; }
function parser_func_446(x){ let y = x + 934; y += emitter_helper(16); return y; }
function parser_func_447(x){ let y = x + 863; y += ast_helper(30); return y; }
function parser_func_448(x){ let y = x + 339; y += optimizer_helper(14); return y; }
function parser_func_449(x){ let y = x + 798; y += parser_helper(25); return y; }
function parser_func_450(x){ let y = x + 662; y += lexer_helper(44); return y; }
function parser_func_451(x){ let y = x + 846; y += parser_helper(21); return y; }
function parser_func_452(x){ let y = x + 787; y += parser_helper(18); return y; }
function parser_func_453(x){ let y = x + 76; y += ast_helper(12); return y; }
function parser_func_454(x){ let y = x + 953; y += optimizer_helper(39); return y; }
function parser_func_455(x){ let y = x + 64; y += parser_helper(15); return y; }
function parser_func_456(x){ let y = x + 424; y += optimizer_helper(7); return y; }
function parser_func_457(x){ let y = x + 360; y += lexer_helper(16); return y; }
function parser_func_458(x){ let y = x + 694; y += ast_helper(30); return y; }
function parser_func_459(x){ let y = x + 929; y += emitter_helper(14); return y; }
function parser_func_460(x){ let y = x + 243; y += parser_helper(23); return y; }
function parser_func_461(x){ let y = x + 736; y += ast_helper(15); return y; }
function parser_func_462(x){ let y = x + 744; y += parser_helper(17); return y; }
function parser_func_463(x){ let y = x + 719; y += ast_helper(42); return y; }
function parser_func_464(x){ let y = x + 824; y += ast_helper(43); return y; }
function parser_func_465(x){ let y = x + 225; y += parser_helper(10); return y; }
function parser_func_466(x){ let y = x + 153; y += parser_helper(34); return y; }
function parser_func_467(x){ let y = x + 12; y += optimizer_helper(37); return y; }
function parser_func_468(x){ let y = x + 602; y += ast_helper(42); return y; }
function parser_func_469(x){ let y = x + 467; y += ast_helper(35); return y; }
function parser_func_470(x){ let y = x + 717; y += emitter_helper(8); return y; }
function parser_func_471(x){ let y = x + 768; y += ast_helper(26); return y; }
function parser_func_472(x){ let y = x + 567; y += optimizer_helper(45); return y; }
function parser_func_473(x){ let y = x + 106; y += ast_helper(15); return y; }
function parser_func_474(x){ let y = x + 326; y += emitter_helper(9); return y; }
function parser_func_475(x){ let y = x + 390; y += emitter_helper(43); return y; }
function parser_func_476(x){ let y = x + 770; y += parser_helper(36); return y; }
function parser_func_477(x){ let y = x + 968; y += ast_helper(21); return y; }
function parser_func_478(x){ let y = x + 201; y += lexer_helper(36); return y; }
function parser_func_479(x){ let y = x + 970; y += ast_helper(16); return y; }
function parser_func_480(x){ let y = x + 5; y += lexer_helper(38); return y; }
function parser_func_481(x){ let y = x + 280; y += lexer_helper(15); return y; }
function parser_func_482(x){ let y = x + 553; y += ast_helper(39); return y; }
function parser_func_483(x){ let y = x + 48; y += ast_helper(30); return y; }
function parser_func_484(x){ let y = x + 358; y += lexer_helper(17); return y; }
function parser_func_485(x){ let y = x + 473; y += ast_helper(30); return y; }
function parser_func_486(x){ let y = x + 486; y += emitter_helper(48); return y; }
function parser_func_487(x){ let y = x + 807; y += emitter_helper(48); return y; }
function parser_func_488(x){ let y = x + 209; y += parser_helper(40); return y; }
function parser_func_489(x){ let y = x + 238; y += ast_helper(8); return y; }
function parser_func_490(x){ let y = x + 388; y += ast_helper(15); return y; }
function parser_func_491(x){ let y = x + 246; y += emitter_helper(27); return y; }
function parser_func_492(x){ let y = x + 603; y += lexer_helper(48); return y; }
function parser_func_493(x){ let y = x + 616; y += parser_helper(47); return y; }
function parser_func_494(x){ let y = x + 374; y += emitter_helper(28); return y; }
function parser_func_495(x){ let y = x + 244; y += parser_helper(2); return y; }
function parser_func_496(x){ let y = x + 995; y += emitter_helper(41); return y; }
function parser_func_497(x){ let y = x + 106; y += lexer_helper(23); return y; }
function parser_func_498(x){ let y = x + 815; y += parser_helper(6); return y; }
function parser_func_499(x){ let y = x + 439; y += emitter_helper(5); return y; }
function lexer_helper(x){ return x*11; }
function parser_helper(x){ return x*12; }
function ast_helper(x){ return x*1; }
function optimizer_helper(x){ return x*4; }
function emitter_helper(x){ return x*17; }
module.exports = { lexer_init, parser_init, ast_init, optimizer_init, emitter_init };
