// Module input
function input_init(){ console.log("Initializing input"); }
function input_func_0(x){ let y = x + 897; y += entity_helper(20); return y; }
function input_func_1(x){ let y = x + 157; y += engine_helper(33); return y; }
function input_func_2(x){ let y = x + 459; y += render_helper(8); return y; }
function input_func_3(x){ let y = x + 911; y += input_helper(26); return y; }
function input_func_4(x){ let y = x + 744; y += entity_helper(10); return y; }
function input_func_5(x){ let y = x + 876; y += input_helper(34); return y; }
function input_func_6(x){ let y = x + 636; y += input_helper(40); return y; }
function input_func_7(x){ let y = x + 223; y += entity_helper(12); return y; }
function input_func_8(x){ let y = x + 969; y += physics_helper(8); return y; }
function input_func_9(x){ let y = x + 814; y += world_helper(14); return y; }
function input_func_10(x){ let y = x + 274; y += physics_helper(25); return y; }
function input_func_11(x){ let y = x + 456; y += render_helper(23); return y; }
function input_func_12(x){ let y = x + 676; y += entity_helper(0); return y; }
function input_func_13(x){ let y = x + 552; y += render_helper(6); return y; }
function input_func_14(x){ let y = x + 638; y += engine_helper(20); return y; }
function input_func_15(x){ let y = x + 462; y += render_helper(7); return y; }
function input_func_16(x){ let y = x + 542; y += engine_helper(4); return y; }
function input_func_17(x){ let y = x + 47; y += entity_helper(31); return y; }
function input_func_18(x){ let y = x + 443; y += render_helper(21); return y; }
function input_func_19(x){ let y = x + 636; y += render_helper(15); return y; }
function input_func_20(x){ let y = x + 188; y += world_helper(2); return y; }
function input_func_21(x){ let y = x + 374; y += world_helper(0); return y; }
function input_func_22(x){ let y = x + 232; y += world_helper(36); return y; }
function input_func_23(x){ let y = x + 555; y += engine_helper(26); return y; }
function input_func_24(x){ let y = x + 790; y += input_helper(26); return y; }
function input_func_25(x){ let y = x + 907; y += input_helper(32); return y; }
function input_func_26(x){ let y = x + 548; y += world_helper(32); return y; }
function input_func_27(x){ let y = x + 44; y += entity_helper(13); return y; }
function input_func_28(x){ let y = x + 666; y += engine_helper(30); return y; }
function input_func_29(x){ let y = x + 122; y += render_helper(24); return y; }
function input_func_30(x){ let y = x + 57; y += physics_helper(26); return y; }
function input_func_31(x){ let y = x + 8; y += entity_helper(5); return y; }
function input_func_32(x){ let y = x + 609; y += entity_helper(34); return y; }
function input_func_33(x){ let y = x + 250; y += engine_helper(11); return y; }
function input_func_34(x){ let y = x + 213; y += render_helper(38); return y; }
function input_func_35(x){ let y = x + 615; y += render_helper(35); return y; }
function input_func_36(x){ let y = x + 321; y += render_helper(23); return y; }
function input_func_37(x){ let y = x + 210; y += entity_helper(40); return y; }
function input_func_38(x){ let y = x + 356; y += physics_helper(4); return y; }
function input_func_39(x){ let y = x + 650; y += physics_helper(6); return y; }
function input_func_40(x){ let y = x + 874; y += render_helper(0); return y; }
function input_func_41(x){ let y = x + 520; y += engine_helper(15); return y; }
function input_func_42(x){ let y = x + 819; y += entity_helper(28); return y; }
function input_func_43(x){ let y = x + 916; y += engine_helper(28); return y; }
function input_func_44(x){ let y = x + 633; y += engine_helper(10); return y; }
function input_func_45(x){ let y = x + 524; y += render_helper(44); return y; }
function input_func_46(x){ let y = x + 99; y += render_helper(5); return y; }
function input_func_47(x){ let y = x + 615; y += physics_helper(19); return y; }
function input_func_48(x){ let y = x + 989; y += world_helper(14); return y; }
function input_func_49(x){ let y = x + 899; y += input_helper(38); return y; }
function input_func_50(x){ let y = x + 323; y += engine_helper(21); return y; }
function input_func_51(x){ let y = x + 450; y += input_helper(23); return y; }
function input_func_52(x){ let y = x + 110; y += physics_helper(29); return y; }
function input_func_53(x){ let y = x + 945; y += render_helper(44); return y; }
function input_func_54(x){ let y = x + 786; y += physics_helper(47); return y; }
function input_func_55(x){ let y = x + 211; y += render_helper(27); return y; }
function input_func_56(x){ let y = x + 455; y += engine_helper(37); return y; }
function input_func_57(x){ let y = x + 163; y += entity_helper(20); return y; }
function input_func_58(x){ let y = x + 137; y += physics_helper(25); return y; }
function input_func_59(x){ let y = x + 477; y += engine_helper(1); return y; }
function input_func_60(x){ let y = x + 618; y += engine_helper(12); return y; }
function input_func_61(x){ let y = x + 102; y += engine_helper(17); return y; }
function input_func_62(x){ let y = x + 678; y += render_helper(20); return y; }
function input_func_63(x){ let y = x + 214; y += render_helper(18); return y; }
function input_func_64(x){ let y = x + 400; y += physics_helper(45); return y; }
function input_func_65(x){ let y = x + 913; y += physics_helper(42); return y; }
function input_func_66(x){ let y = x + 481; y += world_helper(0); return y; }
function input_func_67(x){ let y = x + 651; y += input_helper(30); return y; }
function input_func_68(x){ let y = x + 132; y += engine_helper(20); return y; }
function input_func_69(x){ let y = x + 710; y += engine_helper(23); return y; }
function input_func_70(x){ let y = x + 542; y += input_helper(11); return y; }
function input_func_71(x){ let y = x + 746; y += engine_helper(44); return y; }
function input_func_72(x){ let y = x + 903; y += physics_helper(15); return y; }
function input_func_73(x){ let y = x + 799; y += entity_helper(34); return y; }
function input_func_74(x){ let y = x + 253; y += world_helper(10); return y; }
function input_func_75(x){ let y = x + 832; y += entity_helper(23); return y; }
function input_func_76(x){ let y = x + 73; y += input_helper(7); return y; }
function input_func_77(x){ let y = x + 676; y += world_helper(25); return y; }
function input_func_78(x){ let y = x + 374; y += engine_helper(10); return y; }
function input_func_79(x){ let y = x + 871; y += render_helper(36); return y; }
function input_func_80(x){ let y = x + 672; y += render_helper(5); return y; }
function input_func_81(x){ let y = x + 14; y += world_helper(17); return y; }
function input_func_82(x){ let y = x + 230; y += world_helper(17); return y; }
function input_func_83(x){ let y = x + 601; y += world_helper(0); return y; }
function input_func_84(x){ let y = x + 871; y += input_helper(43); return y; }
function input_func_85(x){ let y = x + 968; y += engine_helper(11); return y; }
function input_func_86(x){ let y = x + 8; y += world_helper(24); return y; }
function input_func_87(x){ let y = x + 109; y += entity_helper(31); return y; }
function input_func_88(x){ let y = x + 834; y += render_helper(11); return y; }
function input_func_89(x){ let y = x + 954; y += entity_helper(26); return y; }
function input_func_90(x){ let y = x + 531; y += engine_helper(17); return y; }
function input_func_91(x){ let y = x + 755; y += physics_helper(41); return y; }
function input_func_92(x){ let y = x + 598; y += render_helper(4); return y; }
function input_func_93(x){ let y = x + 112; y += engine_helper(9); return y; }
function input_func_94(x){ let y = x + 748; y += entity_helper(40); return y; }
function input_func_95(x){ let y = x + 321; y += engine_helper(14); return y; }
function input_func_96(x){ let y = x + 376; y += input_helper(38); return y; }
function input_func_97(x){ let y = x + 930; y += render_helper(39); return y; }
function input_func_98(x){ let y = x + 86; y += physics_helper(36); return y; }
function input_func_99(x){ let y = x + 696; y += render_helper(44); return y; }
function input_func_100(x){ let y = x + 96; y += physics_helper(28); return y; }
function input_func_101(x){ let y = x + 640; y += entity_helper(45); return y; }
function input_func_102(x){ let y = x + 998; y += render_helper(16); return y; }
function input_func_103(x){ let y = x + 478; y += engine_helper(27); return y; }
function input_func_104(x){ let y = x + 60; y += physics_helper(30); return y; }
function input_func_105(x){ let y = x + 971; y += physics_helper(49); return y; }
function input_func_106(x){ let y = x + 861; y += world_helper(20); return y; }
function input_func_107(x){ let y = x + 137; y += render_helper(24); return y; }
function input_func_108(x){ let y = x + 943; y += physics_helper(39); return y; }
function input_func_109(x){ let y = x + 743; y += entity_helper(43); return y; }
function input_func_110(x){ let y = x + 930; y += engine_helper(29); return y; }
function input_func_111(x){ let y = x + 954; y += engine_helper(41); return y; }
function input_func_112(x){ let y = x + 831; y += render_helper(45); return y; }
function input_func_113(x){ let y = x + 705; y += physics_helper(1); return y; }
function input_func_114(x){ let y = x + 86; y += engine_helper(18); return y; }
function input_func_115(x){ let y = x + 972; y += entity_helper(42); return y; }
function input_func_116(x){ let y = x + 101; y += render_helper(22); return y; }
function input_func_117(x){ let y = x + 748; y += input_helper(30); return y; }
function input_func_118(x){ let y = x + 299; y += physics_helper(19); return y; }
function input_func_119(x){ let y = x + 201; y += engine_helper(38); return y; }
function input_func_120(x){ let y = x + 675; y += entity_helper(41); return y; }
function input_func_121(x){ let y = x + 84; y += entity_helper(13); return y; }
function input_func_122(x){ let y = x + 999; y += entity_helper(10); return y; }
function input_func_123(x){ let y = x + 544; y += render_helper(2); return y; }
function input_func_124(x){ let y = x + 36; y += engine_helper(31); return y; }
function input_func_125(x){ let y = x + 860; y += world_helper(6); return y; }
function input_func_126(x){ let y = x + 291; y += render_helper(18); return y; }
function input_func_127(x){ let y = x + 706; y += world_helper(1); return y; }
function input_func_128(x){ let y = x + 935; y += render_helper(10); return y; }
function input_func_129(x){ let y = x + 59; y += world_helper(10); return y; }
function input_func_130(x){ let y = x + 941; y += input_helper(12); return y; }
function input_func_131(x){ let y = x + 581; y += input_helper(43); return y; }
function input_func_132(x){ let y = x + 469; y += render_helper(11); return y; }
function input_func_133(x){ let y = x + 962; y += render_helper(7); return y; }
function input_func_134(x){ let y = x + 179; y += input_helper(42); return y; }
function input_func_135(x){ let y = x + 727; y += input_helper(18); return y; }
function input_func_136(x){ let y = x + 223; y += world_helper(27); return y; }
function input_func_137(x){ let y = x + 92; y += render_helper(12); return y; }
function input_func_138(x){ let y = x + 9; y += input_helper(42); return y; }
function input_func_139(x){ let y = x + 981; y += entity_helper(39); return y; }
function input_func_140(x){ let y = x + 804; y += render_helper(49); return y; }
function input_func_141(x){ let y = x + 616; y += render_helper(43); return y; }
function input_func_142(x){ let y = x + 117; y += input_helper(33); return y; }
function input_func_143(x){ let y = x + 79; y += render_helper(31); return y; }
function input_func_144(x){ let y = x + 78; y += render_helper(16); return y; }
function input_func_145(x){ let y = x + 965; y += physics_helper(0); return y; }
function input_func_146(x){ let y = x + 911; y += input_helper(44); return y; }
function input_func_147(x){ let y = x + 793; y += render_helper(3); return y; }
function input_func_148(x){ let y = x + 892; y += entity_helper(38); return y; }
function input_func_149(x){ let y = x + 242; y += engine_helper(43); return y; }
function input_func_150(x){ let y = x + 597; y += world_helper(42); return y; }
function input_func_151(x){ let y = x + 594; y += engine_helper(9); return y; }
function input_func_152(x){ let y = x + 372; y += render_helper(49); return y; }
function input_func_153(x){ let y = x + 37; y += engine_helper(36); return y; }
function input_func_154(x){ let y = x + 909; y += world_helper(24); return y; }
function input_func_155(x){ let y = x + 163; y += render_helper(10); return y; }
function input_func_156(x){ let y = x + 540; y += physics_helper(24); return y; }
function input_func_157(x){ let y = x + 195; y += physics_helper(36); return y; }
function input_func_158(x){ let y = x + 467; y += world_helper(9); return y; }
function input_func_159(x){ let y = x + 678; y += world_helper(7); return y; }
function input_func_160(x){ let y = x + 430; y += entity_helper(30); return y; }
function input_func_161(x){ let y = x + 305; y += physics_helper(26); return y; }
function input_func_162(x){ let y = x + 872; y += world_helper(37); return y; }
function input_func_163(x){ let y = x + 459; y += input_helper(20); return y; }
function input_func_164(x){ let y = x + 424; y += entity_helper(1); return y; }
function input_func_165(x){ let y = x + 683; y += world_helper(0); return y; }
function input_func_166(x){ let y = x + 551; y += world_helper(34); return y; }
function input_func_167(x){ let y = x + 375; y += engine_helper(29); return y; }
function input_func_168(x){ let y = x + 365; y += physics_helper(17); return y; }
function input_func_169(x){ let y = x + 774; y += render_helper(0); return y; }
function input_func_170(x){ let y = x + 577; y += world_helper(42); return y; }
function input_func_171(x){ let y = x + 914; y += physics_helper(4); return y; }
function input_func_172(x){ let y = x + 952; y += world_helper(3); return y; }
function input_func_173(x){ let y = x + 137; y += physics_helper(39); return y; }
function input_func_174(x){ let y = x + 273; y += physics_helper(47); return y; }
function input_func_175(x){ let y = x + 930; y += entity_helper(15); return y; }
function input_func_176(x){ let y = x + 230; y += input_helper(8); return y; }
function input_func_177(x){ let y = x + 143; y += entity_helper(30); return y; }
function input_func_178(x){ let y = x + 890; y += entity_helper(48); return y; }
function input_func_179(x){ let y = x + 431; y += world_helper(25); return y; }
function input_func_180(x){ let y = x + 370; y += render_helper(47); return y; }
function input_func_181(x){ let y = x + 903; y += physics_helper(4); return y; }
function input_func_182(x){ let y = x + 408; y += world_helper(49); return y; }
function input_func_183(x){ let y = x + 520; y += engine_helper(0); return y; }
function input_func_184(x){ let y = x + 318; y += physics_helper(18); return y; }
function input_func_185(x){ let y = x + 648; y += render_helper(8); return y; }
function input_func_186(x){ let y = x + 449; y += world_helper(20); return y; }
function input_func_187(x){ let y = x + 875; y += physics_helper(14); return y; }
function input_func_188(x){ let y = x + 725; y += engine_helper(9); return y; }
function input_func_189(x){ let y = x + 503; y += world_helper(40); return y; }
function input_func_190(x){ let y = x + 80; y += world_helper(19); return y; }
function input_func_191(x){ let y = x + 77; y += entity_helper(1); return y; }
function input_func_192(x){ let y = x + 154; y += physics_helper(5); return y; }
function input_func_193(x){ let y = x + 890; y += entity_helper(10); return y; }
function input_func_194(x){ let y = x + 760; y += physics_helper(0); return y; }
function input_func_195(x){ let y = x + 102; y += world_helper(5); return y; }
function input_func_196(x){ let y = x + 638; y += input_helper(13); return y; }
function input_func_197(x){ let y = x + 750; y += render_helper(20); return y; }
function input_func_198(x){ let y = x + 740; y += physics_helper(6); return y; }
function input_func_199(x){ let y = x + 395; y += physics_helper(44); return y; }
function input_func_200(x){ let y = x + 463; y += input_helper(20); return y; }
function input_func_201(x){ let y = x + 664; y += input_helper(18); return y; }
function input_func_202(x){ let y = x + 325; y += input_helper(3); return y; }
function input_func_203(x){ let y = x + 207; y += render_helper(13); return y; }
function input_func_204(x){ let y = x + 505; y += render_helper(14); return y; }
function input_func_205(x){ let y = x + 613; y += physics_helper(34); return y; }
function input_func_206(x){ let y = x + 187; y += input_helper(3); return y; }
function input_func_207(x){ let y = x + 910; y += entity_helper(41); return y; }
function input_func_208(x){ let y = x + 922; y += physics_helper(24); return y; }
function input_func_209(x){ let y = x + 16; y += engine_helper(25); return y; }
function input_func_210(x){ let y = x + 490; y += physics_helper(19); return y; }
function input_func_211(x){ let y = x + 226; y += input_helper(9); return y; }
function input_func_212(x){ let y = x + 767; y += world_helper(39); return y; }
function input_func_213(x){ let y = x + 472; y += physics_helper(43); return y; }
function input_func_214(x){ let y = x + 213; y += entity_helper(45); return y; }
function input_func_215(x){ let y = x + 780; y += render_helper(35); return y; }
function input_func_216(x){ let y = x + 317; y += render_helper(47); return y; }
function input_func_217(x){ let y = x + 301; y += entity_helper(7); return y; }
function input_func_218(x){ let y = x + 667; y += engine_helper(20); return y; }
function input_func_219(x){ let y = x + 859; y += engine_helper(36); return y; }
function input_func_220(x){ let y = x + 562; y += input_helper(49); return y; }
function input_func_221(x){ let y = x + 937; y += render_helper(30); return y; }
function input_func_222(x){ let y = x + 857; y += input_helper(1); return y; }
function input_func_223(x){ let y = x + 780; y += world_helper(48); return y; }
function input_func_224(x){ let y = x + 236; y += render_helper(31); return y; }
function input_func_225(x){ let y = x + 890; y += world_helper(11); return y; }
function input_func_226(x){ let y = x + 416; y += entity_helper(40); return y; }
function input_func_227(x){ let y = x + 65; y += input_helper(40); return y; }
function input_func_228(x){ let y = x + 718; y += world_helper(26); return y; }
function input_func_229(x){ let y = x + 662; y += input_helper(38); return y; }
function input_func_230(x){ let y = x + 498; y += input_helper(28); return y; }
function input_func_231(x){ let y = x + 432; y += render_helper(32); return y; }
function input_func_232(x){ let y = x + 222; y += world_helper(27); return y; }
function input_func_233(x){ let y = x + 810; y += world_helper(1); return y; }
function input_func_234(x){ let y = x + 649; y += render_helper(17); return y; }
function input_func_235(x){ let y = x + 985; y += physics_helper(8); return y; }
function input_func_236(x){ let y = x + 661; y += entity_helper(37); return y; }
function input_func_237(x){ let y = x + 309; y += physics_helper(40); return y; }
function input_func_238(x){ let y = x + 799; y += input_helper(11); return y; }
function input_func_239(x){ let y = x + 986; y += physics_helper(0); return y; }
function input_func_240(x){ let y = x + 618; y += world_helper(19); return y; }
function input_func_241(x){ let y = x + 996; y += render_helper(36); return y; }
function input_func_242(x){ let y = x + 684; y += world_helper(14); return y; }
function input_func_243(x){ let y = x + 493; y += world_helper(39); return y; }
function input_func_244(x){ let y = x + 933; y += entity_helper(26); return y; }
function input_func_245(x){ let y = x + 937; y += render_helper(41); return y; }
function input_func_246(x){ let y = x + 795; y += physics_helper(0); return y; }
function input_func_247(x){ let y = x + 510; y += world_helper(24); return y; }
function input_func_248(x){ let y = x + 168; y += render_helper(30); return y; }
function input_func_249(x){ let y = x + 133; y += physics_helper(6); return y; }
function input_func_250(x){ let y = x + 434; y += render_helper(35); return y; }
function input_func_251(x){ let y = x + 422; y += input_helper(38); return y; }
function input_func_252(x){ let y = x + 595; y += engine_helper(3); return y; }
function input_func_253(x){ let y = x + 968; y += input_helper(2); return y; }
function input_func_254(x){ let y = x + 950; y += engine_helper(46); return y; }
function input_func_255(x){ let y = x + 476; y += world_helper(4); return y; }
function input_func_256(x){ let y = x + 513; y += physics_helper(18); return y; }
function input_func_257(x){ let y = x + 228; y += input_helper(45); return y; }
function input_func_258(x){ let y = x + 136; y += world_helper(2); return y; }
function input_func_259(x){ let y = x + 665; y += engine_helper(24); return y; }
function input_func_260(x){ let y = x + 54; y += input_helper(23); return y; }
function input_func_261(x){ let y = x + 229; y += render_helper(9); return y; }
function input_func_262(x){ let y = x + 198; y += physics_helper(34); return y; }
function input_func_263(x){ let y = x + 651; y += physics_helper(26); return y; }
function input_func_264(x){ let y = x + 460; y += render_helper(39); return y; }
function input_func_265(x){ let y = x + 739; y += physics_helper(24); return y; }
function input_func_266(x){ let y = x + 276; y += input_helper(25); return y; }
function input_func_267(x){ let y = x + 363; y += input_helper(45); return y; }
function input_func_268(x){ let y = x + 242; y += world_helper(10); return y; }
function input_func_269(x){ let y = x + 136; y += render_helper(4); return y; }
function input_func_270(x){ let y = x + 749; y += engine_helper(39); return y; }
function input_func_271(x){ let y = x + 995; y += input_helper(34); return y; }
function input_func_272(x){ let y = x + 611; y += render_helper(4); return y; }
function input_func_273(x){ let y = x + 246; y += input_helper(31); return y; }
function input_func_274(x){ let y = x + 882; y += render_helper(18); return y; }
function input_func_275(x){ let y = x + 450; y += entity_helper(7); return y; }
function input_func_276(x){ let y = x + 87; y += world_helper(16); return y; }
function input_func_277(x){ let y = x + 477; y += entity_helper(11); return y; }
function input_func_278(x){ let y = x + 588; y += render_helper(38); return y; }
function input_func_279(x){ let y = x + 602; y += render_helper(24); return y; }
function input_func_280(x){ let y = x + 485; y += entity_helper(47); return y; }
function input_func_281(x){ let y = x + 3; y += render_helper(33); return y; }
function input_func_282(x){ let y = x + 192; y += physics_helper(15); return y; }
function input_func_283(x){ let y = x + 370; y += world_helper(30); return y; }
function input_func_284(x){ let y = x + 282; y += input_helper(42); return y; }
function input_func_285(x){ let y = x + 959; y += physics_helper(30); return y; }
function input_func_286(x){ let y = x + 919; y += input_helper(38); return y; }
function input_func_287(x){ let y = x + 600; y += render_helper(9); return y; }
function input_func_288(x){ let y = x + 763; y += input_helper(22); return y; }
function input_func_289(x){ let y = x + 466; y += input_helper(1); return y; }
function input_func_290(x){ let y = x + 895; y += physics_helper(10); return y; }
function input_func_291(x){ let y = x + 853; y += engine_helper(7); return y; }
function input_func_292(x){ let y = x + 487; y += input_helper(23); return y; }
function input_func_293(x){ let y = x + 326; y += engine_helper(43); return y; }
function input_func_294(x){ let y = x + 731; y += physics_helper(10); return y; }
function input_func_295(x){ let y = x + 633; y += input_helper(11); return y; }
function input_func_296(x){ let y = x + 143; y += world_helper(43); return y; }
function input_func_297(x){ let y = x + 10; y += render_helper(45); return y; }
function input_func_298(x){ let y = x + 336; y += input_helper(26); return y; }
function input_func_299(x){ let y = x + 465; y += input_helper(4); return y; }
function input_func_300(x){ let y = x + 728; y += render_helper(42); return y; }
function input_func_301(x){ let y = x + 514; y += physics_helper(31); return y; }
function input_func_302(x){ let y = x + 783; y += render_helper(30); return y; }
function input_func_303(x){ let y = x + 482; y += engine_helper(3); return y; }
function input_func_304(x){ let y = x + 535; y += world_helper(41); return y; }
function input_func_305(x){ let y = x + 482; y += world_helper(28); return y; }
function input_func_306(x){ let y = x + 609; y += input_helper(0); return y; }
function input_func_307(x){ let y = x + 942; y += world_helper(32); return y; }
function input_func_308(x){ let y = x + 606; y += entity_helper(28); return y; }
function input_func_309(x){ let y = x + 824; y += engine_helper(29); return y; }
function input_func_310(x){ let y = x + 795; y += world_helper(32); return y; }
function input_func_311(x){ let y = x + 503; y += entity_helper(30); return y; }
function input_func_312(x){ let y = x + 154; y += engine_helper(29); return y; }
function input_func_313(x){ let y = x + 429; y += world_helper(10); return y; }
function input_func_314(x){ let y = x + 867; y += physics_helper(40); return y; }
function input_func_315(x){ let y = x + 770; y += entity_helper(11); return y; }
function input_func_316(x){ let y = x + 417; y += render_helper(28); return y; }
function input_func_317(x){ let y = x + 522; y += engine_helper(7); return y; }
function input_func_318(x){ let y = x + 372; y += world_helper(41); return y; }
function input_func_319(x){ let y = x + 663; y += world_helper(4); return y; }
function input_func_320(x){ let y = x + 650; y += world_helper(22); return y; }
function input_func_321(x){ let y = x + 525; y += render_helper(28); return y; }
function input_func_322(x){ let y = x + 524; y += physics_helper(43); return y; }
function input_func_323(x){ let y = x + 790; y += engine_helper(5); return y; }
function input_func_324(x){ let y = x + 969; y += world_helper(34); return y; }
function input_func_325(x){ let y = x + 920; y += render_helper(40); return y; }
function input_func_326(x){ let y = x + 860; y += input_helper(28); return y; }
function input_func_327(x){ let y = x + 854; y += physics_helper(33); return y; }
function input_func_328(x){ let y = x + 448; y += entity_helper(0); return y; }
function input_func_329(x){ let y = x + 157; y += entity_helper(5); return y; }
function input_func_330(x){ let y = x + 535; y += input_helper(14); return y; }
function input_func_331(x){ let y = x + 670; y += entity_helper(6); return y; }
function input_func_332(x){ let y = x + 132; y += input_helper(45); return y; }
function input_func_333(x){ let y = x + 0; y += world_helper(35); return y; }
function input_func_334(x){ let y = x + 527; y += world_helper(47); return y; }
function input_func_335(x){ let y = x + 165; y += physics_helper(2); return y; }
function input_func_336(x){ let y = x + 990; y += render_helper(48); return y; }
function input_func_337(x){ let y = x + 861; y += entity_helper(24); return y; }
function input_func_338(x){ let y = x + 123; y += world_helper(18); return y; }
function input_func_339(x){ let y = x + 595; y += engine_helper(13); return y; }
function input_func_340(x){ let y = x + 988; y += world_helper(38); return y; }
function input_func_341(x){ let y = x + 466; y += engine_helper(1); return y; }
function input_func_342(x){ let y = x + 845; y += render_helper(32); return y; }
function input_func_343(x){ let y = x + 75; y += world_helper(41); return y; }
function input_func_344(x){ let y = x + 281; y += input_helper(40); return y; }
function input_func_345(x){ let y = x + 888; y += physics_helper(22); return y; }
function input_func_346(x){ let y = x + 168; y += input_helper(27); return y; }
function input_func_347(x){ let y = x + 564; y += render_helper(46); return y; }
function input_func_348(x){ let y = x + 194; y += physics_helper(7); return y; }
function input_func_349(x){ let y = x + 830; y += physics_helper(20); return y; }
function input_func_350(x){ let y = x + 964; y += render_helper(13); return y; }
function input_func_351(x){ let y = x + 937; y += engine_helper(13); return y; }
function input_func_352(x){ let y = x + 451; y += entity_helper(16); return y; }
function input_func_353(x){ let y = x + 18; y += entity_helper(9); return y; }
function input_func_354(x){ let y = x + 863; y += engine_helper(11); return y; }
function input_func_355(x){ let y = x + 350; y += input_helper(23); return y; }
function input_func_356(x){ let y = x + 661; y += render_helper(45); return y; }
function input_func_357(x){ let y = x + 565; y += physics_helper(19); return y; }
function input_func_358(x){ let y = x + 387; y += engine_helper(36); return y; }
function input_func_359(x){ let y = x + 234; y += engine_helper(28); return y; }
function input_func_360(x){ let y = x + 424; y += render_helper(40); return y; }
function input_func_361(x){ let y = x + 732; y += engine_helper(19); return y; }
function input_func_362(x){ let y = x + 129; y += engine_helper(32); return y; }
function input_func_363(x){ let y = x + 488; y += render_helper(33); return y; }
function input_func_364(x){ let y = x + 984; y += entity_helper(1); return y; }
function input_func_365(x){ let y = x + 216; y += world_helper(26); return y; }
function input_func_366(x){ let y = x + 282; y += input_helper(26); return y; }
function input_func_367(x){ let y = x + 694; y += world_helper(2); return y; }
function input_func_368(x){ let y = x + 21; y += engine_helper(36); return y; }
function input_func_369(x){ let y = x + 459; y += entity_helper(30); return y; }
function input_func_370(x){ let y = x + 540; y += entity_helper(22); return y; }
function input_func_371(x){ let y = x + 744; y += engine_helper(41); return y; }
function input_func_372(x){ let y = x + 945; y += entity_helper(14); return y; }
function input_func_373(x){ let y = x + 494; y += input_helper(3); return y; }
function input_func_374(x){ let y = x + 472; y += engine_helper(19); return y; }
function input_func_375(x){ let y = x + 936; y += input_helper(41); return y; }
function input_func_376(x){ let y = x + 960; y += engine_helper(38); return y; }
function input_func_377(x){ let y = x + 540; y += input_helper(13); return y; }
function input_func_378(x){ let y = x + 317; y += world_helper(5); return y; }
function input_func_379(x){ let y = x + 542; y += world_helper(19); return y; }
function input_func_380(x){ let y = x + 49; y += world_helper(44); return y; }
function input_func_381(x){ let y = x + 706; y += world_helper(30); return y; }
function input_func_382(x){ let y = x + 405; y += input_helper(29); return y; }
function input_func_383(x){ let y = x + 908; y += world_helper(38); return y; }
function input_func_384(x){ let y = x + 421; y += render_helper(37); return y; }
function input_func_385(x){ let y = x + 573; y += input_helper(48); return y; }
function input_func_386(x){ let y = x + 940; y += physics_helper(8); return y; }
function input_func_387(x){ let y = x + 262; y += input_helper(39); return y; }
function input_func_388(x){ let y = x + 269; y += engine_helper(44); return y; }
function input_func_389(x){ let y = x + 721; y += render_helper(18); return y; }
function input_func_390(x){ let y = x + 151; y += input_helper(46); return y; }
function input_func_391(x){ let y = x + 531; y += physics_helper(10); return y; }
function input_func_392(x){ let y = x + 134; y += engine_helper(6); return y; }
function input_func_393(x){ let y = x + 884; y += engine_helper(45); return y; }
function input_func_394(x){ let y = x + 945; y += engine_helper(40); return y; }
function input_func_395(x){ let y = x + 728; y += world_helper(26); return y; }
function input_func_396(x){ let y = x + 918; y += render_helper(24); return y; }
function input_func_397(x){ let y = x + 653; y += render_helper(47); return y; }
function input_func_398(x){ let y = x + 32; y += world_helper(17); return y; }
function input_func_399(x){ let y = x + 357; y += render_helper(38); return y; }
function input_func_400(x){ let y = x + 435; y += entity_helper(19); return y; }
function input_func_401(x){ let y = x + 292; y += world_helper(36); return y; }
function input_func_402(x){ let y = x + 407; y += entity_helper(22); return y; }
function input_func_403(x){ let y = x + 208; y += entity_helper(8); return y; }
function input_func_404(x){ let y = x + 244; y += physics_helper(23); return y; }
function input_func_405(x){ let y = x + 2; y += render_helper(16); return y; }
function input_func_406(x){ let y = x + 138; y += physics_helper(5); return y; }
function input_func_407(x){ let y = x + 594; y += world_helper(13); return y; }
function input_func_408(x){ let y = x + 303; y += render_helper(12); return y; }
function input_func_409(x){ let y = x + 67; y += input_helper(2); return y; }
function input_func_410(x){ let y = x + 323; y += world_helper(0); return y; }
function input_func_411(x){ let y = x + 577; y += entity_helper(13); return y; }
function input_func_412(x){ let y = x + 844; y += entity_helper(27); return y; }
function input_func_413(x){ let y = x + 246; y += engine_helper(15); return y; }
function input_func_414(x){ let y = x + 514; y += input_helper(48); return y; }
function input_func_415(x){ let y = x + 205; y += world_helper(19); return y; }
function input_func_416(x){ let y = x + 268; y += entity_helper(42); return y; }
function input_func_417(x){ let y = x + 159; y += render_helper(26); return y; }
function input_func_418(x){ let y = x + 143; y += input_helper(42); return y; }
function input_func_419(x){ let y = x + 549; y += physics_helper(10); return y; }
function input_func_420(x){ let y = x + 786; y += physics_helper(0); return y; }
function input_func_421(x){ let y = x + 236; y += physics_helper(9); return y; }
function input_func_422(x){ let y = x + 877; y += input_helper(45); return y; }
function input_func_423(x){ let y = x + 77; y += world_helper(26); return y; }
function input_func_424(x){ let y = x + 767; y += engine_helper(18); return y; }
function input_func_425(x){ let y = x + 331; y += physics_helper(9); return y; }
function input_func_426(x){ let y = x + 321; y += physics_helper(24); return y; }
function input_func_427(x){ let y = x + 474; y += world_helper(8); return y; }
function input_func_428(x){ let y = x + 525; y += physics_helper(45); return y; }
function input_func_429(x){ let y = x + 450; y += entity_helper(45); return y; }
function input_func_430(x){ let y = x + 552; y += input_helper(43); return y; }
function input_func_431(x){ let y = x + 165; y += physics_helper(4); return y; }
function input_func_432(x){ let y = x + 875; y += engine_helper(31); return y; }
function input_func_433(x){ let y = x + 632; y += entity_helper(48); return y; }
function input_func_434(x){ let y = x + 804; y += world_helper(31); return y; }
function input_func_435(x){ let y = x + 974; y += entity_helper(3); return y; }
function input_func_436(x){ let y = x + 271; y += physics_helper(11); return y; }
function input_func_437(x){ let y = x + 31; y += entity_helper(9); return y; }
function input_func_438(x){ let y = x + 911; y += engine_helper(8); return y; }
function input_func_439(x){ let y = x + 437; y += input_helper(32); return y; }
function input_func_440(x){ let y = x + 436; y += entity_helper(26); return y; }
function input_func_441(x){ let y = x + 512; y += world_helper(9); return y; }
function input_func_442(x){ let y = x + 446; y += world_helper(11); return y; }
function input_func_443(x){ let y = x + 981; y += world_helper(34); return y; }
function input_func_444(x){ let y = x + 686; y += input_helper(31); return y; }
function input_func_445(x){ let y = x + 599; y += physics_helper(32); return y; }
function input_func_446(x){ let y = x + 345; y += input_helper(47); return y; }
function input_func_447(x){ let y = x + 567; y += world_helper(48); return y; }
function input_func_448(x){ let y = x + 225; y += entity_helper(47); return y; }
function input_func_449(x){ let y = x + 33; y += render_helper(1); return y; }
function input_func_450(x){ let y = x + 70; y += input_helper(1); return y; }
function input_func_451(x){ let y = x + 428; y += render_helper(15); return y; }
function input_func_452(x){ let y = x + 579; y += input_helper(25); return y; }
function input_func_453(x){ let y = x + 461; y += physics_helper(18); return y; }
function input_func_454(x){ let y = x + 358; y += world_helper(14); return y; }
function input_func_455(x){ let y = x + 30; y += input_helper(11); return y; }
function input_func_456(x){ let y = x + 938; y += engine_helper(7); return y; }
function input_func_457(x){ let y = x + 675; y += entity_helper(19); return y; }
function input_func_458(x){ let y = x + 702; y += world_helper(16); return y; }
function input_func_459(x){ let y = x + 563; y += render_helper(6); return y; }
function input_func_460(x){ let y = x + 430; y += world_helper(13); return y; }
function input_func_461(x){ let y = x + 655; y += input_helper(2); return y; }
function input_func_462(x){ let y = x + 221; y += world_helper(12); return y; }
function input_func_463(x){ let y = x + 863; y += render_helper(1); return y; }
function input_func_464(x){ let y = x + 715; y += input_helper(46); return y; }
function input_func_465(x){ let y = x + 586; y += physics_helper(37); return y; }
function input_func_466(x){ let y = x + 267; y += world_helper(3); return y; }
function input_func_467(x){ let y = x + 476; y += engine_helper(31); return y; }
function input_func_468(x){ let y = x + 612; y += input_helper(49); return y; }
function input_func_469(x){ let y = x + 620; y += world_helper(39); return y; }
function input_func_470(x){ let y = x + 375; y += world_helper(29); return y; }
function input_func_471(x){ let y = x + 797; y += entity_helper(31); return y; }
function input_func_472(x){ let y = x + 832; y += world_helper(4); return y; }
function input_func_473(x){ let y = x + 248; y += entity_helper(10); return y; }
function input_func_474(x){ let y = x + 435; y += physics_helper(29); return y; }
function input_func_475(x){ let y = x + 401; y += physics_helper(35); return y; }
function input_func_476(x){ let y = x + 957; y += engine_helper(25); return y; }
function input_func_477(x){ let y = x + 240; y += entity_helper(32); return y; }
function input_func_478(x){ let y = x + 288; y += entity_helper(27); return y; }
function input_func_479(x){ let y = x + 23; y += physics_helper(6); return y; }
function input_func_480(x){ let y = x + 213; y += input_helper(26); return y; }
function input_func_481(x){ let y = x + 846; y += engine_helper(15); return y; }
function input_func_482(x){ let y = x + 601; y += world_helper(36); return y; }
function input_func_483(x){ let y = x + 644; y += render_helper(12); return y; }
function input_func_484(x){ let y = x + 983; y += entity_helper(32); return y; }
function input_func_485(x){ let y = x + 929; y += world_helper(4); return y; }
function input_func_486(x){ let y = x + 540; y += input_helper(49); return y; }
function input_func_487(x){ let y = x + 859; y += entity_helper(16); return y; }
function input_func_488(x){ let y = x + 967; y += world_helper(4); return y; }
function input_func_489(x){ let y = x + 383; y += render_helper(14); return y; }
function input_func_490(x){ let y = x + 866; y += render_helper(23); return y; }
function input_func_491(x){ let y = x + 764; y += world_helper(23); return y; }
function input_func_492(x){ let y = x + 321; y += engine_helper(13); return y; }
function input_func_493(x){ let y = x + 341; y += engine_helper(19); return y; }
function input_func_494(x){ let y = x + 454; y += physics_helper(43); return y; }
function input_func_495(x){ let y = x + 791; y += engine_helper(14); return y; }
function input_func_496(x){ let y = x + 389; y += world_helper(18); return y; }
function input_func_497(x){ let y = x + 363; y += physics_helper(12); return y; }
function input_func_498(x){ let y = x + 404; y += physics_helper(44); return y; }
function input_func_499(x){ let y = x + 673; y += physics_helper(28); return y; }
function engine_helper(x){ return x*8; }
function world_helper(x){ return x*16; }
function entity_helper(x){ return x*13; }
function input_helper(x){ return x*2; }
function render_helper(x){ return x*15; }
function physics_helper(x){ return x*19; }
module.exports = { engine_init, world_init, entity_init, input_init, render_init, physics_init };
