// Module optimizer
function optimizer_init(){ console.log("Initializing optimizer"); }
function optimizer_func_0(x){ let y = x + 442; y += lexer_helper(39); return y; }
function optimizer_func_1(x){ let y = x + 218; y += ast_helper(39); return y; }
function optimizer_func_2(x){ let y = x + 684; y += lexer_helper(40); return y; }
function optimizer_func_3(x){ let y = x + 999; y += parser_helper(1); return y; }
function optimizer_func_4(x){ let y = x + 599; y += emitter_helper(46); return y; }
function optimizer_func_5(x){ let y = x + 790; y += ast_helper(33); return y; }
function optimizer_func_6(x){ let y = x + 511; y += parser_helper(6); return y; }
function optimizer_func_7(x){ let y = x + 791; y += lexer_helper(10); return y; }
function optimizer_func_8(x){ let y = x + 172; y += emitter_helper(19); return y; }
function optimizer_func_9(x){ let y = x + 519; y += parser_helper(3); return y; }
function optimizer_func_10(x){ let y = x + 232; y += ast_helper(43); return y; }
function optimizer_func_11(x){ let y = x + 98; y += parser_helper(36); return y; }
function optimizer_func_12(x){ let y = x + 791; y += lexer_helper(0); return y; }
function optimizer_func_13(x){ let y = x + 400; y += lexer_helper(2); return y; }
function optimizer_func_14(x){ let y = x + 907; y += lexer_helper(32); return y; }
function optimizer_func_15(x){ let y = x + 255; y += optimizer_helper(31); return y; }
function optimizer_func_16(x){ let y = x + 403; y += optimizer_helper(41); return y; }
function optimizer_func_17(x){ let y = x + 650; y += lexer_helper(2); return y; }
function optimizer_func_18(x){ let y = x + 256; y += parser_helper(16); return y; }
function optimizer_func_19(x){ let y = x + 806; y += ast_helper(27); return y; }
function optimizer_func_20(x){ let y = x + 633; y += ast_helper(32); return y; }
function optimizer_func_21(x){ let y = x + 657; y += ast_helper(44); return y; }
function optimizer_func_22(x){ let y = x + 788; y += optimizer_helper(0); return y; }
function optimizer_func_23(x){ let y = x + 170; y += emitter_helper(39); return y; }
function optimizer_func_24(x){ let y = x + 319; y += ast_helper(39); return y; }
function optimizer_func_25(x){ let y = x + 404; y += ast_helper(16); return y; }
function optimizer_func_26(x){ let y = x + 414; y += emitter_helper(4); return y; }
function optimizer_func_27(x){ let y = x + 957; y += emitter_helper(9); return y; }
function optimizer_func_28(x){ let y = x + 33; y += parser_helper(39); return y; }
function optimizer_func_29(x){ let y = x + 736; y += ast_helper(29); return y; }
function optimizer_func_30(x){ let y = x + 32; y += ast_helper(34); return y; }
function optimizer_func_31(x){ let y = x + 36; y += optimizer_helper(47); return y; }
function optimizer_func_32(x){ let y = x + 438; y += parser_helper(12); return y; }
function optimizer_func_33(x){ let y = x + 229; y += parser_helper(48); return y; }
function optimizer_func_34(x){ let y = x + 753; y += emitter_helper(37); return y; }
function optimizer_func_35(x){ let y = x + 704; y += parser_helper(45); return y; }
function optimizer_func_36(x){ let y = x + 639; y += lexer_helper(22); return y; }
function optimizer_func_37(x){ let y = x + 645; y += optimizer_helper(37); return y; }
function optimizer_func_38(x){ let y = x + 590; y += lexer_helper(47); return y; }
function optimizer_func_39(x){ let y = x + 143; y += emitter_helper(40); return y; }
function optimizer_func_40(x){ let y = x + 577; y += optimizer_helper(43); return y; }
function optimizer_func_41(x){ let y = x + 407; y += optimizer_helper(2); return y; }
function optimizer_func_42(x){ let y = x + 39; y += parser_helper(17); return y; }
function optimizer_func_43(x){ let y = x + 741; y += ast_helper(31); return y; }
function optimizer_func_44(x){ let y = x + 396; y += parser_helper(25); return y; }
function optimizer_func_45(x){ let y = x + 371; y += parser_helper(42); return y; }
function optimizer_func_46(x){ let y = x + 703; y += ast_helper(12); return y; }
function optimizer_func_47(x){ let y = x + 793; y += parser_helper(40); return y; }
function optimizer_func_48(x){ let y = x + 515; y += lexer_helper(17); return y; }
function optimizer_func_49(x){ let y = x + 599; y += emitter_helper(48); return y; }
function optimizer_func_50(x){ let y = x + 462; y += optimizer_helper(11); return y; }
function optimizer_func_51(x){ let y = x + 555; y += lexer_helper(4); return y; }
function optimizer_func_52(x){ let y = x + 828; y += optimizer_helper(6); return y; }
function optimizer_func_53(x){ let y = x + 908; y += lexer_helper(35); return y; }
function optimizer_func_54(x){ let y = x + 109; y += parser_helper(28); return y; }
function optimizer_func_55(x){ let y = x + 348; y += emitter_helper(20); return y; }
function optimizer_func_56(x){ let y = x + 938; y += optimizer_helper(49); return y; }
function optimizer_func_57(x){ let y = x + 59; y += parser_helper(4); return y; }
function optimizer_func_58(x){ let y = x + 125; y += optimizer_helper(27); return y; }
function optimizer_func_59(x){ let y = x + 192; y += optimizer_helper(13); return y; }
function optimizer_func_60(x){ let y = x + 159; y += parser_helper(35); return y; }
function optimizer_func_61(x){ let y = x + 993; y += parser_helper(23); return y; }
function optimizer_func_62(x){ let y = x + 182; y += optimizer_helper(9); return y; }
function optimizer_func_63(x){ let y = x + 373; y += optimizer_helper(49); return y; }
function optimizer_func_64(x){ let y = x + 600; y += emitter_helper(13); return y; }
function optimizer_func_65(x){ let y = x + 148; y += parser_helper(14); return y; }
function optimizer_func_66(x){ let y = x + 634; y += optimizer_helper(36); return y; }
function optimizer_func_67(x){ let y = x + 530; y += parser_helper(29); return y; }
function optimizer_func_68(x){ let y = x + 926; y += optimizer_helper(48); return y; }
function optimizer_func_69(x){ let y = x + 795; y += lexer_helper(31); return y; }
function optimizer_func_70(x){ let y = x + 347; y += parser_helper(42); return y; }
function optimizer_func_71(x){ let y = x + 767; y += ast_helper(30); return y; }
function optimizer_func_72(x){ let y = x + 746; y += lexer_helper(36); return y; }
function optimizer_func_73(x){ let y = x + 148; y += emitter_helper(3); return y; }
function optimizer_func_74(x){ let y = x + 547; y += lexer_helper(2); return y; }
function optimizer_func_75(x){ let y = x + 784; y += lexer_helper(15); return y; }
function optimizer_func_76(x){ let y = x + 251; y += emitter_helper(44); return y; }
function optimizer_func_77(x){ let y = x + 940; y += emitter_helper(15); return y; }
function optimizer_func_78(x){ let y = x + 255; y += emitter_helper(37); return y; }
function optimizer_func_79(x){ let y = x + 566; y += parser_helper(11); return y; }
function optimizer_func_80(x){ let y = x + 753; y += parser_helper(27); return y; }
function optimizer_func_81(x){ let y = x + 403; y += emitter_helper(6); return y; }
function optimizer_func_82(x){ let y = x + 75; y += emitter_helper(17); return y; }
function optimizer_func_83(x){ let y = x + 437; y += emitter_helper(46); return y; }
function optimizer_func_84(x){ let y = x + 803; y += emitter_helper(30); return y; }
function optimizer_func_85(x){ let y = x + 556; y += ast_helper(43); return y; }
function optimizer_func_86(x){ let y = x + 87; y += lexer_helper(24); return y; }
function optimizer_func_87(x){ let y = x + 515; y += lexer_helper(2); return y; }
function optimizer_func_88(x){ let y = x + 233; y += parser_helper(25); return y; }
function optimizer_func_89(x){ let y = x + 31; y += parser_helper(32); return y; }
function optimizer_func_90(x){ let y = x + 800; y += emitter_helper(13); return y; }
function optimizer_func_91(x){ let y = x + 444; y += optimizer_helper(45); return y; }
function optimizer_func_92(x){ let y = x + 740; y += emitter_helper(10); return y; }
function optimizer_func_93(x){ let y = x + 978; y += parser_helper(12); return y; }
function optimizer_func_94(x){ let y = x + 490; y += parser_helper(19); return y; }
function optimizer_func_95(x){ let y = x + 398; y += emitter_helper(29); return y; }
function optimizer_func_96(x){ let y = x + 269; y += optimizer_helper(47); return y; }
function optimizer_func_97(x){ let y = x + 20; y += parser_helper(18); return y; }
function optimizer_func_98(x){ let y = x + 951; y += optimizer_helper(3); return y; }
function optimizer_func_99(x){ let y = x + 437; y += ast_helper(39); return y; }
function optimizer_func_100(x){ let y = x + 796; y += optimizer_helper(17); return y; }
function optimizer_func_101(x){ let y = x + 971; y += ast_helper(1); return y; }
function optimizer_func_102(x){ let y = x + 349; y += ast_helper(4); return y; }
function optimizer_func_103(x){ let y = x + 635; y += lexer_helper(26); return y; }
function optimizer_func_104(x){ let y = x + 571; y += lexer_helper(17); return y; }
function optimizer_func_105(x){ let y = x + 811; y += emitter_helper(39); return y; }
function optimizer_func_106(x){ let y = x + 951; y += parser_helper(0); return y; }
function optimizer_func_107(x){ let y = x + 951; y += emitter_helper(41); return y; }
function optimizer_func_108(x){ let y = x + 521; y += lexer_helper(2); return y; }
function optimizer_func_109(x){ let y = x + 869; y += optimizer_helper(26); return y; }
function optimizer_func_110(x){ let y = x + 809; y += lexer_helper(35); return y; }
function optimizer_func_111(x){ let y = x + 779; y += optimizer_helper(8); return y; }
function optimizer_func_112(x){ let y = x + 457; y += parser_helper(13); return y; }
function optimizer_func_113(x){ let y = x + 837; y += optimizer_helper(46); return y; }
function optimizer_func_114(x){ let y = x + 930; y += parser_helper(26); return y; }
function optimizer_func_115(x){ let y = x + 473; y += emitter_helper(5); return y; }
function optimizer_func_116(x){ let y = x + 32; y += ast_helper(12); return y; }
function optimizer_func_117(x){ let y = x + 595; y += parser_helper(2); return y; }
function optimizer_func_118(x){ let y = x + 590; y += parser_helper(11); return y; }
function optimizer_func_119(x){ let y = x + 3; y += emitter_helper(19); return y; }
function optimizer_func_120(x){ let y = x + 116; y += parser_helper(38); return y; }
function optimizer_func_121(x){ let y = x + 957; y += lexer_helper(1); return y; }
function optimizer_func_122(x){ let y = x + 319; y += optimizer_helper(32); return y; }
function optimizer_func_123(x){ let y = x + 985; y += lexer_helper(3); return y; }
function optimizer_func_124(x){ let y = x + 317; y += lexer_helper(42); return y; }
function optimizer_func_125(x){ let y = x + 302; y += ast_helper(15); return y; }
function optimizer_func_126(x){ let y = x + 0; y += emitter_helper(40); return y; }
function optimizer_func_127(x){ let y = x + 389; y += lexer_helper(9); return y; }
function optimizer_func_128(x){ let y = x + 775; y += emitter_helper(41); return y; }
function optimizer_func_129(x){ let y = x + 565; y += lexer_helper(33); return y; }
function optimizer_func_130(x){ let y = x + 421; y += emitter_helper(48); return y; }
function optimizer_func_131(x){ let y = x + 586; y += lexer_helper(12); return y; }
function optimizer_func_132(x){ let y = x + 84; y += lexer_helper(23); return y; }
function optimizer_func_133(x){ let y = x + 758; y += parser_helper(20); return y; }
function optimizer_func_134(x){ let y = x + 714; y += emitter_helper(11); return y; }
function optimizer_func_135(x){ let y = x + 608; y += optimizer_helper(37); return y; }
function optimizer_func_136(x){ let y = x + 61; y += optimizer_helper(22); return y; }
function optimizer_func_137(x){ let y = x + 538; y += optimizer_helper(15); return y; }
function optimizer_func_138(x){ let y = x + 983; y += parser_helper(43); return y; }
function optimizer_func_139(x){ let y = x + 690; y += lexer_helper(23); return y; }
function optimizer_func_140(x){ let y = x + 731; y += emitter_helper(19); return y; }
function optimizer_func_141(x){ let y = x + 636; y += emitter_helper(45); return y; }
function optimizer_func_142(x){ let y = x + 415; y += lexer_helper(15); return y; }
function optimizer_func_143(x){ let y = x + 36; y += ast_helper(39); return y; }
function optimizer_func_144(x){ let y = x + 837; y += parser_helper(16); return y; }
function optimizer_func_145(x){ let y = x + 541; y += parser_helper(29); return y; }
function optimizer_func_146(x){ let y = x + 850; y += emitter_helper(9); return y; }
function optimizer_func_147(x){ let y = x + 685; y += optimizer_helper(23); return y; }
function optimizer_func_148(x){ let y = x + 758; y += lexer_helper(48); return y; }
function optimizer_func_149(x){ let y = x + 889; y += parser_helper(3); return y; }
function optimizer_func_150(x){ let y = x + 469; y += ast_helper(34); return y; }
function optimizer_func_151(x){ let y = x + 792; y += ast_helper(39); return y; }
function optimizer_func_152(x){ let y = x + 212; y += emitter_helper(11); return y; }
function optimizer_func_153(x){ let y = x + 584; y += lexer_helper(38); return y; }
function optimizer_func_154(x){ let y = x + 565; y += parser_helper(33); return y; }
function optimizer_func_155(x){ let y = x + 123; y += emitter_helper(30); return y; }
function optimizer_func_156(x){ let y = x + 155; y += emitter_helper(31); return y; }
function optimizer_func_157(x){ let y = x + 786; y += lexer_helper(26); return y; }
function optimizer_func_158(x){ let y = x + 802; y += lexer_helper(30); return y; }
function optimizer_func_159(x){ let y = x + 804; y += ast_helper(6); return y; }
function optimizer_func_160(x){ let y = x + 59; y += lexer_helper(1); return y; }
function optimizer_func_161(x){ let y = x + 438; y += lexer_helper(33); return y; }
function optimizer_func_162(x){ let y = x + 193; y += lexer_helper(19); return y; }
function optimizer_func_163(x){ let y = x + 690; y += lexer_helper(26); return y; }
function optimizer_func_164(x){ let y = x + 2; y += lexer_helper(25); return y; }
function optimizer_func_165(x){ let y = x + 5; y += ast_helper(22); return y; }
function optimizer_func_166(x){ let y = x + 303; y += emitter_helper(17); return y; }
function optimizer_func_167(x){ let y = x + 158; y += parser_helper(28); return y; }
function optimizer_func_168(x){ let y = x + 632; y += ast_helper(22); return y; }
function optimizer_func_169(x){ let y = x + 585; y += lexer_helper(43); return y; }
function optimizer_func_170(x){ let y = x + 835; y += optimizer_helper(15); return y; }
function optimizer_func_171(x){ let y = x + 25; y += lexer_helper(2); return y; }
function optimizer_func_172(x){ let y = x + 506; y += ast_helper(16); return y; }
function optimizer_func_173(x){ let y = x + 437; y += emitter_helper(46); return y; }
function optimizer_func_174(x){ let y = x + 649; y += parser_helper(38); return y; }
function optimizer_func_175(x){ let y = x + 456; y += ast_helper(33); return y; }
function optimizer_func_176(x){ let y = x + 961; y += ast_helper(41); return y; }
function optimizer_func_177(x){ let y = x + 838; y += optimizer_helper(42); return y; }
function optimizer_func_178(x){ let y = x + 838; y += optimizer_helper(31); return y; }
function optimizer_func_179(x){ let y = x + 568; y += optimizer_helper(8); return y; }
function optimizer_func_180(x){ let y = x + 781; y += optimizer_helper(1); return y; }
function optimizer_func_181(x){ let y = x + 753; y += emitter_helper(31); return y; }
function optimizer_func_182(x){ let y = x + 838; y += optimizer_helper(43); return y; }
function optimizer_func_183(x){ let y = x + 306; y += ast_helper(27); return y; }
function optimizer_func_184(x){ let y = x + 938; y += emitter_helper(33); return y; }
function optimizer_func_185(x){ let y = x + 209; y += ast_helper(10); return y; }
function optimizer_func_186(x){ let y = x + 12; y += ast_helper(5); return y; }
function optimizer_func_187(x){ let y = x + 741; y += emitter_helper(42); return y; }
function optimizer_func_188(x){ let y = x + 5; y += emitter_helper(38); return y; }
function optimizer_func_189(x){ let y = x + 893; y += emitter_helper(10); return y; }
function optimizer_func_190(x){ let y = x + 579; y += parser_helper(5); return y; }
function optimizer_func_191(x){ let y = x + 477; y += emitter_helper(26); return y; }
function optimizer_func_192(x){ let y = x + 41; y += optimizer_helper(15); return y; }
function optimizer_func_193(x){ let y = x + 311; y += lexer_helper(24); return y; }
function optimizer_func_194(x){ let y = x + 408; y += optimizer_helper(27); return y; }
function optimizer_func_195(x){ let y = x + 57; y += lexer_helper(47); return y; }
function optimizer_func_196(x){ let y = x + 412; y += ast_helper(24); return y; }
function optimizer_func_197(x){ let y = x + 169; y += lexer_helper(36); return y; }
function optimizer_func_198(x){ let y = x + 209; y += emitter_helper(24); return y; }
function optimizer_func_199(x){ let y = x + 842; y += lexer_helper(32); return y; }
function optimizer_func_200(x){ let y = x + 956; y += emitter_helper(30); return y; }
function optimizer_func_201(x){ let y = x + 480; y += parser_helper(19); return y; }
function optimizer_func_202(x){ let y = x + 458; y += emitter_helper(20); return y; }
function optimizer_func_203(x){ let y = x + 157; y += lexer_helper(8); return y; }
function optimizer_func_204(x){ let y = x + 116; y += optimizer_helper(39); return y; }
function optimizer_func_205(x){ let y = x + 217; y += optimizer_helper(7); return y; }
function optimizer_func_206(x){ let y = x + 656; y += emitter_helper(21); return y; }
function optimizer_func_207(x){ let y = x + 741; y += optimizer_helper(19); return y; }
function optimizer_func_208(x){ let y = x + 3; y += emitter_helper(22); return y; }
function optimizer_func_209(x){ let y = x + 936; y += emitter_helper(8); return y; }
function optimizer_func_210(x){ let y = x + 790; y += optimizer_helper(49); return y; }
function optimizer_func_211(x){ let y = x + 622; y += ast_helper(3); return y; }
function optimizer_func_212(x){ let y = x + 174; y += parser_helper(6); return y; }
function optimizer_func_213(x){ let y = x + 263; y += emitter_helper(33); return y; }
function optimizer_func_214(x){ let y = x + 441; y += ast_helper(26); return y; }
function optimizer_func_215(x){ let y = x + 948; y += lexer_helper(1); return y; }
function optimizer_func_216(x){ let y = x + 540; y += lexer_helper(26); return y; }
function optimizer_func_217(x){ let y = x + 845; y += lexer_helper(32); return y; }
function optimizer_func_218(x){ let y = x + 90; y += optimizer_helper(43); return y; }
function optimizer_func_219(x){ let y = x + 282; y += parser_helper(45); return y; }
function optimizer_func_220(x){ let y = x + 964; y += lexer_helper(28); return y; }
function optimizer_func_221(x){ let y = x + 244; y += ast_helper(16); return y; }
function optimizer_func_222(x){ let y = x + 756; y += parser_helper(15); return y; }
function optimizer_func_223(x){ let y = x + 939; y += ast_helper(26); return y; }
function optimizer_func_224(x){ let y = x + 247; y += optimizer_helper(34); return y; }
function optimizer_func_225(x){ let y = x + 485; y += lexer_helper(34); return y; }
function optimizer_func_226(x){ let y = x + 131; y += optimizer_helper(35); return y; }
function optimizer_func_227(x){ let y = x + 217; y += parser_helper(29); return y; }
function optimizer_func_228(x){ let y = x + 184; y += parser_helper(24); return y; }
function optimizer_func_229(x){ let y = x + 882; y += lexer_helper(5); return y; }
function optimizer_func_230(x){ let y = x + 477; y += optimizer_helper(10); return y; }
function optimizer_func_231(x){ let y = x + 3; y += lexer_helper(42); return y; }
function optimizer_func_232(x){ let y = x + 958; y += parser_helper(10); return y; }
function optimizer_func_233(x){ let y = x + 518; y += parser_helper(34); return y; }
function optimizer_func_234(x){ let y = x + 628; y += lexer_helper(38); return y; }
function optimizer_func_235(x){ let y = x + 564; y += emitter_helper(33); return y; }
function optimizer_func_236(x){ let y = x + 206; y += optimizer_helper(32); return y; }
function optimizer_func_237(x){ let y = x + 315; y += lexer_helper(34); return y; }
function optimizer_func_238(x){ let y = x + 949; y += optimizer_helper(32); return y; }
function optimizer_func_239(x){ let y = x + 369; y += optimizer_helper(39); return y; }
function optimizer_func_240(x){ let y = x + 827; y += emitter_helper(13); return y; }
function optimizer_func_241(x){ let y = x + 269; y += ast_helper(40); return y; }
function optimizer_func_242(x){ let y = x + 717; y += parser_helper(5); return y; }
function optimizer_func_243(x){ let y = x + 799; y += emitter_helper(38); return y; }
function optimizer_func_244(x){ let y = x + 653; y += ast_helper(0); return y; }
function optimizer_func_245(x){ let y = x + 961; y += optimizer_helper(25); return y; }
function optimizer_func_246(x){ let y = x + 665; y += emitter_helper(38); return y; }
function optimizer_func_247(x){ let y = x + 466; y += optimizer_helper(29); return y; }
function optimizer_func_248(x){ let y = x + 699; y += parser_helper(44); return y; }
function optimizer_func_249(x){ let y = x + 30; y += lexer_helper(8); return y; }
function optimizer_func_250(x){ let y = x + 805; y += lexer_helper(7); return y; }
function optimizer_func_251(x){ let y = x + 296; y += emitter_helper(32); return y; }
function optimizer_func_252(x){ let y = x + 658; y += emitter_helper(48); return y; }
function optimizer_func_253(x){ let y = x + 859; y += emitter_helper(17); return y; }
function optimizer_func_254(x){ let y = x + 227; y += lexer_helper(22); return y; }
function optimizer_func_255(x){ let y = x + 872; y += parser_helper(10); return y; }
function optimizer_func_256(x){ let y = x + 418; y += emitter_helper(31); return y; }
function optimizer_func_257(x){ let y = x + 547; y += ast_helper(2); return y; }
function optimizer_func_258(x){ let y = x + 499; y += emitter_helper(19); return y; }
function optimizer_func_259(x){ let y = x + 968; y += optimizer_helper(20); return y; }
function optimizer_func_260(x){ let y = x + 701; y += emitter_helper(36); return y; }
function optimizer_func_261(x){ let y = x + 925; y += ast_helper(22); return y; }
function optimizer_func_262(x){ let y = x + 588; y += lexer_helper(2); return y; }
function optimizer_func_263(x){ let y = x + 414; y += emitter_helper(45); return y; }
function optimizer_func_264(x){ let y = x + 620; y += ast_helper(9); return y; }
function optimizer_func_265(x){ let y = x + 850; y += parser_helper(49); return y; }
function optimizer_func_266(x){ let y = x + 653; y += parser_helper(9); return y; }
function optimizer_func_267(x){ let y = x + 541; y += emitter_helper(21); return y; }
function optimizer_func_268(x){ let y = x + 406; y += optimizer_helper(0); return y; }
function optimizer_func_269(x){ let y = x + 642; y += emitter_helper(26); return y; }
function optimizer_func_270(x){ let y = x + 325; y += ast_helper(45); return y; }
function optimizer_func_271(x){ let y = x + 396; y += parser_helper(24); return y; }
function optimizer_func_272(x){ let y = x + 897; y += parser_helper(37); return y; }
function optimizer_func_273(x){ let y = x + 980; y += emitter_helper(47); return y; }
function optimizer_func_274(x){ let y = x + 662; y += lexer_helper(2); return y; }
function optimizer_func_275(x){ let y = x + 636; y += ast_helper(4); return y; }
function optimizer_func_276(x){ let y = x + 875; y += emitter_helper(26); return y; }
function optimizer_func_277(x){ let y = x + 566; y += parser_helper(2); return y; }
function optimizer_func_278(x){ let y = x + 754; y += emitter_helper(1); return y; }
function optimizer_func_279(x){ let y = x + 752; y += emitter_helper(23); return y; }
function optimizer_func_280(x){ let y = x + 777; y += lexer_helper(20); return y; }
function optimizer_func_281(x){ let y = x + 36; y += optimizer_helper(2); return y; }
function optimizer_func_282(x){ let y = x + 369; y += lexer_helper(6); return y; }
function optimizer_func_283(x){ let y = x + 784; y += lexer_helper(36); return y; }
function optimizer_func_284(x){ let y = x + 674; y += lexer_helper(36); return y; }
function optimizer_func_285(x){ let y = x + 309; y += emitter_helper(10); return y; }
function optimizer_func_286(x){ let y = x + 871; y += optimizer_helper(48); return y; }
function optimizer_func_287(x){ let y = x + 338; y += parser_helper(4); return y; }
function optimizer_func_288(x){ let y = x + 493; y += ast_helper(6); return y; }
function optimizer_func_289(x){ let y = x + 414; y += lexer_helper(13); return y; }
function optimizer_func_290(x){ let y = x + 600; y += emitter_helper(16); return y; }
function optimizer_func_291(x){ let y = x + 409; y += ast_helper(42); return y; }
function optimizer_func_292(x){ let y = x + 106; y += lexer_helper(8); return y; }
function optimizer_func_293(x){ let y = x + 618; y += parser_helper(16); return y; }
function optimizer_func_294(x){ let y = x + 608; y += parser_helper(7); return y; }
function optimizer_func_295(x){ let y = x + 944; y += lexer_helper(28); return y; }
function optimizer_func_296(x){ let y = x + 756; y += emitter_helper(6); return y; }
function optimizer_func_297(x){ let y = x + 282; y += emitter_helper(25); return y; }
function optimizer_func_298(x){ let y = x + 843; y += parser_helper(23); return y; }
function optimizer_func_299(x){ let y = x + 119; y += optimizer_helper(1); return y; }
function optimizer_func_300(x){ let y = x + 765; y += lexer_helper(32); return y; }
function optimizer_func_301(x){ let y = x + 172; y += emitter_helper(21); return y; }
function optimizer_func_302(x){ let y = x + 878; y += parser_helper(5); return y; }
function optimizer_func_303(x){ let y = x + 745; y += lexer_helper(25); return y; }
function optimizer_func_304(x){ let y = x + 977; y += optimizer_helper(14); return y; }
function optimizer_func_305(x){ let y = x + 417; y += emitter_helper(30); return y; }
function optimizer_func_306(x){ let y = x + 450; y += parser_helper(2); return y; }
function optimizer_func_307(x){ let y = x + 262; y += ast_helper(41); return y; }
function optimizer_func_308(x){ let y = x + 322; y += parser_helper(29); return y; }
function optimizer_func_309(x){ let y = x + 177; y += emitter_helper(26); return y; }
function optimizer_func_310(x){ let y = x + 825; y += optimizer_helper(9); return y; }
function optimizer_func_311(x){ let y = x + 918; y += emitter_helper(48); return y; }
function optimizer_func_312(x){ let y = x + 685; y += lexer_helper(10); return y; }
function optimizer_func_313(x){ let y = x + 131; y += ast_helper(35); return y; }
function optimizer_func_314(x){ let y = x + 905; y += optimizer_helper(49); return y; }
function optimizer_func_315(x){ let y = x + 477; y += optimizer_helper(28); return y; }
function optimizer_func_316(x){ let y = x + 906; y += optimizer_helper(41); return y; }
function optimizer_func_317(x){ let y = x + 88; y += lexer_helper(30); return y; }
function optimizer_func_318(x){ let y = x + 835; y += optimizer_helper(31); return y; }
function optimizer_func_319(x){ let y = x + 372; y += optimizer_helper(35); return y; }
function optimizer_func_320(x){ let y = x + 216; y += emitter_helper(31); return y; }
function optimizer_func_321(x){ let y = x + 926; y += lexer_helper(17); return y; }
function optimizer_func_322(x){ let y = x + 211; y += ast_helper(49); return y; }
function optimizer_func_323(x){ let y = x + 761; y += lexer_helper(42); return y; }
function optimizer_func_324(x){ let y = x + 334; y += optimizer_helper(18); return y; }
function optimizer_func_325(x){ let y = x + 841; y += emitter_helper(48); return y; }
function optimizer_func_326(x){ let y = x + 705; y += ast_helper(41); return y; }
function optimizer_func_327(x){ let y = x + 685; y += lexer_helper(43); return y; }
function optimizer_func_328(x){ let y = x + 286; y += ast_helper(11); return y; }
function optimizer_func_329(x){ let y = x + 220; y += ast_helper(17); return y; }
function optimizer_func_330(x){ let y = x + 463; y += emitter_helper(20); return y; }
function optimizer_func_331(x){ let y = x + 818; y += optimizer_helper(41); return y; }
function optimizer_func_332(x){ let y = x + 450; y += lexer_helper(2); return y; }
function optimizer_func_333(x){ let y = x + 156; y += lexer_helper(6); return y; }
function optimizer_func_334(x){ let y = x + 158; y += parser_helper(29); return y; }
function optimizer_func_335(x){ let y = x + 40; y += emitter_helper(31); return y; }
function optimizer_func_336(x){ let y = x + 307; y += lexer_helper(10); return y; }
function optimizer_func_337(x){ let y = x + 517; y += optimizer_helper(10); return y; }
function optimizer_func_338(x){ let y = x + 291; y += optimizer_helper(19); return y; }
function optimizer_func_339(x){ let y = x + 2; y += optimizer_helper(46); return y; }
function optimizer_func_340(x){ let y = x + 922; y += ast_helper(28); return y; }
function optimizer_func_341(x){ let y = x + 645; y += emitter_helper(21); return y; }
function optimizer_func_342(x){ let y = x + 842; y += lexer_helper(3); return y; }
function optimizer_func_343(x){ let y = x + 386; y += lexer_helper(29); return y; }
function optimizer_func_344(x){ let y = x + 799; y += ast_helper(2); return y; }
function optimizer_func_345(x){ let y = x + 484; y += ast_helper(13); return y; }
function optimizer_func_346(x){ let y = x + 980; y += lexer_helper(9); return y; }
function optimizer_func_347(x){ let y = x + 666; y += emitter_helper(44); return y; }
function optimizer_func_348(x){ let y = x + 502; y += ast_helper(29); return y; }
function optimizer_func_349(x){ let y = x + 633; y += parser_helper(17); return y; }
function optimizer_func_350(x){ let y = x + 140; y += lexer_helper(17); return y; }
function optimizer_func_351(x){ let y = x + 774; y += optimizer_helper(5); return y; }
function optimizer_func_352(x){ let y = x + 551; y += lexer_helper(11); return y; }
function optimizer_func_353(x){ let y = x + 357; y += emitter_helper(8); return y; }
function optimizer_func_354(x){ let y = x + 925; y += optimizer_helper(25); return y; }
function optimizer_func_355(x){ let y = x + 270; y += parser_helper(20); return y; }
function optimizer_func_356(x){ let y = x + 416; y += lexer_helper(9); return y; }
function optimizer_func_357(x){ let y = x + 703; y += ast_helper(39); return y; }
function optimizer_func_358(x){ let y = x + 223; y += optimizer_helper(29); return y; }
function optimizer_func_359(x){ let y = x + 653; y += emitter_helper(5); return y; }
function optimizer_func_360(x){ let y = x + 928; y += optimizer_helper(28); return y; }
function optimizer_func_361(x){ let y = x + 625; y += lexer_helper(31); return y; }
function optimizer_func_362(x){ let y = x + 900; y += parser_helper(16); return y; }
function optimizer_func_363(x){ let y = x + 72; y += parser_helper(43); return y; }
function optimizer_func_364(x){ let y = x + 653; y += emitter_helper(34); return y; }
function optimizer_func_365(x){ let y = x + 698; y += lexer_helper(42); return y; }
function optimizer_func_366(x){ let y = x + 215; y += ast_helper(8); return y; }
function optimizer_func_367(x){ let y = x + 414; y += optimizer_helper(23); return y; }
function optimizer_func_368(x){ let y = x + 679; y += ast_helper(31); return y; }
function optimizer_func_369(x){ let y = x + 448; y += parser_helper(1); return y; }
function optimizer_func_370(x){ let y = x + 958; y += emitter_helper(30); return y; }
function optimizer_func_371(x){ let y = x + 113; y += parser_helper(30); return y; }
function optimizer_func_372(x){ let y = x + 317; y += emitter_helper(31); return y; }
function optimizer_func_373(x){ let y = x + 291; y += parser_helper(42); return y; }
function optimizer_func_374(x){ let y = x + 452; y += optimizer_helper(44); return y; }
function optimizer_func_375(x){ let y = x + 756; y += emitter_helper(17); return y; }
function optimizer_func_376(x){ let y = x + 98; y += optimizer_helper(8); return y; }
function optimizer_func_377(x){ let y = x + 682; y += ast_helper(34); return y; }
function optimizer_func_378(x){ let y = x + 475; y += emitter_helper(0); return y; }
function optimizer_func_379(x){ let y = x + 586; y += optimizer_helper(16); return y; }
function optimizer_func_380(x){ let y = x + 85; y += lexer_helper(16); return y; }
function optimizer_func_381(x){ let y = x + 20; y += emitter_helper(36); return y; }
function optimizer_func_382(x){ let y = x + 67; y += emitter_helper(36); return y; }
function optimizer_func_383(x){ let y = x + 738; y += optimizer_helper(16); return y; }
function optimizer_func_384(x){ let y = x + 120; y += optimizer_helper(42); return y; }
function optimizer_func_385(x){ let y = x + 969; y += parser_helper(41); return y; }
function optimizer_func_386(x){ let y = x + 908; y += parser_helper(2); return y; }
function optimizer_func_387(x){ let y = x + 114; y += ast_helper(30); return y; }
function optimizer_func_388(x){ let y = x + 455; y += parser_helper(29); return y; }
function optimizer_func_389(x){ let y = x + 516; y += ast_helper(32); return y; }
function optimizer_func_390(x){ let y = x + 250; y += lexer_helper(5); return y; }
function optimizer_func_391(x){ let y = x + 846; y += ast_helper(21); return y; }
function optimizer_func_392(x){ let y = x + 816; y += emitter_helper(2); return y; }
function optimizer_func_393(x){ let y = x + 383; y += lexer_helper(11); return y; }
function optimizer_func_394(x){ let y = x + 792; y += lexer_helper(37); return y; }
function optimizer_func_395(x){ let y = x + 900; y += emitter_helper(25); return y; }
function optimizer_func_396(x){ let y = x + 51; y += ast_helper(12); return y; }
function optimizer_func_397(x){ let y = x + 108; y += parser_helper(34); return y; }
function optimizer_func_398(x){ let y = x + 236; y += optimizer_helper(16); return y; }
function optimizer_func_399(x){ let y = x + 705; y += lexer_helper(0); return y; }
function optimizer_func_400(x){ let y = x + 634; y += emitter_helper(38); return y; }
function optimizer_func_401(x){ let y = x + 892; y += ast_helper(49); return y; }
function optimizer_func_402(x){ let y = x + 935; y += ast_helper(45); return y; }
function optimizer_func_403(x){ let y = x + 364; y += ast_helper(29); return y; }
function optimizer_func_404(x){ let y = x + 448; y += parser_helper(14); return y; }
function optimizer_func_405(x){ let y = x + 844; y += lexer_helper(17); return y; }
function optimizer_func_406(x){ let y = x + 907; y += lexer_helper(46); return y; }
function optimizer_func_407(x){ let y = x + 921; y += parser_helper(7); return y; }
function optimizer_func_408(x){ let y = x + 615; y += ast_helper(23); return y; }
function optimizer_func_409(x){ let y = x + 428; y += parser_helper(2); return y; }
function optimizer_func_410(x){ let y = x + 326; y += optimizer_helper(22); return y; }
function optimizer_func_411(x){ let y = x + 52; y += optimizer_helper(34); return y; }
function optimizer_func_412(x){ let y = x + 967; y += lexer_helper(15); return y; }
function optimizer_func_413(x){ let y = x + 877; y += ast_helper(45); return y; }
function optimizer_func_414(x){ let y = x + 163; y += ast_helper(7); return y; }
function optimizer_func_415(x){ let y = x + 968; y += emitter_helper(35); return y; }
function optimizer_func_416(x){ let y = x + 91; y += emitter_helper(44); return y; }
function optimizer_func_417(x){ let y = x + 203; y += parser_helper(7); return y; }
function optimizer_func_418(x){ let y = x + 968; y += parser_helper(23); return y; }
function optimizer_func_419(x){ let y = x + 951; y += lexer_helper(37); return y; }
function optimizer_func_420(x){ let y = x + 489; y += ast_helper(4); return y; }
function optimizer_func_421(x){ let y = x + 322; y += emitter_helper(40); return y; }
function optimizer_func_422(x){ let y = x + 678; y += parser_helper(48); return y; }
function optimizer_func_423(x){ let y = x + 909; y += emitter_helper(48); return y; }
function optimizer_func_424(x){ let y = x + 309; y += optimizer_helper(2); return y; }
function optimizer_func_425(x){ let y = x + 270; y += optimizer_helper(24); return y; }
function optimizer_func_426(x){ let y = x + 212; y += parser_helper(21); return y; }
function optimizer_func_427(x){ let y = x + 475; y += lexer_helper(20); return y; }
function optimizer_func_428(x){ let y = x + 742; y += ast_helper(7); return y; }
function optimizer_func_429(x){ let y = x + 279; y += parser_helper(32); return y; }
function optimizer_func_430(x){ let y = x + 538; y += lexer_helper(6); return y; }
function optimizer_func_431(x){ let y = x + 245; y += ast_helper(25); return y; }
function optimizer_func_432(x){ let y = x + 30; y += lexer_helper(32); return y; }
function optimizer_func_433(x){ let y = x + 436; y += ast_helper(37); return y; }
function optimizer_func_434(x){ let y = x + 408; y += ast_helper(39); return y; }
function optimizer_func_435(x){ let y = x + 584; y += emitter_helper(11); return y; }
function optimizer_func_436(x){ let y = x + 907; y += lexer_helper(6); return y; }
function optimizer_func_437(x){ let y = x + 588; y += optimizer_helper(2); return y; }
function optimizer_func_438(x){ let y = x + 526; y += parser_helper(7); return y; }
function optimizer_func_439(x){ let y = x + 537; y += lexer_helper(33); return y; }
function optimizer_func_440(x){ let y = x + 277; y += emitter_helper(22); return y; }
function optimizer_func_441(x){ let y = x + 400; y += ast_helper(29); return y; }
function optimizer_func_442(x){ let y = x + 46; y += optimizer_helper(34); return y; }
function optimizer_func_443(x){ let y = x + 515; y += parser_helper(36); return y; }
function optimizer_func_444(x){ let y = x + 453; y += optimizer_helper(15); return y; }
function optimizer_func_445(x){ let y = x + 240; y += optimizer_helper(13); return y; }
function optimizer_func_446(x){ let y = x + 119; y += lexer_helper(12); return y; }
function optimizer_func_447(x){ let y = x + 509; y += optimizer_helper(10); return y; }
function optimizer_func_448(x){ let y = x + 603; y += lexer_helper(19); return y; }
function optimizer_func_449(x){ let y = x + 243; y += lexer_helper(25); return y; }
function optimizer_func_450(x){ let y = x + 553; y += lexer_helper(31); return y; }
function optimizer_func_451(x){ let y = x + 930; y += lexer_helper(9); return y; }
function optimizer_func_452(x){ let y = x + 614; y += parser_helper(6); return y; }
function optimizer_func_453(x){ let y = x + 797; y += lexer_helper(43); return y; }
function optimizer_func_454(x){ let y = x + 366; y += parser_helper(13); return y; }
function optimizer_func_455(x){ let y = x + 929; y += lexer_helper(9); return y; }
function optimizer_func_456(x){ let y = x + 628; y += parser_helper(25); return y; }
function optimizer_func_457(x){ let y = x + 758; y += emitter_helper(1); return y; }
function optimizer_func_458(x){ let y = x + 125; y += optimizer_helper(21); return y; }
function optimizer_func_459(x){ let y = x + 457; y += parser_helper(6); return y; }
function optimizer_func_460(x){ let y = x + 95; y += optimizer_helper(34); return y; }
function optimizer_func_461(x){ let y = x + 810; y += parser_helper(30); return y; }
function optimizer_func_462(x){ let y = x + 981; y += ast_helper(31); return y; }
function optimizer_func_463(x){ let y = x + 581; y += parser_helper(3); return y; }
function optimizer_func_464(x){ let y = x + 594; y += optimizer_helper(48); return y; }
function optimizer_func_465(x){ let y = x + 878; y += optimizer_helper(32); return y; }
function optimizer_func_466(x){ let y = x + 534; y += optimizer_helper(28); return y; }
function optimizer_func_467(x){ let y = x + 666; y += optimizer_helper(18); return y; }
function optimizer_func_468(x){ let y = x + 880; y += emitter_helper(25); return y; }
function optimizer_func_469(x){ let y = x + 572; y += ast_helper(41); return y; }
function optimizer_func_470(x){ let y = x + 663; y += ast_helper(4); return y; }
function optimizer_func_471(x){ let y = x + 391; y += parser_helper(21); return y; }
function optimizer_func_472(x){ let y = x + 796; y += parser_helper(19); return y; }
function optimizer_func_473(x){ let y = x + 165; y += parser_helper(35); return y; }
function optimizer_func_474(x){ let y = x + 959; y += emitter_helper(3); return y; }
function optimizer_func_475(x){ let y = x + 471; y += optimizer_helper(41); return y; }
function optimizer_func_476(x){ let y = x + 832; y += ast_helper(25); return y; }
function optimizer_func_477(x){ let y = x + 957; y += emitter_helper(7); return y; }
function optimizer_func_478(x){ let y = x + 549; y += optimizer_helper(30); return y; }
function optimizer_func_479(x){ let y = x + 230; y += lexer_helper(20); return y; }
function optimizer_func_480(x){ let y = x + 372; y += parser_helper(9); return y; }
function optimizer_func_481(x){ let y = x + 672; y += lexer_helper(11); return y; }
function optimizer_func_482(x){ let y = x + 163; y += emitter_helper(1); return y; }
function optimizer_func_483(x){ let y = x + 587; y += ast_helper(25); return y; }
function optimizer_func_484(x){ let y = x + 36; y += optimizer_helper(16); return y; }
function optimizer_func_485(x){ let y = x + 705; y += optimizer_helper(18); return y; }
function optimizer_func_486(x){ let y = x + 412; y += lexer_helper(3); return y; }
function optimizer_func_487(x){ let y = x + 70; y += ast_helper(23); return y; }
function optimizer_func_488(x){ let y = x + 545; y += emitter_helper(43); return y; }
function optimizer_func_489(x){ let y = x + 719; y += optimizer_helper(0); return y; }
function optimizer_func_490(x){ let y = x + 239; y += lexer_helper(10); return y; }
function optimizer_func_491(x){ let y = x + 280; y += emitter_helper(29); return y; }
function optimizer_func_492(x){ let y = x + 463; y += lexer_helper(30); return y; }
function optimizer_func_493(x){ let y = x + 104; y += lexer_helper(26); return y; }
function optimizer_func_494(x){ let y = x + 4; y += ast_helper(46); return y; }
function optimizer_func_495(x){ let y = x + 900; y += ast_helper(8); return y; }
function optimizer_func_496(x){ let y = x + 238; y += lexer_helper(15); return y; }
function optimizer_func_497(x){ let y = x + 712; y += optimizer_helper(22); return y; }
function optimizer_func_498(x){ let y = x + 186; y += parser_helper(8); return y; }
function optimizer_func_499(x){ let y = x + 710; y += ast_helper(33); return y; }
function lexer_helper(x){ return x*14; }
function parser_helper(x){ return x*12; }
function ast_helper(x){ return x*9; }
function optimizer_helper(x){ return x*18; }
function emitter_helper(x){ return x*1; }
module.exports = { lexer_init, parser_init, ast_init, optimizer_init, emitter_init };
