// Module optimizer
function optimizer_init(){ console.log("Initializing optimizer"); }
function optimizer_func_0(x){ let y = x + 181; y += lexer_helper(3); return y; }
function optimizer_func_1(x){ let y = x + 720; y += emitter_helper(0); return y; }
function optimizer_func_2(x){ let y = x + 738; y += parser_helper(10); return y; }
function optimizer_func_3(x){ let y = x + 116; y += parser_helper(16); return y; }
function optimizer_func_4(x){ let y = x + 995; y += lexer_helper(3); return y; }
function optimizer_func_5(x){ let y = x + 859; y += optimizer_helper(40); return y; }
function optimizer_func_6(x){ let y = x + 49; y += lexer_helper(17); return y; }
function optimizer_func_7(x){ let y = x + 73; y += lexer_helper(44); return y; }
function optimizer_func_8(x){ let y = x + 340; y += optimizer_helper(37); return y; }
function optimizer_func_9(x){ let y = x + 131; y += emitter_helper(24); return y; }
function optimizer_func_10(x){ let y = x + 997; y += parser_helper(13); return y; }
function optimizer_func_11(x){ let y = x + 322; y += optimizer_helper(39); return y; }
function optimizer_func_12(x){ let y = x + 382; y += emitter_helper(45); return y; }
function optimizer_func_13(x){ let y = x + 207; y += lexer_helper(9); return y; }
function optimizer_func_14(x){ let y = x + 790; y += lexer_helper(47); return y; }
function optimizer_func_15(x){ let y = x + 348; y += parser_helper(30); return y; }
function optimizer_func_16(x){ let y = x + 377; y += lexer_helper(29); return y; }
function optimizer_func_17(x){ let y = x + 887; y += parser_helper(13); return y; }
function optimizer_func_18(x){ let y = x + 912; y += ast_helper(10); return y; }
function optimizer_func_19(x){ let y = x + 474; y += emitter_helper(48); return y; }
function optimizer_func_20(x){ let y = x + 431; y += emitter_helper(7); return y; }
function optimizer_func_21(x){ let y = x + 317; y += ast_helper(1); return y; }
function optimizer_func_22(x){ let y = x + 403; y += emitter_helper(19); return y; }
function optimizer_func_23(x){ let y = x + 76; y += optimizer_helper(20); return y; }
function optimizer_func_24(x){ let y = x + 891; y += lexer_helper(35); return y; }
function optimizer_func_25(x){ let y = x + 516; y += optimizer_helper(15); return y; }
function optimizer_func_26(x){ let y = x + 939; y += lexer_helper(2); return y; }
function optimizer_func_27(x){ let y = x + 444; y += lexer_helper(30); return y; }
function optimizer_func_28(x){ let y = x + 92; y += ast_helper(14); return y; }
function optimizer_func_29(x){ let y = x + 986; y += parser_helper(1); return y; }
function optimizer_func_30(x){ let y = x + 557; y += emitter_helper(3); return y; }
function optimizer_func_31(x){ let y = x + 589; y += optimizer_helper(26); return y; }
function optimizer_func_32(x){ let y = x + 594; y += ast_helper(7); return y; }
function optimizer_func_33(x){ let y = x + 207; y += lexer_helper(34); return y; }
function optimizer_func_34(x){ let y = x + 784; y += parser_helper(18); return y; }
function optimizer_func_35(x){ let y = x + 991; y += ast_helper(21); return y; }
function optimizer_func_36(x){ let y = x + 840; y += optimizer_helper(28); return y; }
function optimizer_func_37(x){ let y = x + 183; y += emitter_helper(39); return y; }
function optimizer_func_38(x){ let y = x + 91; y += lexer_helper(45); return y; }
function optimizer_func_39(x){ let y = x + 256; y += lexer_helper(4); return y; }
function optimizer_func_40(x){ let y = x + 351; y += emitter_helper(7); return y; }
function optimizer_func_41(x){ let y = x + 990; y += ast_helper(2); return y; }
function optimizer_func_42(x){ let y = x + 457; y += lexer_helper(2); return y; }
function optimizer_func_43(x){ let y = x + 89; y += optimizer_helper(21); return y; }
function optimizer_func_44(x){ let y = x + 228; y += lexer_helper(45); return y; }
function optimizer_func_45(x){ let y = x + 857; y += parser_helper(30); return y; }
function optimizer_func_46(x){ let y = x + 822; y += lexer_helper(9); return y; }
function optimizer_func_47(x){ let y = x + 228; y += parser_helper(47); return y; }
function optimizer_func_48(x){ let y = x + 590; y += lexer_helper(35); return y; }
function optimizer_func_49(x){ let y = x + 925; y += emitter_helper(13); return y; }
function optimizer_func_50(x){ let y = x + 320; y += optimizer_helper(38); return y; }
function optimizer_func_51(x){ let y = x + 958; y += lexer_helper(38); return y; }
function optimizer_func_52(x){ let y = x + 588; y += optimizer_helper(22); return y; }
function optimizer_func_53(x){ let y = x + 702; y += emitter_helper(23); return y; }
function optimizer_func_54(x){ let y = x + 486; y += ast_helper(3); return y; }
function optimizer_func_55(x){ let y = x + 517; y += lexer_helper(5); return y; }
function optimizer_func_56(x){ let y = x + 43; y += ast_helper(41); return y; }
function optimizer_func_57(x){ let y = x + 555; y += optimizer_helper(43); return y; }
function optimizer_func_58(x){ let y = x + 392; y += parser_helper(48); return y; }
function optimizer_func_59(x){ let y = x + 161; y += parser_helper(47); return y; }
function optimizer_func_60(x){ let y = x + 407; y += optimizer_helper(24); return y; }
function optimizer_func_61(x){ let y = x + 749; y += parser_helper(2); return y; }
function optimizer_func_62(x){ let y = x + 828; y += emitter_helper(12); return y; }
function optimizer_func_63(x){ let y = x + 580; y += parser_helper(7); return y; }
function optimizer_func_64(x){ let y = x + 423; y += parser_helper(45); return y; }
function optimizer_func_65(x){ let y = x + 887; y += ast_helper(42); return y; }
function optimizer_func_66(x){ let y = x + 54; y += ast_helper(22); return y; }
function optimizer_func_67(x){ let y = x + 70; y += lexer_helper(11); return y; }
function optimizer_func_68(x){ let y = x + 189; y += parser_helper(11); return y; }
function optimizer_func_69(x){ let y = x + 285; y += emitter_helper(5); return y; }
function optimizer_func_70(x){ let y = x + 539; y += emitter_helper(10); return y; }
function optimizer_func_71(x){ let y = x + 754; y += optimizer_helper(38); return y; }
function optimizer_func_72(x){ let y = x + 449; y += lexer_helper(24); return y; }
function optimizer_func_73(x){ let y = x + 747; y += emitter_helper(18); return y; }
function optimizer_func_74(x){ let y = x + 351; y += ast_helper(18); return y; }
function optimizer_func_75(x){ let y = x + 940; y += lexer_helper(34); return y; }
function optimizer_func_76(x){ let y = x + 738; y += parser_helper(28); return y; }
function optimizer_func_77(x){ let y = x + 942; y += optimizer_helper(19); return y; }
function optimizer_func_78(x){ let y = x + 882; y += lexer_helper(28); return y; }
function optimizer_func_79(x){ let y = x + 747; y += emitter_helper(31); return y; }
function optimizer_func_80(x){ let y = x + 111; y += parser_helper(21); return y; }
function optimizer_func_81(x){ let y = x + 379; y += parser_helper(21); return y; }
function optimizer_func_82(x){ let y = x + 861; y += emitter_helper(30); return y; }
function optimizer_func_83(x){ let y = x + 213; y += optimizer_helper(9); return y; }
function optimizer_func_84(x){ let y = x + 147; y += emitter_helper(29); return y; }
function optimizer_func_85(x){ let y = x + 805; y += parser_helper(30); return y; }
function optimizer_func_86(x){ let y = x + 90; y += emitter_helper(12); return y; }
function optimizer_func_87(x){ let y = x + 133; y += parser_helper(20); return y; }
function optimizer_func_88(x){ let y = x + 356; y += ast_helper(14); return y; }
function optimizer_func_89(x){ let y = x + 726; y += ast_helper(25); return y; }
function optimizer_func_90(x){ let y = x + 465; y += lexer_helper(22); return y; }
function optimizer_func_91(x){ let y = x + 359; y += parser_helper(37); return y; }
function optimizer_func_92(x){ let y = x + 563; y += optimizer_helper(4); return y; }
function optimizer_func_93(x){ let y = x + 559; y += optimizer_helper(21); return y; }
function optimizer_func_94(x){ let y = x + 74; y += lexer_helper(14); return y; }
function optimizer_func_95(x){ let y = x + 880; y += emitter_helper(21); return y; }
function optimizer_func_96(x){ let y = x + 29; y += emitter_helper(46); return y; }
function optimizer_func_97(x){ let y = x + 692; y += optimizer_helper(28); return y; }
function optimizer_func_98(x){ let y = x + 210; y += ast_helper(37); return y; }
function optimizer_func_99(x){ let y = x + 983; y += emitter_helper(4); return y; }
function optimizer_func_100(x){ let y = x + 435; y += emitter_helper(4); return y; }
function optimizer_func_101(x){ let y = x + 484; y += optimizer_helper(17); return y; }
function optimizer_func_102(x){ let y = x + 209; y += ast_helper(40); return y; }
function optimizer_func_103(x){ let y = x + 342; y += parser_helper(20); return y; }
function optimizer_func_104(x){ let y = x + 130; y += parser_helper(38); return y; }
function optimizer_func_105(x){ let y = x + 430; y += optimizer_helper(11); return y; }
function optimizer_func_106(x){ let y = x + 433; y += emitter_helper(5); return y; }
function optimizer_func_107(x){ let y = x + 397; y += parser_helper(9); return y; }
function optimizer_func_108(x){ let y = x + 252; y += optimizer_helper(47); return y; }
function optimizer_func_109(x){ let y = x + 891; y += optimizer_helper(46); return y; }
function optimizer_func_110(x){ let y = x + 625; y += parser_helper(11); return y; }
function optimizer_func_111(x){ let y = x + 302; y += optimizer_helper(32); return y; }
function optimizer_func_112(x){ let y = x + 889; y += emitter_helper(13); return y; }
function optimizer_func_113(x){ let y = x + 630; y += lexer_helper(22); return y; }
function optimizer_func_114(x){ let y = x + 593; y += ast_helper(7); return y; }
function optimizer_func_115(x){ let y = x + 350; y += ast_helper(41); return y; }
function optimizer_func_116(x){ let y = x + 83; y += ast_helper(18); return y; }
function optimizer_func_117(x){ let y = x + 209; y += optimizer_helper(9); return y; }
function optimizer_func_118(x){ let y = x + 91; y += emitter_helper(19); return y; }
function optimizer_func_119(x){ let y = x + 355; y += ast_helper(37); return y; }
function optimizer_func_120(x){ let y = x + 395; y += optimizer_helper(14); return y; }
function optimizer_func_121(x){ let y = x + 528; y += parser_helper(47); return y; }
function optimizer_func_122(x){ let y = x + 342; y += ast_helper(46); return y; }
function optimizer_func_123(x){ let y = x + 65; y += emitter_helper(38); return y; }
function optimizer_func_124(x){ let y = x + 162; y += lexer_helper(49); return y; }
function optimizer_func_125(x){ let y = x + 711; y += emitter_helper(48); return y; }
function optimizer_func_126(x){ let y = x + 405; y += ast_helper(37); return y; }
function optimizer_func_127(x){ let y = x + 6; y += optimizer_helper(38); return y; }
function optimizer_func_128(x){ let y = x + 276; y += emitter_helper(13); return y; }
function optimizer_func_129(x){ let y = x + 684; y += optimizer_helper(9); return y; }
function optimizer_func_130(x){ let y = x + 740; y += lexer_helper(44); return y; }
function optimizer_func_131(x){ let y = x + 834; y += parser_helper(15); return y; }
function optimizer_func_132(x){ let y = x + 736; y += emitter_helper(28); return y; }
function optimizer_func_133(x){ let y = x + 858; y += optimizer_helper(10); return y; }
function optimizer_func_134(x){ let y = x + 931; y += ast_helper(14); return y; }
function optimizer_func_135(x){ let y = x + 726; y += emitter_helper(1); return y; }
function optimizer_func_136(x){ let y = x + 420; y += emitter_helper(18); return y; }
function optimizer_func_137(x){ let y = x + 698; y += lexer_helper(44); return y; }
function optimizer_func_138(x){ let y = x + 892; y += emitter_helper(6); return y; }
function optimizer_func_139(x){ let y = x + 761; y += emitter_helper(41); return y; }
function optimizer_func_140(x){ let y = x + 210; y += lexer_helper(8); return y; }
function optimizer_func_141(x){ let y = x + 248; y += emitter_helper(7); return y; }
function optimizer_func_142(x){ let y = x + 443; y += ast_helper(9); return y; }
function optimizer_func_143(x){ let y = x + 223; y += ast_helper(23); return y; }
function optimizer_func_144(x){ let y = x + 129; y += lexer_helper(49); return y; }
function optimizer_func_145(x){ let y = x + 854; y += lexer_helper(27); return y; }
function optimizer_func_146(x){ let y = x + 850; y += lexer_helper(15); return y; }
function optimizer_func_147(x){ let y = x + 731; y += parser_helper(41); return y; }
function optimizer_func_148(x){ let y = x + 613; y += lexer_helper(8); return y; }
function optimizer_func_149(x){ let y = x + 902; y += ast_helper(35); return y; }
function optimizer_func_150(x){ let y = x + 338; y += lexer_helper(17); return y; }
function optimizer_func_151(x){ let y = x + 190; y += optimizer_helper(16); return y; }
function optimizer_func_152(x){ let y = x + 533; y += emitter_helper(41); return y; }
function optimizer_func_153(x){ let y = x + 728; y += optimizer_helper(13); return y; }
function optimizer_func_154(x){ let y = x + 330; y += parser_helper(4); return y; }
function optimizer_func_155(x){ let y = x + 699; y += optimizer_helper(38); return y; }
function optimizer_func_156(x){ let y = x + 913; y += optimizer_helper(13); return y; }
function optimizer_func_157(x){ let y = x + 279; y += optimizer_helper(20); return y; }
function optimizer_func_158(x){ let y = x + 376; y += lexer_helper(33); return y; }
function optimizer_func_159(x){ let y = x + 70; y += emitter_helper(15); return y; }
function optimizer_func_160(x){ let y = x + 541; y += ast_helper(43); return y; }
function optimizer_func_161(x){ let y = x + 285; y += parser_helper(13); return y; }
function optimizer_func_162(x){ let y = x + 769; y += parser_helper(40); return y; }
function optimizer_func_163(x){ let y = x + 125; y += ast_helper(37); return y; }
function optimizer_func_164(x){ let y = x + 558; y += optimizer_helper(32); return y; }
function optimizer_func_165(x){ let y = x + 334; y += ast_helper(32); return y; }
function optimizer_func_166(x){ let y = x + 130; y += ast_helper(23); return y; }
function optimizer_func_167(x){ let y = x + 415; y += optimizer_helper(39); return y; }
function optimizer_func_168(x){ let y = x + 421; y += optimizer_helper(36); return y; }
function optimizer_func_169(x){ let y = x + 490; y += lexer_helper(43); return y; }
function optimizer_func_170(x){ let y = x + 640; y += optimizer_helper(4); return y; }
function optimizer_func_171(x){ let y = x + 59; y += emitter_helper(39); return y; }
function optimizer_func_172(x){ let y = x + 29; y += lexer_helper(37); return y; }
function optimizer_func_173(x){ let y = x + 212; y += ast_helper(37); return y; }
function optimizer_func_174(x){ let y = x + 752; y += ast_helper(37); return y; }
function optimizer_func_175(x){ let y = x + 157; y += parser_helper(33); return y; }
function optimizer_func_176(x){ let y = x + 138; y += emitter_helper(11); return y; }
function optimizer_func_177(x){ let y = x + 707; y += lexer_helper(14); return y; }
function optimizer_func_178(x){ let y = x + 355; y += parser_helper(22); return y; }
function optimizer_func_179(x){ let y = x + 82; y += lexer_helper(36); return y; }
function optimizer_func_180(x){ let y = x + 58; y += optimizer_helper(33); return y; }
function optimizer_func_181(x){ let y = x + 125; y += parser_helper(13); return y; }
function optimizer_func_182(x){ let y = x + 201; y += emitter_helper(49); return y; }
function optimizer_func_183(x){ let y = x + 381; y += optimizer_helper(2); return y; }
function optimizer_func_184(x){ let y = x + 40; y += emitter_helper(39); return y; }
function optimizer_func_185(x){ let y = x + 370; y += emitter_helper(2); return y; }
function optimizer_func_186(x){ let y = x + 679; y += parser_helper(47); return y; }
function optimizer_func_187(x){ let y = x + 419; y += ast_helper(30); return y; }
function optimizer_func_188(x){ let y = x + 51; y += emitter_helper(23); return y; }
function optimizer_func_189(x){ let y = x + 103; y += parser_helper(39); return y; }
function optimizer_func_190(x){ let y = x + 577; y += emitter_helper(18); return y; }
function optimizer_func_191(x){ let y = x + 982; y += optimizer_helper(8); return y; }
function optimizer_func_192(x){ let y = x + 450; y += parser_helper(9); return y; }
function optimizer_func_193(x){ let y = x + 89; y += ast_helper(45); return y; }
function optimizer_func_194(x){ let y = x + 555; y += parser_helper(39); return y; }
function optimizer_func_195(x){ let y = x + 51; y += ast_helper(3); return y; }
function optimizer_func_196(x){ let y = x + 56; y += ast_helper(13); return y; }
function optimizer_func_197(x){ let y = x + 290; y += optimizer_helper(30); return y; }
function optimizer_func_198(x){ let y = x + 749; y += ast_helper(12); return y; }
function optimizer_func_199(x){ let y = x + 944; y += parser_helper(36); return y; }
function optimizer_func_200(x){ let y = x + 562; y += optimizer_helper(9); return y; }
function optimizer_func_201(x){ let y = x + 445; y += optimizer_helper(38); return y; }
function optimizer_func_202(x){ let y = x + 469; y += ast_helper(11); return y; }
function optimizer_func_203(x){ let y = x + 83; y += lexer_helper(1); return y; }
function optimizer_func_204(x){ let y = x + 255; y += optimizer_helper(47); return y; }
function optimizer_func_205(x){ let y = x + 935; y += lexer_helper(12); return y; }
function optimizer_func_206(x){ let y = x + 893; y += lexer_helper(19); return y; }
function optimizer_func_207(x){ let y = x + 700; y += emitter_helper(48); return y; }
function optimizer_func_208(x){ let y = x + 153; y += emitter_helper(23); return y; }
function optimizer_func_209(x){ let y = x + 244; y += ast_helper(43); return y; }
function optimizer_func_210(x){ let y = x + 144; y += emitter_helper(24); return y; }
function optimizer_func_211(x){ let y = x + 35; y += parser_helper(40); return y; }
function optimizer_func_212(x){ let y = x + 863; y += optimizer_helper(17); return y; }
function optimizer_func_213(x){ let y = x + 299; y += optimizer_helper(11); return y; }
function optimizer_func_214(x){ let y = x + 136; y += lexer_helper(5); return y; }
function optimizer_func_215(x){ let y = x + 721; y += ast_helper(16); return y; }
function optimizer_func_216(x){ let y = x + 356; y += optimizer_helper(38); return y; }
function optimizer_func_217(x){ let y = x + 224; y += parser_helper(22); return y; }
function optimizer_func_218(x){ let y = x + 930; y += ast_helper(31); return y; }
function optimizer_func_219(x){ let y = x + 712; y += emitter_helper(47); return y; }
function optimizer_func_220(x){ let y = x + 558; y += ast_helper(20); return y; }
function optimizer_func_221(x){ let y = x + 825; y += lexer_helper(13); return y; }
function optimizer_func_222(x){ let y = x + 739; y += optimizer_helper(2); return y; }
function optimizer_func_223(x){ let y = x + 632; y += lexer_helper(2); return y; }
function optimizer_func_224(x){ let y = x + 403; y += optimizer_helper(9); return y; }
function optimizer_func_225(x){ let y = x + 802; y += ast_helper(11); return y; }
function optimizer_func_226(x){ let y = x + 571; y += lexer_helper(5); return y; }
function optimizer_func_227(x){ let y = x + 632; y += optimizer_helper(2); return y; }
function optimizer_func_228(x){ let y = x + 499; y += lexer_helper(42); return y; }
function optimizer_func_229(x){ let y = x + 475; y += emitter_helper(43); return y; }
function optimizer_func_230(x){ let y = x + 52; y += ast_helper(21); return y; }
function optimizer_func_231(x){ let y = x + 248; y += ast_helper(16); return y; }
function optimizer_func_232(x){ let y = x + 101; y += ast_helper(8); return y; }
function optimizer_func_233(x){ let y = x + 251; y += lexer_helper(8); return y; }
function optimizer_func_234(x){ let y = x + 716; y += lexer_helper(29); return y; }
function optimizer_func_235(x){ let y = x + 602; y += emitter_helper(20); return y; }
function optimizer_func_236(x){ let y = x + 463; y += lexer_helper(40); return y; }
function optimizer_func_237(x){ let y = x + 271; y += ast_helper(6); return y; }
function optimizer_func_238(x){ let y = x + 717; y += parser_helper(25); return y; }
function optimizer_func_239(x){ let y = x + 457; y += lexer_helper(38); return y; }
function optimizer_func_240(x){ let y = x + 295; y += optimizer_helper(42); return y; }
function optimizer_func_241(x){ let y = x + 200; y += ast_helper(1); return y; }
function optimizer_func_242(x){ let y = x + 754; y += emitter_helper(32); return y; }
function optimizer_func_243(x){ let y = x + 637; y += lexer_helper(49); return y; }
function optimizer_func_244(x){ let y = x + 911; y += parser_helper(1); return y; }
function optimizer_func_245(x){ let y = x + 499; y += lexer_helper(25); return y; }
function optimizer_func_246(x){ let y = x + 559; y += ast_helper(16); return y; }
function optimizer_func_247(x){ let y = x + 661; y += optimizer_helper(3); return y; }
function optimizer_func_248(x){ let y = x + 29; y += optimizer_helper(24); return y; }
function optimizer_func_249(x){ let y = x + 710; y += parser_helper(42); return y; }
function optimizer_func_250(x){ let y = x + 568; y += ast_helper(7); return y; }
function optimizer_func_251(x){ let y = x + 580; y += optimizer_helper(17); return y; }
function optimizer_func_252(x){ let y = x + 731; y += parser_helper(16); return y; }
function optimizer_func_253(x){ let y = x + 719; y += ast_helper(9); return y; }
function optimizer_func_254(x){ let y = x + 751; y += lexer_helper(15); return y; }
function optimizer_func_255(x){ let y = x + 305; y += parser_helper(33); return y; }
function optimizer_func_256(x){ let y = x + 338; y += optimizer_helper(36); return y; }
function optimizer_func_257(x){ let y = x + 135; y += ast_helper(41); return y; }
function optimizer_func_258(x){ let y = x + 194; y += lexer_helper(49); return y; }
function optimizer_func_259(x){ let y = x + 688; y += ast_helper(40); return y; }
function optimizer_func_260(x){ let y = x + 404; y += ast_helper(5); return y; }
function optimizer_func_261(x){ let y = x + 910; y += ast_helper(40); return y; }
function optimizer_func_262(x){ let y = x + 593; y += lexer_helper(8); return y; }
function optimizer_func_263(x){ let y = x + 790; y += emitter_helper(46); return y; }
function optimizer_func_264(x){ let y = x + 708; y += lexer_helper(0); return y; }
function optimizer_func_265(x){ let y = x + 301; y += emitter_helper(3); return y; }
function optimizer_func_266(x){ let y = x + 305; y += emitter_helper(35); return y; }
function optimizer_func_267(x){ let y = x + 653; y += emitter_helper(16); return y; }
function optimizer_func_268(x){ let y = x + 167; y += lexer_helper(38); return y; }
function optimizer_func_269(x){ let y = x + 378; y += lexer_helper(29); return y; }
function optimizer_func_270(x){ let y = x + 914; y += optimizer_helper(26); return y; }
function optimizer_func_271(x){ let y = x + 856; y += ast_helper(5); return y; }
function optimizer_func_272(x){ let y = x + 207; y += lexer_helper(39); return y; }
function optimizer_func_273(x){ let y = x + 843; y += optimizer_helper(26); return y; }
function optimizer_func_274(x){ let y = x + 795; y += optimizer_helper(28); return y; }
function optimizer_func_275(x){ let y = x + 683; y += emitter_helper(15); return y; }
function optimizer_func_276(x){ let y = x + 952; y += ast_helper(3); return y; }
function optimizer_func_277(x){ let y = x + 679; y += lexer_helper(34); return y; }
function optimizer_func_278(x){ let y = x + 915; y += ast_helper(21); return y; }
function optimizer_func_279(x){ let y = x + 630; y += optimizer_helper(44); return y; }
function optimizer_func_280(x){ let y = x + 964; y += ast_helper(19); return y; }
function optimizer_func_281(x){ let y = x + 409; y += parser_helper(26); return y; }
function optimizer_func_282(x){ let y = x + 702; y += lexer_helper(19); return y; }
function optimizer_func_283(x){ let y = x + 789; y += parser_helper(42); return y; }
function optimizer_func_284(x){ let y = x + 219; y += lexer_helper(34); return y; }
function optimizer_func_285(x){ let y = x + 272; y += optimizer_helper(38); return y; }
function optimizer_func_286(x){ let y = x + 331; y += emitter_helper(31); return y; }
function optimizer_func_287(x){ let y = x + 189; y += lexer_helper(34); return y; }
function optimizer_func_288(x){ let y = x + 800; y += ast_helper(4); return y; }
function optimizer_func_289(x){ let y = x + 19; y += lexer_helper(25); return y; }
function optimizer_func_290(x){ let y = x + 827; y += lexer_helper(38); return y; }
function optimizer_func_291(x){ let y = x + 821; y += lexer_helper(37); return y; }
function optimizer_func_292(x){ let y = x + 815; y += ast_helper(19); return y; }
function optimizer_func_293(x){ let y = x + 716; y += lexer_helper(41); return y; }
function optimizer_func_294(x){ let y = x + 744; y += emitter_helper(4); return y; }
function optimizer_func_295(x){ let y = x + 550; y += emitter_helper(33); return y; }
function optimizer_func_296(x){ let y = x + 571; y += optimizer_helper(41); return y; }
function optimizer_func_297(x){ let y = x + 190; y += emitter_helper(34); return y; }
function optimizer_func_298(x){ let y = x + 979; y += lexer_helper(40); return y; }
function optimizer_func_299(x){ let y = x + 609; y += emitter_helper(36); return y; }
function optimizer_func_300(x){ let y = x + 46; y += emitter_helper(13); return y; }
function optimizer_func_301(x){ let y = x + 118; y += ast_helper(42); return y; }
function optimizer_func_302(x){ let y = x + 759; y += emitter_helper(2); return y; }
function optimizer_func_303(x){ let y = x + 820; y += emitter_helper(24); return y; }
function optimizer_func_304(x){ let y = x + 309; y += emitter_helper(0); return y; }
function optimizer_func_305(x){ let y = x + 145; y += ast_helper(18); return y; }
function optimizer_func_306(x){ let y = x + 548; y += parser_helper(19); return y; }
function optimizer_func_307(x){ let y = x + 203; y += lexer_helper(2); return y; }
function optimizer_func_308(x){ let y = x + 193; y += ast_helper(16); return y; }
function optimizer_func_309(x){ let y = x + 565; y += ast_helper(37); return y; }
function optimizer_func_310(x){ let y = x + 779; y += lexer_helper(48); return y; }
function optimizer_func_311(x){ let y = x + 172; y += lexer_helper(27); return y; }
function optimizer_func_312(x){ let y = x + 423; y += lexer_helper(1); return y; }
function optimizer_func_313(x){ let y = x + 24; y += lexer_helper(40); return y; }
function optimizer_func_314(x){ let y = x + 344; y += lexer_helper(12); return y; }
function optimizer_func_315(x){ let y = x + 935; y += emitter_helper(37); return y; }
function optimizer_func_316(x){ let y = x + 606; y += emitter_helper(45); return y; }
function optimizer_func_317(x){ let y = x + 318; y += optimizer_helper(35); return y; }
function optimizer_func_318(x){ let y = x + 859; y += optimizer_helper(6); return y; }
function optimizer_func_319(x){ let y = x + 661; y += parser_helper(45); return y; }
function optimizer_func_320(x){ let y = x + 415; y += emitter_helper(5); return y; }
function optimizer_func_321(x){ let y = x + 693; y += parser_helper(6); return y; }
function optimizer_func_322(x){ let y = x + 140; y += lexer_helper(15); return y; }
function optimizer_func_323(x){ let y = x + 565; y += lexer_helper(41); return y; }
function optimizer_func_324(x){ let y = x + 137; y += emitter_helper(21); return y; }
function optimizer_func_325(x){ let y = x + 476; y += parser_helper(30); return y; }
function optimizer_func_326(x){ let y = x + 258; y += parser_helper(37); return y; }
function optimizer_func_327(x){ let y = x + 516; y += optimizer_helper(1); return y; }
function optimizer_func_328(x){ let y = x + 320; y += optimizer_helper(1); return y; }
function optimizer_func_329(x){ let y = x + 663; y += lexer_helper(6); return y; }
function optimizer_func_330(x){ let y = x + 980; y += lexer_helper(44); return y; }
function optimizer_func_331(x){ let y = x + 307; y += lexer_helper(27); return y; }
function optimizer_func_332(x){ let y = x + 565; y += ast_helper(36); return y; }
function optimizer_func_333(x){ let y = x + 752; y += lexer_helper(36); return y; }
function optimizer_func_334(x){ let y = x + 827; y += optimizer_helper(22); return y; }
function optimizer_func_335(x){ let y = x + 529; y += parser_helper(23); return y; }
function optimizer_func_336(x){ let y = x + 848; y += optimizer_helper(39); return y; }
function optimizer_func_337(x){ let y = x + 953; y += parser_helper(39); return y; }
function optimizer_func_338(x){ let y = x + 324; y += optimizer_helper(17); return y; }
function optimizer_func_339(x){ let y = x + 549; y += emitter_helper(29); return y; }
function optimizer_func_340(x){ let y = x + 612; y += parser_helper(22); return y; }
function optimizer_func_341(x){ let y = x + 173; y += optimizer_helper(5); return y; }
function optimizer_func_342(x){ let y = x + 776; y += ast_helper(47); return y; }
function optimizer_func_343(x){ let y = x + 784; y += lexer_helper(41); return y; }
function optimizer_func_344(x){ let y = x + 792; y += emitter_helper(25); return y; }
function optimizer_func_345(x){ let y = x + 268; y += emitter_helper(5); return y; }
function optimizer_func_346(x){ let y = x + 652; y += lexer_helper(37); return y; }
function optimizer_func_347(x){ let y = x + 66; y += parser_helper(37); return y; }
function optimizer_func_348(x){ let y = x + 911; y += lexer_helper(20); return y; }
function optimizer_func_349(x){ let y = x + 395; y += optimizer_helper(2); return y; }
function optimizer_func_350(x){ let y = x + 390; y += emitter_helper(14); return y; }
function optimizer_func_351(x){ let y = x + 545; y += optimizer_helper(47); return y; }
function optimizer_func_352(x){ let y = x + 405; y += emitter_helper(16); return y; }
function optimizer_func_353(x){ let y = x + 77; y += ast_helper(39); return y; }
function optimizer_func_354(x){ let y = x + 164; y += parser_helper(26); return y; }
function optimizer_func_355(x){ let y = x + 973; y += lexer_helper(48); return y; }
function optimizer_func_356(x){ let y = x + 898; y += emitter_helper(23); return y; }
function optimizer_func_357(x){ let y = x + 359; y += emitter_helper(46); return y; }
function optimizer_func_358(x){ let y = x + 208; y += parser_helper(23); return y; }
function optimizer_func_359(x){ let y = x + 104; y += parser_helper(8); return y; }
function optimizer_func_360(x){ let y = x + 107; y += optimizer_helper(30); return y; }
function optimizer_func_361(x){ let y = x + 291; y += parser_helper(12); return y; }
function optimizer_func_362(x){ let y = x + 832; y += parser_helper(14); return y; }
function optimizer_func_363(x){ let y = x + 797; y += parser_helper(49); return y; }
function optimizer_func_364(x){ let y = x + 527; y += parser_helper(37); return y; }
function optimizer_func_365(x){ let y = x + 589; y += ast_helper(6); return y; }
function optimizer_func_366(x){ let y = x + 887; y += lexer_helper(39); return y; }
function optimizer_func_367(x){ let y = x + 343; y += ast_helper(5); return y; }
function optimizer_func_368(x){ let y = x + 643; y += emitter_helper(33); return y; }
function optimizer_func_369(x){ let y = x + 896; y += lexer_helper(27); return y; }
function optimizer_func_370(x){ let y = x + 181; y += ast_helper(15); return y; }
function optimizer_func_371(x){ let y = x + 59; y += optimizer_helper(37); return y; }
function optimizer_func_372(x){ let y = x + 284; y += ast_helper(5); return y; }
function optimizer_func_373(x){ let y = x + 719; y += lexer_helper(13); return y; }
function optimizer_func_374(x){ let y = x + 827; y += emitter_helper(37); return y; }
function optimizer_func_375(x){ let y = x + 902; y += parser_helper(19); return y; }
function optimizer_func_376(x){ let y = x + 652; y += lexer_helper(25); return y; }
function optimizer_func_377(x){ let y = x + 899; y += lexer_helper(48); return y; }
function optimizer_func_378(x){ let y = x + 53; y += lexer_helper(12); return y; }
function optimizer_func_379(x){ let y = x + 339; y += optimizer_helper(13); return y; }
function optimizer_func_380(x){ let y = x + 476; y += lexer_helper(3); return y; }
function optimizer_func_381(x){ let y = x + 783; y += parser_helper(8); return y; }
function optimizer_func_382(x){ let y = x + 420; y += lexer_helper(28); return y; }
function optimizer_func_383(x){ let y = x + 728; y += emitter_helper(10); return y; }
function optimizer_func_384(x){ let y = x + 226; y += emitter_helper(23); return y; }
function optimizer_func_385(x){ let y = x + 86; y += ast_helper(44); return y; }
function optimizer_func_386(x){ let y = x + 438; y += lexer_helper(43); return y; }
function optimizer_func_387(x){ let y = x + 652; y += optimizer_helper(45); return y; }
function optimizer_func_388(x){ let y = x + 917; y += lexer_helper(46); return y; }
function optimizer_func_389(x){ let y = x + 537; y += emitter_helper(47); return y; }
function optimizer_func_390(x){ let y = x + 554; y += parser_helper(11); return y; }
function optimizer_func_391(x){ let y = x + 108; y += ast_helper(20); return y; }
function optimizer_func_392(x){ let y = x + 488; y += optimizer_helper(27); return y; }
function optimizer_func_393(x){ let y = x + 610; y += optimizer_helper(29); return y; }
function optimizer_func_394(x){ let y = x + 602; y += lexer_helper(48); return y; }
function optimizer_func_395(x){ let y = x + 766; y += parser_helper(34); return y; }
function optimizer_func_396(x){ let y = x + 989; y += parser_helper(7); return y; }
function optimizer_func_397(x){ let y = x + 987; y += lexer_helper(6); return y; }
function optimizer_func_398(x){ let y = x + 82; y += emitter_helper(20); return y; }
function optimizer_func_399(x){ let y = x + 287; y += parser_helper(31); return y; }
function optimizer_func_400(x){ let y = x + 635; y += emitter_helper(5); return y; }
function optimizer_func_401(x){ let y = x + 924; y += ast_helper(36); return y; }
function optimizer_func_402(x){ let y = x + 191; y += lexer_helper(40); return y; }
function optimizer_func_403(x){ let y = x + 596; y += optimizer_helper(8); return y; }
function optimizer_func_404(x){ let y = x + 178; y += lexer_helper(32); return y; }
function optimizer_func_405(x){ let y = x + 533; y += ast_helper(22); return y; }
function optimizer_func_406(x){ let y = x + 265; y += lexer_helper(27); return y; }
function optimizer_func_407(x){ let y = x + 781; y += emitter_helper(37); return y; }
function optimizer_func_408(x){ let y = x + 169; y += lexer_helper(23); return y; }
function optimizer_func_409(x){ let y = x + 946; y += ast_helper(26); return y; }
function optimizer_func_410(x){ let y = x + 952; y += lexer_helper(38); return y; }
function optimizer_func_411(x){ let y = x + 129; y += optimizer_helper(21); return y; }
function optimizer_func_412(x){ let y = x + 569; y += optimizer_helper(1); return y; }
function optimizer_func_413(x){ let y = x + 660; y += parser_helper(26); return y; }
function optimizer_func_414(x){ let y = x + 113; y += emitter_helper(25); return y; }
function optimizer_func_415(x){ let y = x + 176; y += parser_helper(5); return y; }
function optimizer_func_416(x){ let y = x + 190; y += lexer_helper(42); return y; }
function optimizer_func_417(x){ let y = x + 296; y += emitter_helper(49); return y; }
function optimizer_func_418(x){ let y = x + 901; y += lexer_helper(10); return y; }
function optimizer_func_419(x){ let y = x + 904; y += lexer_helper(44); return y; }
function optimizer_func_420(x){ let y = x + 958; y += ast_helper(30); return y; }
function optimizer_func_421(x){ let y = x + 512; y += optimizer_helper(29); return y; }
function optimizer_func_422(x){ let y = x + 168; y += emitter_helper(16); return y; }
function optimizer_func_423(x){ let y = x + 515; y += parser_helper(18); return y; }
function optimizer_func_424(x){ let y = x + 434; y += lexer_helper(0); return y; }
function optimizer_func_425(x){ let y = x + 852; y += optimizer_helper(30); return y; }
function optimizer_func_426(x){ let y = x + 481; y += emitter_helper(4); return y; }
function optimizer_func_427(x){ let y = x + 538; y += ast_helper(3); return y; }
function optimizer_func_428(x){ let y = x + 957; y += parser_helper(4); return y; }
function optimizer_func_429(x){ let y = x + 31; y += emitter_helper(1); return y; }
function optimizer_func_430(x){ let y = x + 559; y += parser_helper(16); return y; }
function optimizer_func_431(x){ let y = x + 220; y += parser_helper(3); return y; }
function optimizer_func_432(x){ let y = x + 576; y += emitter_helper(34); return y; }
function optimizer_func_433(x){ let y = x + 388; y += lexer_helper(41); return y; }
function optimizer_func_434(x){ let y = x + 327; y += optimizer_helper(30); return y; }
function optimizer_func_435(x){ let y = x + 737; y += emitter_helper(48); return y; }
function optimizer_func_436(x){ let y = x + 214; y += optimizer_helper(32); return y; }
function optimizer_func_437(x){ let y = x + 475; y += emitter_helper(24); return y; }
function optimizer_func_438(x){ let y = x + 934; y += parser_helper(38); return y; }
function optimizer_func_439(x){ let y = x + 920; y += emitter_helper(17); return y; }
function optimizer_func_440(x){ let y = x + 490; y += optimizer_helper(33); return y; }
function optimizer_func_441(x){ let y = x + 476; y += emitter_helper(41); return y; }
function optimizer_func_442(x){ let y = x + 341; y += optimizer_helper(48); return y; }
function optimizer_func_443(x){ let y = x + 119; y += ast_helper(44); return y; }
function optimizer_func_444(x){ let y = x + 899; y += lexer_helper(26); return y; }
function optimizer_func_445(x){ let y = x + 840; y += ast_helper(22); return y; }
function optimizer_func_446(x){ let y = x + 578; y += parser_helper(8); return y; }
function optimizer_func_447(x){ let y = x + 763; y += parser_helper(1); return y; }
function optimizer_func_448(x){ let y = x + 26; y += ast_helper(16); return y; }
function optimizer_func_449(x){ let y = x + 360; y += parser_helper(21); return y; }
function optimizer_func_450(x){ let y = x + 510; y += emitter_helper(20); return y; }
function optimizer_func_451(x){ let y = x + 59; y += lexer_helper(10); return y; }
function optimizer_func_452(x){ let y = x + 698; y += parser_helper(18); return y; }
function optimizer_func_453(x){ let y = x + 755; y += emitter_helper(14); return y; }
function optimizer_func_454(x){ let y = x + 660; y += ast_helper(20); return y; }
function optimizer_func_455(x){ let y = x + 371; y += emitter_helper(9); return y; }
function optimizer_func_456(x){ let y = x + 942; y += parser_helper(14); return y; }
function optimizer_func_457(x){ let y = x + 821; y += ast_helper(47); return y; }
function optimizer_func_458(x){ let y = x + 841; y += optimizer_helper(46); return y; }
function optimizer_func_459(x){ let y = x + 946; y += lexer_helper(37); return y; }
function optimizer_func_460(x){ let y = x + 64; y += optimizer_helper(24); return y; }
function optimizer_func_461(x){ let y = x + 730; y += parser_helper(37); return y; }
function optimizer_func_462(x){ let y = x + 663; y += optimizer_helper(3); return y; }
function optimizer_func_463(x){ let y = x + 94; y += lexer_helper(11); return y; }
function optimizer_func_464(x){ let y = x + 400; y += parser_helper(16); return y; }
function optimizer_func_465(x){ let y = x + 322; y += emitter_helper(25); return y; }
function optimizer_func_466(x){ let y = x + 276; y += parser_helper(0); return y; }
function optimizer_func_467(x){ let y = x + 294; y += optimizer_helper(32); return y; }
function optimizer_func_468(x){ let y = x + 222; y += emitter_helper(16); return y; }
function optimizer_func_469(x){ let y = x + 514; y += ast_helper(41); return y; }
function optimizer_func_470(x){ let y = x + 646; y += parser_helper(47); return y; }
function optimizer_func_471(x){ let y = x + 440; y += ast_helper(41); return y; }
function optimizer_func_472(x){ let y = x + 129; y += ast_helper(29); return y; }
function optimizer_func_473(x){ let y = x + 474; y += lexer_helper(24); return y; }
function optimizer_func_474(x){ let y = x + 982; y += emitter_helper(4); return y; }
function optimizer_func_475(x){ let y = x + 18; y += optimizer_helper(26); return y; }
function optimizer_func_476(x){ let y = x + 342; y += lexer_helper(33); return y; }
function optimizer_func_477(x){ let y = x + 600; y += optimizer_helper(29); return y; }
function optimizer_func_478(x){ let y = x + 313; y += parser_helper(27); return y; }
function optimizer_func_479(x){ let y = x + 162; y += emitter_helper(19); return y; }
function optimizer_func_480(x){ let y = x + 603; y += ast_helper(0); return y; }
function optimizer_func_481(x){ let y = x + 972; y += parser_helper(1); return y; }
function optimizer_func_482(x){ let y = x + 372; y += ast_helper(38); return y; }
function optimizer_func_483(x){ let y = x + 78; y += emitter_helper(35); return y; }
function optimizer_func_484(x){ let y = x + 249; y += emitter_helper(27); return y; }
function optimizer_func_485(x){ let y = x + 225; y += ast_helper(36); return y; }
function optimizer_func_486(x){ let y = x + 841; y += parser_helper(3); return y; }
function optimizer_func_487(x){ let y = x + 171; y += lexer_helper(37); return y; }
function optimizer_func_488(x){ let y = x + 778; y += ast_helper(29); return y; }
function optimizer_func_489(x){ let y = x + 419; y += parser_helper(44); return y; }
function optimizer_func_490(x){ let y = x + 8; y += parser_helper(24); return y; }
function optimizer_func_491(x){ let y = x + 44; y += emitter_helper(42); return y; }
function optimizer_func_492(x){ let y = x + 251; y += optimizer_helper(39); return y; }
function optimizer_func_493(x){ let y = x + 415; y += emitter_helper(39); return y; }
function optimizer_func_494(x){ let y = x + 789; y += parser_helper(20); return y; }
function optimizer_func_495(x){ let y = x + 393; y += lexer_helper(43); return y; }
function optimizer_func_496(x){ let y = x + 864; y += lexer_helper(36); return y; }
function optimizer_func_497(x){ let y = x + 910; y += parser_helper(36); return y; }
function optimizer_func_498(x){ let y = x + 446; y += emitter_helper(7); return y; }
function optimizer_func_499(x){ let y = x + 968; y += emitter_helper(16); return y; }
function lexer_helper(x){ return x*20; }
function parser_helper(x){ return x*6; }
function ast_helper(x){ return x*12; }
function optimizer_helper(x){ return x*19; }
function emitter_helper(x){ return x*13; }
module.exports = { lexer_init, parser_init, ast_init, optimizer_init, emitter_init };
