// Module lexer
function lexer_init(){ console.log("Initializing lexer"); }
function lexer_func_0(x){ let y = x + 551; y += emitter_helper(11); return y; }
function lexer_func_1(x){ let y = x + 958; y += emitter_helper(32); return y; }
function lexer_func_2(x){ let y = x + 99; y += optimizer_helper(37); return y; }
function lexer_func_3(x){ let y = x + 687; y += emitter_helper(31); return y; }
function lexer_func_4(x){ let y = x + 914; y += optimizer_helper(19); return y; }
function lexer_func_5(x){ let y = x + 142; y += ast_helper(49); return y; }
function lexer_func_6(x){ let y = x + 990; y += parser_helper(2); return y; }
function lexer_func_7(x){ let y = x + 199; y += optimizer_helper(45); return y; }
function lexer_func_8(x){ let y = x + 655; y += parser_helper(42); return y; }
function lexer_func_9(x){ let y = x + 801; y += ast_helper(24); return y; }
function lexer_func_10(x){ let y = x + 612; y += parser_helper(38); return y; }
function lexer_func_11(x){ let y = x + 798; y += ast_helper(25); return y; }
function lexer_func_12(x){ let y = x + 680; y += parser_helper(39); return y; }
function lexer_func_13(x){ let y = x + 759; y += lexer_helper(26); return y; }
function lexer_func_14(x){ let y = x + 375; y += lexer_helper(37); return y; }
function lexer_func_15(x){ let y = x + 955; y += optimizer_helper(41); return y; }
function lexer_func_16(x){ let y = x + 807; y += optimizer_helper(8); return y; }
function lexer_func_17(x){ let y = x + 663; y += parser_helper(29); return y; }
function lexer_func_18(x){ let y = x + 945; y += optimizer_helper(42); return y; }
function lexer_func_19(x){ let y = x + 127; y += parser_helper(9); return y; }
function lexer_func_20(x){ let y = x + 719; y += emitter_helper(4); return y; }
function lexer_func_21(x){ let y = x + 88; y += lexer_helper(28); return y; }
function lexer_func_22(x){ let y = x + 373; y += parser_helper(15); return y; }
function lexer_func_23(x){ let y = x + 950; y += ast_helper(3); return y; }
function lexer_func_24(x){ let y = x + 154; y += parser_helper(42); return y; }
function lexer_func_25(x){ let y = x + 556; y += ast_helper(36); return y; }
function lexer_func_26(x){ let y = x + 45; y += emitter_helper(10); return y; }
function lexer_func_27(x){ let y = x + 906; y += optimizer_helper(10); return y; }
function lexer_func_28(x){ let y = x + 3; y += optimizer_helper(26); return y; }
function lexer_func_29(x){ let y = x + 276; y += parser_helper(20); return y; }
function lexer_func_30(x){ let y = x + 911; y += emitter_helper(39); return y; }
function lexer_func_31(x){ let y = x + 352; y += optimizer_helper(23); return y; }
function lexer_func_32(x){ let y = x + 20; y += lexer_helper(23); return y; }
function lexer_func_33(x){ let y = x + 517; y += lexer_helper(11); return y; }
function lexer_func_34(x){ let y = x + 844; y += parser_helper(15); return y; }
function lexer_func_35(x){ let y = x + 555; y += optimizer_helper(24); return y; }
function lexer_func_36(x){ let y = x + 24; y += lexer_helper(6); return y; }
function lexer_func_37(x){ let y = x + 845; y += parser_helper(6); return y; }
function lexer_func_38(x){ let y = x + 122; y += parser_helper(17); return y; }
function lexer_func_39(x){ let y = x + 233; y += lexer_helper(36); return y; }
function lexer_func_40(x){ let y = x + 162; y += optimizer_helper(21); return y; }
function lexer_func_41(x){ let y = x + 421; y += emitter_helper(37); return y; }
function lexer_func_42(x){ let y = x + 743; y += optimizer_helper(41); return y; }
function lexer_func_43(x){ let y = x + 712; y += lexer_helper(47); return y; }
function lexer_func_44(x){ let y = x + 486; y += emitter_helper(34); return y; }
function lexer_func_45(x){ let y = x + 210; y += emitter_helper(46); return y; }
function lexer_func_46(x){ let y = x + 819; y += parser_helper(19); return y; }
function lexer_func_47(x){ let y = x + 960; y += emitter_helper(45); return y; }
function lexer_func_48(x){ let y = x + 120; y += emitter_helper(12); return y; }
function lexer_func_49(x){ let y = x + 383; y += ast_helper(34); return y; }
function lexer_func_50(x){ let y = x + 356; y += lexer_helper(47); return y; }
function lexer_func_51(x){ let y = x + 378; y += emitter_helper(39); return y; }
function lexer_func_52(x){ let y = x + 808; y += emitter_helper(8); return y; }
function lexer_func_53(x){ let y = x + 16; y += ast_helper(16); return y; }
function lexer_func_54(x){ let y = x + 294; y += ast_helper(4); return y; }
function lexer_func_55(x){ let y = x + 494; y += emitter_helper(6); return y; }
function lexer_func_56(x){ let y = x + 245; y += emitter_helper(33); return y; }
function lexer_func_57(x){ let y = x + 938; y += parser_helper(35); return y; }
function lexer_func_58(x){ let y = x + 590; y += emitter_helper(21); return y; }
function lexer_func_59(x){ let y = x + 480; y += emitter_helper(48); return y; }
function lexer_func_60(x){ let y = x + 284; y += emitter_helper(36); return y; }
function lexer_func_61(x){ let y = x + 175; y += optimizer_helper(36); return y; }
function lexer_func_62(x){ let y = x + 422; y += parser_helper(17); return y; }
function lexer_func_63(x){ let y = x + 820; y += parser_helper(36); return y; }
function lexer_func_64(x){ let y = x + 442; y += ast_helper(32); return y; }
function lexer_func_65(x){ let y = x + 436; y += optimizer_helper(11); return y; }
function lexer_func_66(x){ let y = x + 918; y += ast_helper(49); return y; }
function lexer_func_67(x){ let y = x + 393; y += lexer_helper(49); return y; }
function lexer_func_68(x){ let y = x + 455; y += lexer_helper(39); return y; }
function lexer_func_69(x){ let y = x + 23; y += ast_helper(27); return y; }
function lexer_func_70(x){ let y = x + 247; y += emitter_helper(35); return y; }
function lexer_func_71(x){ let y = x + 20; y += ast_helper(13); return y; }
function lexer_func_72(x){ let y = x + 976; y += ast_helper(47); return y; }
function lexer_func_73(x){ let y = x + 527; y += lexer_helper(20); return y; }
function lexer_func_74(x){ let y = x + 854; y += lexer_helper(23); return y; }
function lexer_func_75(x){ let y = x + 754; y += emitter_helper(43); return y; }
function lexer_func_76(x){ let y = x + 531; y += ast_helper(20); return y; }
function lexer_func_77(x){ let y = x + 492; y += emitter_helper(40); return y; }
function lexer_func_78(x){ let y = x + 1; y += ast_helper(48); return y; }
function lexer_func_79(x){ let y = x + 431; y += emitter_helper(41); return y; }
function lexer_func_80(x){ let y = x + 788; y += parser_helper(32); return y; }
function lexer_func_81(x){ let y = x + 731; y += ast_helper(35); return y; }
function lexer_func_82(x){ let y = x + 74; y += parser_helper(47); return y; }
function lexer_func_83(x){ let y = x + 585; y += ast_helper(20); return y; }
function lexer_func_84(x){ let y = x + 793; y += emitter_helper(7); return y; }
function lexer_func_85(x){ let y = x + 937; y += parser_helper(46); return y; }
function lexer_func_86(x){ let y = x + 949; y += emitter_helper(40); return y; }
function lexer_func_87(x){ let y = x + 92; y += emitter_helper(25); return y; }
function lexer_func_88(x){ let y = x + 317; y += lexer_helper(11); return y; }
function lexer_func_89(x){ let y = x + 791; y += emitter_helper(13); return y; }
function lexer_func_90(x){ let y = x + 293; y += ast_helper(4); return y; }
function lexer_func_91(x){ let y = x + 105; y += ast_helper(41); return y; }
function lexer_func_92(x){ let y = x + 147; y += emitter_helper(15); return y; }
function lexer_func_93(x){ let y = x + 305; y += emitter_helper(15); return y; }
function lexer_func_94(x){ let y = x + 797; y += emitter_helper(36); return y; }
function lexer_func_95(x){ let y = x + 819; y += lexer_helper(6); return y; }
function lexer_func_96(x){ let y = x + 168; y += optimizer_helper(34); return y; }
function lexer_func_97(x){ let y = x + 901; y += emitter_helper(32); return y; }
function lexer_func_98(x){ let y = x + 533; y += ast_helper(43); return y; }
function lexer_func_99(x){ let y = x + 4; y += ast_helper(7); return y; }
function lexer_func_100(x){ let y = x + 978; y += parser_helper(15); return y; }
function lexer_func_101(x){ let y = x + 788; y += lexer_helper(30); return y; }
function lexer_func_102(x){ let y = x + 205; y += ast_helper(33); return y; }
function lexer_func_103(x){ let y = x + 779; y += emitter_helper(0); return y; }
function lexer_func_104(x){ let y = x + 141; y += optimizer_helper(32); return y; }
function lexer_func_105(x){ let y = x + 953; y += emitter_helper(14); return y; }
function lexer_func_106(x){ let y = x + 799; y += optimizer_helper(46); return y; }
function lexer_func_107(x){ let y = x + 349; y += lexer_helper(30); return y; }
function lexer_func_108(x){ let y = x + 634; y += emitter_helper(21); return y; }
function lexer_func_109(x){ let y = x + 802; y += lexer_helper(6); return y; }
function lexer_func_110(x){ let y = x + 665; y += lexer_helper(20); return y; }
function lexer_func_111(x){ let y = x + 725; y += optimizer_helper(26); return y; }
function lexer_func_112(x){ let y = x + 320; y += emitter_helper(6); return y; }
function lexer_func_113(x){ let y = x + 541; y += lexer_helper(22); return y; }
function lexer_func_114(x){ let y = x + 4; y += emitter_helper(17); return y; }
function lexer_func_115(x){ let y = x + 382; y += lexer_helper(40); return y; }
function lexer_func_116(x){ let y = x + 367; y += ast_helper(29); return y; }
function lexer_func_117(x){ let y = x + 734; y += optimizer_helper(29); return y; }
function lexer_func_118(x){ let y = x + 614; y += lexer_helper(39); return y; }
function lexer_func_119(x){ let y = x + 585; y += parser_helper(47); return y; }
function lexer_func_120(x){ let y = x + 96; y += lexer_helper(4); return y; }
function lexer_func_121(x){ let y = x + 371; y += emitter_helper(32); return y; }
function lexer_func_122(x){ let y = x + 139; y += lexer_helper(7); return y; }
function lexer_func_123(x){ let y = x + 968; y += optimizer_helper(49); return y; }
function lexer_func_124(x){ let y = x + 905; y += emitter_helper(10); return y; }
function lexer_func_125(x){ let y = x + 225; y += ast_helper(31); return y; }
function lexer_func_126(x){ let y = x + 539; y += optimizer_helper(0); return y; }
function lexer_func_127(x){ let y = x + 314; y += ast_helper(46); return y; }
function lexer_func_128(x){ let y = x + 806; y += parser_helper(20); return y; }
function lexer_func_129(x){ let y = x + 536; y += optimizer_helper(41); return y; }
function lexer_func_130(x){ let y = x + 946; y += optimizer_helper(24); return y; }
function lexer_func_131(x){ let y = x + 404; y += ast_helper(8); return y; }
function lexer_func_132(x){ let y = x + 750; y += emitter_helper(38); return y; }
function lexer_func_133(x){ let y = x + 891; y += parser_helper(22); return y; }
function lexer_func_134(x){ let y = x + 579; y += lexer_helper(11); return y; }
function lexer_func_135(x){ let y = x + 340; y += ast_helper(31); return y; }
function lexer_func_136(x){ let y = x + 248; y += parser_helper(2); return y; }
function lexer_func_137(x){ let y = x + 418; y += parser_helper(14); return y; }
function lexer_func_138(x){ let y = x + 811; y += optimizer_helper(47); return y; }
function lexer_func_139(x){ let y = x + 620; y += optimizer_helper(16); return y; }
function lexer_func_140(x){ let y = x + 379; y += lexer_helper(13); return y; }
function lexer_func_141(x){ let y = x + 663; y += ast_helper(20); return y; }
function lexer_func_142(x){ let y = x + 124; y += lexer_helper(32); return y; }
function lexer_func_143(x){ let y = x + 32; y += ast_helper(41); return y; }
function lexer_func_144(x){ let y = x + 561; y += parser_helper(3); return y; }
function lexer_func_145(x){ let y = x + 607; y += optimizer_helper(1); return y; }
function lexer_func_146(x){ let y = x + 667; y += emitter_helper(44); return y; }
function lexer_func_147(x){ let y = x + 746; y += optimizer_helper(47); return y; }
function lexer_func_148(x){ let y = x + 13; y += parser_helper(43); return y; }
function lexer_func_149(x){ let y = x + 442; y += emitter_helper(4); return y; }
function lexer_func_150(x){ let y = x + 450; y += lexer_helper(1); return y; }
function lexer_func_151(x){ let y = x + 897; y += optimizer_helper(21); return y; }
function lexer_func_152(x){ let y = x + 249; y += lexer_helper(12); return y; }
function lexer_func_153(x){ let y = x + 882; y += optimizer_helper(39); return y; }
function lexer_func_154(x){ let y = x + 589; y += parser_helper(23); return y; }
function lexer_func_155(x){ let y = x + 721; y += ast_helper(37); return y; }
function lexer_func_156(x){ let y = x + 554; y += optimizer_helper(47); return y; }
function lexer_func_157(x){ let y = x + 381; y += emitter_helper(44); return y; }
function lexer_func_158(x){ let y = x + 596; y += parser_helper(32); return y; }
function lexer_func_159(x){ let y = x + 794; y += emitter_helper(35); return y; }
function lexer_func_160(x){ let y = x + 963; y += optimizer_helper(18); return y; }
function lexer_func_161(x){ let y = x + 896; y += ast_helper(24); return y; }
function lexer_func_162(x){ let y = x + 910; y += ast_helper(40); return y; }
function lexer_func_163(x){ let y = x + 102; y += lexer_helper(9); return y; }
function lexer_func_164(x){ let y = x + 682; y += parser_helper(40); return y; }
function lexer_func_165(x){ let y = x + 438; y += lexer_helper(22); return y; }
function lexer_func_166(x){ let y = x + 823; y += ast_helper(20); return y; }
function lexer_func_167(x){ let y = x + 860; y += ast_helper(18); return y; }
function lexer_func_168(x){ let y = x + 514; y += lexer_helper(18); return y; }
function lexer_func_169(x){ let y = x + 85; y += optimizer_helper(21); return y; }
function lexer_func_170(x){ let y = x + 527; y += emitter_helper(14); return y; }
function lexer_func_171(x){ let y = x + 235; y += lexer_helper(12); return y; }
function lexer_func_172(x){ let y = x + 722; y += parser_helper(21); return y; }
function lexer_func_173(x){ let y = x + 49; y += lexer_helper(27); return y; }
function lexer_func_174(x){ let y = x + 453; y += emitter_helper(47); return y; }
function lexer_func_175(x){ let y = x + 114; y += ast_helper(30); return y; }
function lexer_func_176(x){ let y = x + 219; y += optimizer_helper(33); return y; }
function lexer_func_177(x){ let y = x + 99; y += ast_helper(34); return y; }
function lexer_func_178(x){ let y = x + 927; y += emitter_helper(44); return y; }
function lexer_func_179(x){ let y = x + 232; y += ast_helper(28); return y; }
function lexer_func_180(x){ let y = x + 8; y += lexer_helper(24); return y; }
function lexer_func_181(x){ let y = x + 890; y += optimizer_helper(39); return y; }
function lexer_func_182(x){ let y = x + 572; y += parser_helper(1); return y; }
function lexer_func_183(x){ let y = x + 948; y += emitter_helper(6); return y; }
function lexer_func_184(x){ let y = x + 96; y += parser_helper(11); return y; }
function lexer_func_185(x){ let y = x + 723; y += parser_helper(3); return y; }
function lexer_func_186(x){ let y = x + 652; y += ast_helper(17); return y; }
function lexer_func_187(x){ let y = x + 272; y += ast_helper(45); return y; }
function lexer_func_188(x){ let y = x + 697; y += ast_helper(6); return y; }
function lexer_func_189(x){ let y = x + 397; y += optimizer_helper(21); return y; }
function lexer_func_190(x){ let y = x + 569; y += optimizer_helper(37); return y; }
function lexer_func_191(x){ let y = x + 644; y += ast_helper(47); return y; }
function lexer_func_192(x){ let y = x + 737; y += lexer_helper(40); return y; }
function lexer_func_193(x){ let y = x + 7; y += ast_helper(45); return y; }
function lexer_func_194(x){ let y = x + 668; y += optimizer_helper(45); return y; }
function lexer_func_195(x){ let y = x + 195; y += parser_helper(29); return y; }
function lexer_func_196(x){ let y = x + 940; y += emitter_helper(41); return y; }
function lexer_func_197(x){ let y = x + 462; y += optimizer_helper(29); return y; }
function lexer_func_198(x){ let y = x + 351; y += parser_helper(41); return y; }
function lexer_func_199(x){ let y = x + 424; y += parser_helper(21); return y; }
function lexer_func_200(x){ let y = x + 165; y += lexer_helper(14); return y; }
function lexer_func_201(x){ let y = x + 132; y += emitter_helper(8); return y; }
function lexer_func_202(x){ let y = x + 33; y += lexer_helper(40); return y; }
function lexer_func_203(x){ let y = x + 986; y += ast_helper(21); return y; }
function lexer_func_204(x){ let y = x + 625; y += emitter_helper(14); return y; }
function lexer_func_205(x){ let y = x + 371; y += ast_helper(44); return y; }
function lexer_func_206(x){ let y = x + 745; y += parser_helper(19); return y; }
function lexer_func_207(x){ let y = x + 257; y += parser_helper(24); return y; }
function lexer_func_208(x){ let y = x + 14; y += optimizer_helper(23); return y; }
function lexer_func_209(x){ let y = x + 451; y += emitter_helper(27); return y; }
function lexer_func_210(x){ let y = x + 489; y += lexer_helper(0); return y; }
function lexer_func_211(x){ let y = x + 682; y += optimizer_helper(33); return y; }
function lexer_func_212(x){ let y = x + 596; y += emitter_helper(41); return y; }
function lexer_func_213(x){ let y = x + 714; y += ast_helper(43); return y; }
function lexer_func_214(x){ let y = x + 267; y += parser_helper(43); return y; }
function lexer_func_215(x){ let y = x + 344; y += ast_helper(11); return y; }
function lexer_func_216(x){ let y = x + 245; y += emitter_helper(34); return y; }
function lexer_func_217(x){ let y = x + 974; y += parser_helper(6); return y; }
function lexer_func_218(x){ let y = x + 887; y += emitter_helper(25); return y; }
function lexer_func_219(x){ let y = x + 128; y += lexer_helper(44); return y; }
function lexer_func_220(x){ let y = x + 469; y += optimizer_helper(21); return y; }
function lexer_func_221(x){ let y = x + 446; y += emitter_helper(26); return y; }
function lexer_func_222(x){ let y = x + 708; y += emitter_helper(39); return y; }
function lexer_func_223(x){ let y = x + 119; y += emitter_helper(36); return y; }
function lexer_func_224(x){ let y = x + 396; y += lexer_helper(33); return y; }
function lexer_func_225(x){ let y = x + 996; y += ast_helper(45); return y; }
function lexer_func_226(x){ let y = x + 341; y += optimizer_helper(16); return y; }
function lexer_func_227(x){ let y = x + 684; y += optimizer_helper(29); return y; }
function lexer_func_228(x){ let y = x + 645; y += emitter_helper(36); return y; }
function lexer_func_229(x){ let y = x + 813; y += optimizer_helper(6); return y; }
function lexer_func_230(x){ let y = x + 565; y += ast_helper(22); return y; }
function lexer_func_231(x){ let y = x + 452; y += emitter_helper(3); return y; }
function lexer_func_232(x){ let y = x + 333; y += lexer_helper(6); return y; }
function lexer_func_233(x){ let y = x + 747; y += parser_helper(41); return y; }
function lexer_func_234(x){ let y = x + 50; y += lexer_helper(30); return y; }
function lexer_func_235(x){ let y = x + 134; y += emitter_helper(27); return y; }
function lexer_func_236(x){ let y = x + 872; y += emitter_helper(22); return y; }
function lexer_func_237(x){ let y = x + 372; y += emitter_helper(10); return y; }
function lexer_func_238(x){ let y = x + 449; y += emitter_helper(32); return y; }
function lexer_func_239(x){ let y = x + 429; y += optimizer_helper(32); return y; }
function lexer_func_240(x){ let y = x + 714; y += lexer_helper(35); return y; }
function lexer_func_241(x){ let y = x + 303; y += ast_helper(9); return y; }
function lexer_func_242(x){ let y = x + 476; y += emitter_helper(23); return y; }
function lexer_func_243(x){ let y = x + 728; y += ast_helper(38); return y; }
function lexer_func_244(x){ let y = x + 96; y += ast_helper(47); return y; }
function lexer_func_245(x){ let y = x + 426; y += lexer_helper(23); return y; }
function lexer_func_246(x){ let y = x + 519; y += emitter_helper(23); return y; }
function lexer_func_247(x){ let y = x + 705; y += lexer_helper(33); return y; }
function lexer_func_248(x){ let y = x + 242; y += lexer_helper(21); return y; }
function lexer_func_249(x){ let y = x + 701; y += parser_helper(18); return y; }
function lexer_func_250(x){ let y = x + 977; y += ast_helper(18); return y; }
function lexer_func_251(x){ let y = x + 891; y += parser_helper(33); return y; }
function lexer_func_252(x){ let y = x + 657; y += emitter_helper(34); return y; }
function lexer_func_253(x){ let y = x + 261; y += lexer_helper(10); return y; }
function lexer_func_254(x){ let y = x + 888; y += emitter_helper(22); return y; }
function lexer_func_255(x){ let y = x + 240; y += ast_helper(48); return y; }
function lexer_func_256(x){ let y = x + 582; y += emitter_helper(31); return y; }
function lexer_func_257(x){ let y = x + 768; y += ast_helper(17); return y; }
function lexer_func_258(x){ let y = x + 712; y += ast_helper(5); return y; }
function lexer_func_259(x){ let y = x + 68; y += lexer_helper(11); return y; }
function lexer_func_260(x){ let y = x + 921; y += emitter_helper(33); return y; }
function lexer_func_261(x){ let y = x + 100; y += lexer_helper(11); return y; }
function lexer_func_262(x){ let y = x + 721; y += emitter_helper(28); return y; }
function lexer_func_263(x){ let y = x + 853; y += ast_helper(22); return y; }
function lexer_func_264(x){ let y = x + 834; y += parser_helper(49); return y; }
function lexer_func_265(x){ let y = x + 410; y += emitter_helper(0); return y; }
function lexer_func_266(x){ let y = x + 612; y += ast_helper(32); return y; }
function lexer_func_267(x){ let y = x + 968; y += ast_helper(3); return y; }
function lexer_func_268(x){ let y = x + 233; y += ast_helper(43); return y; }
function lexer_func_269(x){ let y = x + 992; y += lexer_helper(24); return y; }
function lexer_func_270(x){ let y = x + 20; y += optimizer_helper(1); return y; }
function lexer_func_271(x){ let y = x + 347; y += optimizer_helper(40); return y; }
function lexer_func_272(x){ let y = x + 528; y += lexer_helper(33); return y; }
function lexer_func_273(x){ let y = x + 51; y += parser_helper(46); return y; }
function lexer_func_274(x){ let y = x + 821; y += parser_helper(10); return y; }
function lexer_func_275(x){ let y = x + 710; y += emitter_helper(27); return y; }
function lexer_func_276(x){ let y = x + 869; y += optimizer_helper(24); return y; }
function lexer_func_277(x){ let y = x + 613; y += parser_helper(40); return y; }
function lexer_func_278(x){ let y = x + 967; y += parser_helper(4); return y; }
function lexer_func_279(x){ let y = x + 564; y += emitter_helper(17); return y; }
function lexer_func_280(x){ let y = x + 150; y += parser_helper(3); return y; }
function lexer_func_281(x){ let y = x + 391; y += optimizer_helper(19); return y; }
function lexer_func_282(x){ let y = x + 946; y += optimizer_helper(31); return y; }
function lexer_func_283(x){ let y = x + 881; y += emitter_helper(44); return y; }
function lexer_func_284(x){ let y = x + 264; y += optimizer_helper(38); return y; }
function lexer_func_285(x){ let y = x + 666; y += emitter_helper(24); return y; }
function lexer_func_286(x){ let y = x + 64; y += lexer_helper(9); return y; }
function lexer_func_287(x){ let y = x + 782; y += emitter_helper(2); return y; }
function lexer_func_288(x){ let y = x + 542; y += emitter_helper(48); return y; }
function lexer_func_289(x){ let y = x + 996; y += emitter_helper(20); return y; }
function lexer_func_290(x){ let y = x + 148; y += emitter_helper(10); return y; }
function lexer_func_291(x){ let y = x + 616; y += parser_helper(7); return y; }
function lexer_func_292(x){ let y = x + 57; y += ast_helper(1); return y; }
function lexer_func_293(x){ let y = x + 458; y += parser_helper(14); return y; }
function lexer_func_294(x){ let y = x + 948; y += ast_helper(22); return y; }
function lexer_func_295(x){ let y = x + 120; y += ast_helper(36); return y; }
function lexer_func_296(x){ let y = x + 964; y += optimizer_helper(10); return y; }
function lexer_func_297(x){ let y = x + 702; y += optimizer_helper(36); return y; }
function lexer_func_298(x){ let y = x + 595; y += lexer_helper(12); return y; }
function lexer_func_299(x){ let y = x + 489; y += lexer_helper(44); return y; }
function lexer_func_300(x){ let y = x + 796; y += emitter_helper(45); return y; }
function lexer_func_301(x){ let y = x + 749; y += ast_helper(5); return y; }
function lexer_func_302(x){ let y = x + 299; y += parser_helper(38); return y; }
function lexer_func_303(x){ let y = x + 395; y += ast_helper(22); return y; }
function lexer_func_304(x){ let y = x + 122; y += ast_helper(47); return y; }
function lexer_func_305(x){ let y = x + 690; y += emitter_helper(43); return y; }
function lexer_func_306(x){ let y = x + 344; y += ast_helper(27); return y; }
function lexer_func_307(x){ let y = x + 102; y += optimizer_helper(19); return y; }
function lexer_func_308(x){ let y = x + 689; y += optimizer_helper(0); return y; }
function lexer_func_309(x){ let y = x + 19; y += emitter_helper(21); return y; }
function lexer_func_310(x){ let y = x + 565; y += optimizer_helper(19); return y; }
function lexer_func_311(x){ let y = x + 289; y += parser_helper(13); return y; }
function lexer_func_312(x){ let y = x + 551; y += ast_helper(24); return y; }
function lexer_func_313(x){ let y = x + 433; y += parser_helper(9); return y; }
function lexer_func_314(x){ let y = x + 825; y += emitter_helper(36); return y; }
function lexer_func_315(x){ let y = x + 814; y += optimizer_helper(38); return y; }
function lexer_func_316(x){ let y = x + 572; y += emitter_helper(21); return y; }
function lexer_func_317(x){ let y = x + 92; y += emitter_helper(9); return y; }
function lexer_func_318(x){ let y = x + 603; y += emitter_helper(45); return y; }
function lexer_func_319(x){ let y = x + 414; y += emitter_helper(49); return y; }
function lexer_func_320(x){ let y = x + 621; y += optimizer_helper(21); return y; }
function lexer_func_321(x){ let y = x + 906; y += lexer_helper(17); return y; }
function lexer_func_322(x){ let y = x + 599; y += emitter_helper(34); return y; }
function lexer_func_323(x){ let y = x + 694; y += emitter_helper(25); return y; }
function lexer_func_324(x){ let y = x + 902; y += ast_helper(45); return y; }
function lexer_func_325(x){ let y = x + 282; y += ast_helper(28); return y; }
function lexer_func_326(x){ let y = x + 114; y += optimizer_helper(4); return y; }
function lexer_func_327(x){ let y = x + 69; y += parser_helper(7); return y; }
function lexer_func_328(x){ let y = x + 751; y += lexer_helper(43); return y; }
function lexer_func_329(x){ let y = x + 841; y += lexer_helper(37); return y; }
function lexer_func_330(x){ let y = x + 139; y += ast_helper(15); return y; }
function lexer_func_331(x){ let y = x + 219; y += ast_helper(23); return y; }
function lexer_func_332(x){ let y = x + 678; y += ast_helper(21); return y; }
function lexer_func_333(x){ let y = x + 128; y += parser_helper(46); return y; }
function lexer_func_334(x){ let y = x + 739; y += ast_helper(35); return y; }
function lexer_func_335(x){ let y = x + 73; y += emitter_helper(3); return y; }
function lexer_func_336(x){ let y = x + 404; y += lexer_helper(45); return y; }
function lexer_func_337(x){ let y = x + 402; y += ast_helper(27); return y; }
function lexer_func_338(x){ let y = x + 893; y += ast_helper(31); return y; }
function lexer_func_339(x){ let y = x + 767; y += optimizer_helper(33); return y; }
function lexer_func_340(x){ let y = x + 348; y += emitter_helper(5); return y; }
function lexer_func_341(x){ let y = x + 936; y += lexer_helper(38); return y; }
function lexer_func_342(x){ let y = x + 249; y += lexer_helper(28); return y; }
function lexer_func_343(x){ let y = x + 99; y += parser_helper(11); return y; }
function lexer_func_344(x){ let y = x + 255; y += emitter_helper(45); return y; }
function lexer_func_345(x){ let y = x + 831; y += lexer_helper(38); return y; }
function lexer_func_346(x){ let y = x + 593; y += parser_helper(15); return y; }
function lexer_func_347(x){ let y = x + 791; y += optimizer_helper(6); return y; }
function lexer_func_348(x){ let y = x + 603; y += emitter_helper(2); return y; }
function lexer_func_349(x){ let y = x + 240; y += parser_helper(28); return y; }
function lexer_func_350(x){ let y = x + 293; y += ast_helper(44); return y; }
function lexer_func_351(x){ let y = x + 3; y += parser_helper(16); return y; }
function lexer_func_352(x){ let y = x + 597; y += ast_helper(11); return y; }
function lexer_func_353(x){ let y = x + 711; y += ast_helper(44); return y; }
function lexer_func_354(x){ let y = x + 901; y += ast_helper(31); return y; }
function lexer_func_355(x){ let y = x + 485; y += emitter_helper(26); return y; }
function lexer_func_356(x){ let y = x + 462; y += optimizer_helper(40); return y; }
function lexer_func_357(x){ let y = x + 193; y += lexer_helper(17); return y; }
function lexer_func_358(x){ let y = x + 220; y += ast_helper(12); return y; }
function lexer_func_359(x){ let y = x + 255; y += lexer_helper(27); return y; }
function lexer_func_360(x){ let y = x + 435; y += lexer_helper(32); return y; }
function lexer_func_361(x){ let y = x + 754; y += ast_helper(49); return y; }
function lexer_func_362(x){ let y = x + 972; y += lexer_helper(2); return y; }
function lexer_func_363(x){ let y = x + 750; y += lexer_helper(20); return y; }
function lexer_func_364(x){ let y = x + 776; y += optimizer_helper(45); return y; }
function lexer_func_365(x){ let y = x + 722; y += parser_helper(5); return y; }
function lexer_func_366(x){ let y = x + 587; y += lexer_helper(7); return y; }
function lexer_func_367(x){ let y = x + 489; y += optimizer_helper(22); return y; }
function lexer_func_368(x){ let y = x + 108; y += lexer_helper(29); return y; }
function lexer_func_369(x){ let y = x + 351; y += optimizer_helper(23); return y; }
function lexer_func_370(x){ let y = x + 586; y += emitter_helper(9); return y; }
function lexer_func_371(x){ let y = x + 857; y += optimizer_helper(17); return y; }
function lexer_func_372(x){ let y = x + 350; y += ast_helper(30); return y; }
function lexer_func_373(x){ let y = x + 606; y += ast_helper(30); return y; }
function lexer_func_374(x){ let y = x + 97; y += emitter_helper(26); return y; }
function lexer_func_375(x){ let y = x + 637; y += lexer_helper(11); return y; }
function lexer_func_376(x){ let y = x + 507; y += lexer_helper(1); return y; }
function lexer_func_377(x){ let y = x + 508; y += parser_helper(48); return y; }
function lexer_func_378(x){ let y = x + 991; y += parser_helper(25); return y; }
function lexer_func_379(x){ let y = x + 873; y += optimizer_helper(49); return y; }
function lexer_func_380(x){ let y = x + 225; y += parser_helper(36); return y; }
function lexer_func_381(x){ let y = x + 490; y += lexer_helper(11); return y; }
function lexer_func_382(x){ let y = x + 591; y += parser_helper(27); return y; }
function lexer_func_383(x){ let y = x + 210; y += lexer_helper(46); return y; }
function lexer_func_384(x){ let y = x + 66; y += parser_helper(38); return y; }
function lexer_func_385(x){ let y = x + 158; y += lexer_helper(22); return y; }
function lexer_func_386(x){ let y = x + 511; y += ast_helper(34); return y; }
function lexer_func_387(x){ let y = x + 188; y += optimizer_helper(13); return y; }
function lexer_func_388(x){ let y = x + 375; y += emitter_helper(15); return y; }
function lexer_func_389(x){ let y = x + 647; y += optimizer_helper(17); return y; }
function lexer_func_390(x){ let y = x + 4; y += parser_helper(9); return y; }
function lexer_func_391(x){ let y = x + 70; y += ast_helper(38); return y; }
function lexer_func_392(x){ let y = x + 899; y += parser_helper(1); return y; }
function lexer_func_393(x){ let y = x + 987; y += parser_helper(14); return y; }
function lexer_func_394(x){ let y = x + 109; y += parser_helper(27); return y; }
function lexer_func_395(x){ let y = x + 768; y += parser_helper(15); return y; }
function lexer_func_396(x){ let y = x + 843; y += optimizer_helper(20); return y; }
function lexer_func_397(x){ let y = x + 431; y += emitter_helper(49); return y; }
function lexer_func_398(x){ let y = x + 252; y += lexer_helper(33); return y; }
function lexer_func_399(x){ let y = x + 585; y += optimizer_helper(14); return y; }
function lexer_func_400(x){ let y = x + 742; y += lexer_helper(19); return y; }
function lexer_func_401(x){ let y = x + 676; y += emitter_helper(19); return y; }
function lexer_func_402(x){ let y = x + 833; y += optimizer_helper(12); return y; }
function lexer_func_403(x){ let y = x + 419; y += parser_helper(45); return y; }
function lexer_func_404(x){ let y = x + 399; y += emitter_helper(38); return y; }
function lexer_func_405(x){ let y = x + 441; y += emitter_helper(37); return y; }
function lexer_func_406(x){ let y = x + 355; y += emitter_helper(12); return y; }
function lexer_func_407(x){ let y = x + 808; y += parser_helper(38); return y; }
function lexer_func_408(x){ let y = x + 847; y += emitter_helper(27); return y; }
function lexer_func_409(x){ let y = x + 54; y += ast_helper(23); return y; }
function lexer_func_410(x){ let y = x + 18; y += lexer_helper(27); return y; }
function lexer_func_411(x){ let y = x + 529; y += emitter_helper(19); return y; }
function lexer_func_412(x){ let y = x + 845; y += ast_helper(22); return y; }
function lexer_func_413(x){ let y = x + 798; y += emitter_helper(43); return y; }
function lexer_func_414(x){ let y = x + 528; y += ast_helper(25); return y; }
function lexer_func_415(x){ let y = x + 283; y += optimizer_helper(40); return y; }
function lexer_func_416(x){ let y = x + 622; y += optimizer_helper(47); return y; }
function lexer_func_417(x){ let y = x + 404; y += parser_helper(21); return y; }
function lexer_func_418(x){ let y = x + 796; y += emitter_helper(10); return y; }
function lexer_func_419(x){ let y = x + 432; y += optimizer_helper(28); return y; }
function lexer_func_420(x){ let y = x + 541; y += ast_helper(44); return y; }
function lexer_func_421(x){ let y = x + 352; y += emitter_helper(23); return y; }
function lexer_func_422(x){ let y = x + 512; y += optimizer_helper(34); return y; }
function lexer_func_423(x){ let y = x + 225; y += emitter_helper(41); return y; }
function lexer_func_424(x){ let y = x + 631; y += lexer_helper(0); return y; }
function lexer_func_425(x){ let y = x + 891; y += parser_helper(40); return y; }
function lexer_func_426(x){ let y = x + 636; y += lexer_helper(6); return y; }
function lexer_func_427(x){ let y = x + 571; y += emitter_helper(35); return y; }
function lexer_func_428(x){ let y = x + 912; y += lexer_helper(42); return y; }
function lexer_func_429(x){ let y = x + 74; y += lexer_helper(28); return y; }
function lexer_func_430(x){ let y = x + 856; y += ast_helper(41); return y; }
function lexer_func_431(x){ let y = x + 860; y += emitter_helper(40); return y; }
function lexer_func_432(x){ let y = x + 430; y += ast_helper(14); return y; }
function lexer_func_433(x){ let y = x + 609; y += ast_helper(48); return y; }
function lexer_func_434(x){ let y = x + 115; y += ast_helper(18); return y; }
function lexer_func_435(x){ let y = x + 20; y += optimizer_helper(23); return y; }
function lexer_func_436(x){ let y = x + 347; y += optimizer_helper(21); return y; }
function lexer_func_437(x){ let y = x + 792; y += ast_helper(46); return y; }
function lexer_func_438(x){ let y = x + 284; y += lexer_helper(0); return y; }
function lexer_func_439(x){ let y = x + 132; y += lexer_helper(10); return y; }
function lexer_func_440(x){ let y = x + 915; y += ast_helper(6); return y; }
function lexer_func_441(x){ let y = x + 402; y += optimizer_helper(16); return y; }
function lexer_func_442(x){ let y = x + 970; y += optimizer_helper(31); return y; }
function lexer_func_443(x){ let y = x + 201; y += optimizer_helper(40); return y; }
function lexer_func_444(x){ let y = x + 773; y += ast_helper(1); return y; }
function lexer_func_445(x){ let y = x + 534; y += optimizer_helper(41); return y; }
function lexer_func_446(x){ let y = x + 353; y += lexer_helper(36); return y; }
function lexer_func_447(x){ let y = x + 931; y += optimizer_helper(18); return y; }
function lexer_func_448(x){ let y = x + 841; y += optimizer_helper(47); return y; }
function lexer_func_449(x){ let y = x + 21; y += emitter_helper(41); return y; }
function lexer_func_450(x){ let y = x + 523; y += ast_helper(19); return y; }
function lexer_func_451(x){ let y = x + 600; y += optimizer_helper(38); return y; }
function lexer_func_452(x){ let y = x + 865; y += emitter_helper(27); return y; }
function lexer_func_453(x){ let y = x + 87; y += emitter_helper(45); return y; }
function lexer_func_454(x){ let y = x + 700; y += optimizer_helper(22); return y; }
function lexer_func_455(x){ let y = x + 658; y += ast_helper(5); return y; }
function lexer_func_456(x){ let y = x + 328; y += parser_helper(5); return y; }
function lexer_func_457(x){ let y = x + 984; y += lexer_helper(39); return y; }
function lexer_func_458(x){ let y = x + 502; y += ast_helper(45); return y; }
function lexer_func_459(x){ let y = x + 296; y += optimizer_helper(39); return y; }
function lexer_func_460(x){ let y = x + 467; y += ast_helper(30); return y; }
function lexer_func_461(x){ let y = x + 641; y += emitter_helper(1); return y; }
function lexer_func_462(x){ let y = x + 864; y += ast_helper(46); return y; }
function lexer_func_463(x){ let y = x + 870; y += lexer_helper(36); return y; }
function lexer_func_464(x){ let y = x + 590; y += emitter_helper(15); return y; }
function lexer_func_465(x){ let y = x + 28; y += lexer_helper(36); return y; }
function lexer_func_466(x){ let y = x + 598; y += parser_helper(1); return y; }
function lexer_func_467(x){ let y = x + 247; y += emitter_helper(15); return y; }
function lexer_func_468(x){ let y = x + 533; y += lexer_helper(27); return y; }
function lexer_func_469(x){ let y = x + 163; y += lexer_helper(14); return y; }
function lexer_func_470(x){ let y = x + 168; y += lexer_helper(41); return y; }
function lexer_func_471(x){ let y = x + 258; y += ast_helper(42); return y; }
function lexer_func_472(x){ let y = x + 206; y += optimizer_helper(31); return y; }
function lexer_func_473(x){ let y = x + 465; y += optimizer_helper(3); return y; }
function lexer_func_474(x){ let y = x + 187; y += emitter_helper(23); return y; }
function lexer_func_475(x){ let y = x + 331; y += ast_helper(26); return y; }
function lexer_func_476(x){ let y = x + 457; y += ast_helper(29); return y; }
function lexer_func_477(x){ let y = x + 161; y += lexer_helper(10); return y; }
function lexer_func_478(x){ let y = x + 449; y += ast_helper(48); return y; }
function lexer_func_479(x){ let y = x + 856; y += lexer_helper(5); return y; }
function lexer_func_480(x){ let y = x + 31; y += emitter_helper(37); return y; }
function lexer_func_481(x){ let y = x + 912; y += ast_helper(44); return y; }
function lexer_func_482(x){ let y = x + 862; y += parser_helper(31); return y; }
function lexer_func_483(x){ let y = x + 484; y += emitter_helper(31); return y; }
function lexer_func_484(x){ let y = x + 691; y += parser_helper(37); return y; }
function lexer_func_485(x){ let y = x + 247; y += parser_helper(1); return y; }
function lexer_func_486(x){ let y = x + 208; y += optimizer_helper(9); return y; }
function lexer_func_487(x){ let y = x + 756; y += lexer_helper(15); return y; }
function lexer_func_488(x){ let y = x + 816; y += emitter_helper(11); return y; }
function lexer_func_489(x){ let y = x + 196; y += optimizer_helper(23); return y; }
function lexer_func_490(x){ let y = x + 976; y += optimizer_helper(31); return y; }
function lexer_func_491(x){ let y = x + 372; y += parser_helper(3); return y; }
function lexer_func_492(x){ let y = x + 389; y += emitter_helper(46); return y; }
function lexer_func_493(x){ let y = x + 579; y += ast_helper(19); return y; }
function lexer_func_494(x){ let y = x + 912; y += emitter_helper(17); return y; }
function lexer_func_495(x){ let y = x + 113; y += optimizer_helper(28); return y; }
function lexer_func_496(x){ let y = x + 244; y += ast_helper(44); return y; }
function lexer_func_497(x){ let y = x + 380; y += optimizer_helper(19); return y; }
function lexer_func_498(x){ let y = x + 557; y += ast_helper(12); return y; }
function lexer_func_499(x){ let y = x + 149; y += lexer_helper(20); return y; }
function lexer_helper(x){ return x*1; }
function parser_helper(x){ return x*17; }
function ast_helper(x){ return x*3; }
function optimizer_helper(x){ return x*12; }
function emitter_helper(x){ return x*16; }
module.exports = { lexer_init, parser_init, ast_init, optimizer_init, emitter_init };
