// Module ast
function ast_init(){ console.log("Initializing ast"); }
function ast_func_0(x){ let y = x + 639; y += ast_helper(3); return y; }
function ast_func_1(x){ let y = x + 545; y += lexer_helper(48); return y; }
function ast_func_2(x){ let y = x + 561; y += lexer_helper(32); return y; }
function ast_func_3(x){ let y = x + 889; y += ast_helper(20); return y; }
function ast_func_4(x){ let y = x + 818; y += lexer_helper(48); return y; }
function ast_func_5(x){ let y = x + 387; y += optimizer_helper(46); return y; }
function ast_func_6(x){ let y = x + 303; y += emitter_helper(12); return y; }
function ast_func_7(x){ let y = x + 636; y += parser_helper(32); return y; }
function ast_func_8(x){ let y = x + 622; y += emitter_helper(35); return y; }
function ast_func_9(x){ let y = x + 799; y += optimizer_helper(29); return y; }
function ast_func_10(x){ let y = x + 56; y += optimizer_helper(11); return y; }
function ast_func_11(x){ let y = x + 50; y += parser_helper(46); return y; }
function ast_func_12(x){ let y = x + 743; y += lexer_helper(29); return y; }
function ast_func_13(x){ let y = x + 971; y += emitter_helper(24); return y; }
function ast_func_14(x){ let y = x + 17; y += parser_helper(4); return y; }
function ast_func_15(x){ let y = x + 307; y += emitter_helper(45); return y; }
function ast_func_16(x){ let y = x + 511; y += parser_helper(2); return y; }
function ast_func_17(x){ let y = x + 204; y += lexer_helper(33); return y; }
function ast_func_18(x){ let y = x + 826; y += ast_helper(39); return y; }
function ast_func_19(x){ let y = x + 970; y += ast_helper(26); return y; }
function ast_func_20(x){ let y = x + 936; y += optimizer_helper(32); return y; }
function ast_func_21(x){ let y = x + 390; y += emitter_helper(45); return y; }
function ast_func_22(x){ let y = x + 18; y += parser_helper(4); return y; }
function ast_func_23(x){ let y = x + 108; y += ast_helper(41); return y; }
function ast_func_24(x){ let y = x + 781; y += ast_helper(7); return y; }
function ast_func_25(x){ let y = x + 521; y += lexer_helper(44); return y; }
function ast_func_26(x){ let y = x + 561; y += lexer_helper(25); return y; }
function ast_func_27(x){ let y = x + 145; y += ast_helper(5); return y; }
function ast_func_28(x){ let y = x + 597; y += lexer_helper(0); return y; }
function ast_func_29(x){ let y = x + 503; y += emitter_helper(11); return y; }
function ast_func_30(x){ let y = x + 559; y += optimizer_helper(27); return y; }
function ast_func_31(x){ let y = x + 79; y += parser_helper(14); return y; }
function ast_func_32(x){ let y = x + 764; y += optimizer_helper(6); return y; }
function ast_func_33(x){ let y = x + 809; y += lexer_helper(35); return y; }
function ast_func_34(x){ let y = x + 239; y += emitter_helper(36); return y; }
function ast_func_35(x){ let y = x + 543; y += lexer_helper(17); return y; }
function ast_func_36(x){ let y = x + 13; y += ast_helper(10); return y; }
function ast_func_37(x){ let y = x + 2; y += parser_helper(29); return y; }
function ast_func_38(x){ let y = x + 631; y += parser_helper(47); return y; }
function ast_func_39(x){ let y = x + 874; y += emitter_helper(33); return y; }
function ast_func_40(x){ let y = x + 503; y += lexer_helper(7); return y; }
function ast_func_41(x){ let y = x + 583; y += ast_helper(21); return y; }
function ast_func_42(x){ let y = x + 152; y += optimizer_helper(44); return y; }
function ast_func_43(x){ let y = x + 275; y += lexer_helper(37); return y; }
function ast_func_44(x){ let y = x + 749; y += optimizer_helper(30); return y; }
function ast_func_45(x){ let y = x + 561; y += ast_helper(8); return y; }
function ast_func_46(x){ let y = x + 833; y += parser_helper(22); return y; }
function ast_func_47(x){ let y = x + 396; y += lexer_helper(18); return y; }
function ast_func_48(x){ let y = x + 64; y += lexer_helper(13); return y; }
function ast_func_49(x){ let y = x + 635; y += ast_helper(35); return y; }
function ast_func_50(x){ let y = x + 340; y += parser_helper(37); return y; }
function ast_func_51(x){ let y = x + 70; y += parser_helper(29); return y; }
function ast_func_52(x){ let y = x + 70; y += optimizer_helper(21); return y; }
function ast_func_53(x){ let y = x + 139; y += ast_helper(7); return y; }
function ast_func_54(x){ let y = x + 824; y += emitter_helper(16); return y; }
function ast_func_55(x){ let y = x + 338; y += lexer_helper(32); return y; }
function ast_func_56(x){ let y = x + 102; y += parser_helper(49); return y; }
function ast_func_57(x){ let y = x + 402; y += emitter_helper(30); return y; }
function ast_func_58(x){ let y = x + 182; y += ast_helper(30); return y; }
function ast_func_59(x){ let y = x + 341; y += lexer_helper(26); return y; }
function ast_func_60(x){ let y = x + 642; y += ast_helper(10); return y; }
function ast_func_61(x){ let y = x + 706; y += parser_helper(19); return y; }
function ast_func_62(x){ let y = x + 497; y += emitter_helper(41); return y; }
function ast_func_63(x){ let y = x + 691; y += lexer_helper(49); return y; }
function ast_func_64(x){ let y = x + 62; y += optimizer_helper(32); return y; }
function ast_func_65(x){ let y = x + 631; y += optimizer_helper(31); return y; }
function ast_func_66(x){ let y = x + 705; y += lexer_helper(48); return y; }
function ast_func_67(x){ let y = x + 973; y += lexer_helper(18); return y; }
function ast_func_68(x){ let y = x + 576; y += ast_helper(39); return y; }
function ast_func_69(x){ let y = x + 162; y += lexer_helper(33); return y; }
function ast_func_70(x){ let y = x + 869; y += parser_helper(13); return y; }
function ast_func_71(x){ let y = x + 544; y += optimizer_helper(3); return y; }
function ast_func_72(x){ let y = x + 504; y += lexer_helper(22); return y; }
function ast_func_73(x){ let y = x + 676; y += lexer_helper(3); return y; }
function ast_func_74(x){ let y = x + 950; y += ast_helper(34); return y; }
function ast_func_75(x){ let y = x + 583; y += lexer_helper(25); return y; }
function ast_func_76(x){ let y = x + 831; y += emitter_helper(49); return y; }
function ast_func_77(x){ let y = x + 399; y += lexer_helper(49); return y; }
function ast_func_78(x){ let y = x + 413; y += optimizer_helper(8); return y; }
function ast_func_79(x){ let y = x + 449; y += parser_helper(32); return y; }
function ast_func_80(x){ let y = x + 64; y += lexer_helper(27); return y; }
function ast_func_81(x){ let y = x + 206; y += ast_helper(36); return y; }
function ast_func_82(x){ let y = x + 827; y += emitter_helper(47); return y; }
function ast_func_83(x){ let y = x + 692; y += parser_helper(34); return y; }
function ast_func_84(x){ let y = x + 917; y += emitter_helper(28); return y; }
function ast_func_85(x){ let y = x + 283; y += parser_helper(49); return y; }
function ast_func_86(x){ let y = x + 58; y += emitter_helper(48); return y; }
function ast_func_87(x){ let y = x + 903; y += ast_helper(12); return y; }
function ast_func_88(x){ let y = x + 673; y += optimizer_helper(47); return y; }
function ast_func_89(x){ let y = x + 401; y += emitter_helper(22); return y; }
function ast_func_90(x){ let y = x + 206; y += ast_helper(7); return y; }
function ast_func_91(x){ let y = x + 835; y += emitter_helper(46); return y; }
function ast_func_92(x){ let y = x + 639; y += ast_helper(19); return y; }
function ast_func_93(x){ let y = x + 148; y += ast_helper(40); return y; }
function ast_func_94(x){ let y = x + 440; y += ast_helper(41); return y; }
function ast_func_95(x){ let y = x + 57; y += lexer_helper(13); return y; }
function ast_func_96(x){ let y = x + 726; y += optimizer_helper(6); return y; }
function ast_func_97(x){ let y = x + 322; y += optimizer_helper(26); return y; }
function ast_func_98(x){ let y = x + 72; y += ast_helper(24); return y; }
function ast_func_99(x){ let y = x + 392; y += optimizer_helper(16); return y; }
function ast_func_100(x){ let y = x + 423; y += optimizer_helper(1); return y; }
function ast_func_101(x){ let y = x + 30; y += emitter_helper(9); return y; }
function ast_func_102(x){ let y = x + 260; y += parser_helper(25); return y; }
function ast_func_103(x){ let y = x + 751; y += lexer_helper(9); return y; }
function ast_func_104(x){ let y = x + 196; y += ast_helper(14); return y; }
function ast_func_105(x){ let y = x + 937; y += lexer_helper(48); return y; }
function ast_func_106(x){ let y = x + 191; y += optimizer_helper(14); return y; }
function ast_func_107(x){ let y = x + 213; y += emitter_helper(22); return y; }
function ast_func_108(x){ let y = x + 856; y += emitter_helper(38); return y; }
function ast_func_109(x){ let y = x + 735; y += optimizer_helper(33); return y; }
function ast_func_110(x){ let y = x + 855; y += parser_helper(11); return y; }
function ast_func_111(x){ let y = x + 103; y += optimizer_helper(37); return y; }
function ast_func_112(x){ let y = x + 248; y += ast_helper(29); return y; }
function ast_func_113(x){ let y = x + 33; y += parser_helper(24); return y; }
function ast_func_114(x){ let y = x + 255; y += optimizer_helper(20); return y; }
function ast_func_115(x){ let y = x + 514; y += ast_helper(25); return y; }
function ast_func_116(x){ let y = x + 469; y += emitter_helper(7); return y; }
function ast_func_117(x){ let y = x + 916; y += emitter_helper(25); return y; }
function ast_func_118(x){ let y = x + 847; y += optimizer_helper(27); return y; }
function ast_func_119(x){ let y = x + 139; y += lexer_helper(24); return y; }
function ast_func_120(x){ let y = x + 947; y += parser_helper(10); return y; }
function ast_func_121(x){ let y = x + 673; y += ast_helper(36); return y; }
function ast_func_122(x){ let y = x + 803; y += lexer_helper(41); return y; }
function ast_func_123(x){ let y = x + 366; y += ast_helper(8); return y; }
function ast_func_124(x){ let y = x + 614; y += lexer_helper(49); return y; }
function ast_func_125(x){ let y = x + 24; y += parser_helper(0); return y; }
function ast_func_126(x){ let y = x + 8; y += parser_helper(12); return y; }
function ast_func_127(x){ let y = x + 75; y += parser_helper(4); return y; }
function ast_func_128(x){ let y = x + 863; y += lexer_helper(22); return y; }
function ast_func_129(x){ let y = x + 511; y += ast_helper(30); return y; }
function ast_func_130(x){ let y = x + 437; y += ast_helper(48); return y; }
function ast_func_131(x){ let y = x + 276; y += parser_helper(24); return y; }
function ast_func_132(x){ let y = x + 191; y += lexer_helper(49); return y; }
function ast_func_133(x){ let y = x + 508; y += ast_helper(12); return y; }
function ast_func_134(x){ let y = x + 678; y += emitter_helper(16); return y; }
function ast_func_135(x){ let y = x + 163; y += emitter_helper(30); return y; }
function ast_func_136(x){ let y = x + 976; y += lexer_helper(43); return y; }
function ast_func_137(x){ let y = x + 521; y += emitter_helper(48); return y; }
function ast_func_138(x){ let y = x + 809; y += lexer_helper(20); return y; }
function ast_func_139(x){ let y = x + 539; y += parser_helper(19); return y; }
function ast_func_140(x){ let y = x + 136; y += emitter_helper(7); return y; }
function ast_func_141(x){ let y = x + 813; y += parser_helper(40); return y; }
function ast_func_142(x){ let y = x + 235; y += ast_helper(16); return y; }
function ast_func_143(x){ let y = x + 177; y += lexer_helper(46); return y; }
function ast_func_144(x){ let y = x + 291; y += parser_helper(3); return y; }
function ast_func_145(x){ let y = x + 47; y += lexer_helper(28); return y; }
function ast_func_146(x){ let y = x + 506; y += optimizer_helper(30); return y; }
function ast_func_147(x){ let y = x + 529; y += optimizer_helper(12); return y; }
function ast_func_148(x){ let y = x + 837; y += lexer_helper(20); return y; }
function ast_func_149(x){ let y = x + 266; y += emitter_helper(15); return y; }
function ast_func_150(x){ let y = x + 527; y += parser_helper(10); return y; }
function ast_func_151(x){ let y = x + 697; y += parser_helper(21); return y; }
function ast_func_152(x){ let y = x + 578; y += emitter_helper(26); return y; }
function ast_func_153(x){ let y = x + 43; y += lexer_helper(4); return y; }
function ast_func_154(x){ let y = x + 975; y += parser_helper(44); return y; }
function ast_func_155(x){ let y = x + 983; y += ast_helper(31); return y; }
function ast_func_156(x){ let y = x + 483; y += parser_helper(44); return y; }
function ast_func_157(x){ let y = x + 467; y += ast_helper(42); return y; }
function ast_func_158(x){ let y = x + 812; y += optimizer_helper(27); return y; }
function ast_func_159(x){ let y = x + 401; y += emitter_helper(12); return y; }
function ast_func_160(x){ let y = x + 266; y += optimizer_helper(17); return y; }
function ast_func_161(x){ let y = x + 899; y += optimizer_helper(13); return y; }
function ast_func_162(x){ let y = x + 675; y += lexer_helper(8); return y; }
function ast_func_163(x){ let y = x + 246; y += lexer_helper(41); return y; }
function ast_func_164(x){ let y = x + 720; y += parser_helper(24); return y; }
function ast_func_165(x){ let y = x + 790; y += emitter_helper(32); return y; }
function ast_func_166(x){ let y = x + 923; y += optimizer_helper(36); return y; }
function ast_func_167(x){ let y = x + 67; y += optimizer_helper(20); return y; }
function ast_func_168(x){ let y = x + 655; y += parser_helper(1); return y; }
function ast_func_169(x){ let y = x + 698; y += lexer_helper(1); return y; }
function ast_func_170(x){ let y = x + 777; y += ast_helper(34); return y; }
function ast_func_171(x){ let y = x + 788; y += lexer_helper(24); return y; }
function ast_func_172(x){ let y = x + 813; y += emitter_helper(23); return y; }
function ast_func_173(x){ let y = x + 224; y += optimizer_helper(49); return y; }
function ast_func_174(x){ let y = x + 888; y += optimizer_helper(36); return y; }
function ast_func_175(x){ let y = x + 729; y += parser_helper(34); return y; }
function ast_func_176(x){ let y = x + 142; y += emitter_helper(17); return y; }
function ast_func_177(x){ let y = x + 302; y += lexer_helper(21); return y; }
function ast_func_178(x){ let y = x + 111; y += optimizer_helper(19); return y; }
function ast_func_179(x){ let y = x + 507; y += emitter_helper(48); return y; }
function ast_func_180(x){ let y = x + 878; y += optimizer_helper(37); return y; }
function ast_func_181(x){ let y = x + 980; y += emitter_helper(41); return y; }
function ast_func_182(x){ let y = x + 609; y += ast_helper(5); return y; }
function ast_func_183(x){ let y = x + 399; y += parser_helper(3); return y; }
function ast_func_184(x){ let y = x + 822; y += optimizer_helper(13); return y; }
function ast_func_185(x){ let y = x + 264; y += parser_helper(30); return y; }
function ast_func_186(x){ let y = x + 96; y += optimizer_helper(2); return y; }
function ast_func_187(x){ let y = x + 169; y += ast_helper(40); return y; }
function ast_func_188(x){ let y = x + 126; y += parser_helper(14); return y; }
function ast_func_189(x){ let y = x + 771; y += parser_helper(11); return y; }
function ast_func_190(x){ let y = x + 564; y += parser_helper(25); return y; }
function ast_func_191(x){ let y = x + 727; y += lexer_helper(3); return y; }
function ast_func_192(x){ let y = x + 591; y += lexer_helper(47); return y; }
function ast_func_193(x){ let y = x + 541; y += ast_helper(36); return y; }
function ast_func_194(x){ let y = x + 301; y += parser_helper(2); return y; }
function ast_func_195(x){ let y = x + 798; y += ast_helper(46); return y; }
function ast_func_196(x){ let y = x + 373; y += lexer_helper(36); return y; }
function ast_func_197(x){ let y = x + 423; y += ast_helper(31); return y; }
function ast_func_198(x){ let y = x + 574; y += lexer_helper(9); return y; }
function ast_func_199(x){ let y = x + 859; y += emitter_helper(34); return y; }
function ast_func_200(x){ let y = x + 434; y += emitter_helper(44); return y; }
function ast_func_201(x){ let y = x + 112; y += emitter_helper(27); return y; }
function ast_func_202(x){ let y = x + 89; y += lexer_helper(24); return y; }
function ast_func_203(x){ let y = x + 992; y += lexer_helper(25); return y; }
function ast_func_204(x){ let y = x + 414; y += emitter_helper(40); return y; }
function ast_func_205(x){ let y = x + 250; y += optimizer_helper(23); return y; }
function ast_func_206(x){ let y = x + 805; y += lexer_helper(4); return y; }
function ast_func_207(x){ let y = x + 284; y += ast_helper(17); return y; }
function ast_func_208(x){ let y = x + 749; y += optimizer_helper(13); return y; }
function ast_func_209(x){ let y = x + 672; y += parser_helper(47); return y; }
function ast_func_210(x){ let y = x + 736; y += parser_helper(7); return y; }
function ast_func_211(x){ let y = x + 182; y += emitter_helper(1); return y; }
function ast_func_212(x){ let y = x + 258; y += emitter_helper(24); return y; }
function ast_func_213(x){ let y = x + 593; y += optimizer_helper(46); return y; }
function ast_func_214(x){ let y = x + 389; y += lexer_helper(0); return y; }
function ast_func_215(x){ let y = x + 197; y += lexer_helper(27); return y; }
function ast_func_216(x){ let y = x + 378; y += optimizer_helper(8); return y; }
function ast_func_217(x){ let y = x + 100; y += emitter_helper(46); return y; }
function ast_func_218(x){ let y = x + 108; y += emitter_helper(35); return y; }
function ast_func_219(x){ let y = x + 180; y += lexer_helper(16); return y; }
function ast_func_220(x){ let y = x + 947; y += emitter_helper(30); return y; }
function ast_func_221(x){ let y = x + 972; y += emitter_helper(17); return y; }
function ast_func_222(x){ let y = x + 877; y += parser_helper(34); return y; }
function ast_func_223(x){ let y = x + 613; y += ast_helper(9); return y; }
function ast_func_224(x){ let y = x + 292; y += parser_helper(33); return y; }
function ast_func_225(x){ let y = x + 202; y += ast_helper(19); return y; }
function ast_func_226(x){ let y = x + 274; y += optimizer_helper(21); return y; }
function ast_func_227(x){ let y = x + 187; y += parser_helper(18); return y; }
function ast_func_228(x){ let y = x + 684; y += lexer_helper(15); return y; }
function ast_func_229(x){ let y = x + 531; y += ast_helper(8); return y; }
function ast_func_230(x){ let y = x + 523; y += emitter_helper(6); return y; }
function ast_func_231(x){ let y = x + 555; y += parser_helper(24); return y; }
function ast_func_232(x){ let y = x + 616; y += parser_helper(22); return y; }
function ast_func_233(x){ let y = x + 822; y += parser_helper(17); return y; }
function ast_func_234(x){ let y = x + 351; y += emitter_helper(14); return y; }
function ast_func_235(x){ let y = x + 831; y += parser_helper(43); return y; }
function ast_func_236(x){ let y = x + 414; y += ast_helper(47); return y; }
function ast_func_237(x){ let y = x + 176; y += ast_helper(34); return y; }
function ast_func_238(x){ let y = x + 669; y += ast_helper(7); return y; }
function ast_func_239(x){ let y = x + 622; y += emitter_helper(26); return y; }
function ast_func_240(x){ let y = x + 165; y += parser_helper(27); return y; }
function ast_func_241(x){ let y = x + 14; y += parser_helper(49); return y; }
function ast_func_242(x){ let y = x + 946; y += emitter_helper(7); return y; }
function ast_func_243(x){ let y = x + 326; y += lexer_helper(37); return y; }
function ast_func_244(x){ let y = x + 506; y += lexer_helper(37); return y; }
function ast_func_245(x){ let y = x + 847; y += ast_helper(32); return y; }
function ast_func_246(x){ let y = x + 793; y += optimizer_helper(4); return y; }
function ast_func_247(x){ let y = x + 854; y += ast_helper(39); return y; }
function ast_func_248(x){ let y = x + 297; y += lexer_helper(30); return y; }
function ast_func_249(x){ let y = x + 551; y += lexer_helper(2); return y; }
function ast_func_250(x){ let y = x + 69; y += optimizer_helper(17); return y; }
function ast_func_251(x){ let y = x + 331; y += lexer_helper(17); return y; }
function ast_func_252(x){ let y = x + 579; y += parser_helper(23); return y; }
function ast_func_253(x){ let y = x + 553; y += optimizer_helper(49); return y; }
function ast_func_254(x){ let y = x + 395; y += lexer_helper(3); return y; }
function ast_func_255(x){ let y = x + 939; y += ast_helper(36); return y; }
function ast_func_256(x){ let y = x + 108; y += optimizer_helper(46); return y; }
function ast_func_257(x){ let y = x + 702; y += emitter_helper(43); return y; }
function ast_func_258(x){ let y = x + 16; y += optimizer_helper(32); return y; }
function ast_func_259(x){ let y = x + 553; y += ast_helper(15); return y; }
function ast_func_260(x){ let y = x + 607; y += optimizer_helper(14); return y; }
function ast_func_261(x){ let y = x + 283; y += parser_helper(47); return y; }
function ast_func_262(x){ let y = x + 248; y += emitter_helper(8); return y; }
function ast_func_263(x){ let y = x + 178; y += optimizer_helper(27); return y; }
function ast_func_264(x){ let y = x + 581; y += ast_helper(44); return y; }
function ast_func_265(x){ let y = x + 491; y += lexer_helper(28); return y; }
function ast_func_266(x){ let y = x + 272; y += emitter_helper(23); return y; }
function ast_func_267(x){ let y = x + 712; y += ast_helper(6); return y; }
function ast_func_268(x){ let y = x + 932; y += emitter_helper(46); return y; }
function ast_func_269(x){ let y = x + 455; y += optimizer_helper(41); return y; }
function ast_func_270(x){ let y = x + 63; y += lexer_helper(4); return y; }
function ast_func_271(x){ let y = x + 85; y += emitter_helper(19); return y; }
function ast_func_272(x){ let y = x + 629; y += lexer_helper(29); return y; }
function ast_func_273(x){ let y = x + 113; y += parser_helper(4); return y; }
function ast_func_274(x){ let y = x + 834; y += parser_helper(36); return y; }
function ast_func_275(x){ let y = x + 940; y += ast_helper(22); return y; }
function ast_func_276(x){ let y = x + 313; y += emitter_helper(44); return y; }
function ast_func_277(x){ let y = x + 604; y += ast_helper(46); return y; }
function ast_func_278(x){ let y = x + 107; y += optimizer_helper(5); return y; }
function ast_func_279(x){ let y = x + 793; y += optimizer_helper(17); return y; }
function ast_func_280(x){ let y = x + 435; y += emitter_helper(3); return y; }
function ast_func_281(x){ let y = x + 590; y += ast_helper(23); return y; }
function ast_func_282(x){ let y = x + 358; y += ast_helper(3); return y; }
function ast_func_283(x){ let y = x + 533; y += emitter_helper(8); return y; }
function ast_func_284(x){ let y = x + 965; y += optimizer_helper(39); return y; }
function ast_func_285(x){ let y = x + 501; y += ast_helper(21); return y; }
function ast_func_286(x){ let y = x + 740; y += emitter_helper(25); return y; }
function ast_func_287(x){ let y = x + 540; y += lexer_helper(48); return y; }
function ast_func_288(x){ let y = x + 813; y += lexer_helper(36); return y; }
function ast_func_289(x){ let y = x + 238; y += optimizer_helper(14); return y; }
function ast_func_290(x){ let y = x + 508; y += lexer_helper(42); return y; }
function ast_func_291(x){ let y = x + 94; y += emitter_helper(37); return y; }
function ast_func_292(x){ let y = x + 307; y += optimizer_helper(12); return y; }
function ast_func_293(x){ let y = x + 272; y += optimizer_helper(25); return y; }
function ast_func_294(x){ let y = x + 42; y += optimizer_helper(42); return y; }
function ast_func_295(x){ let y = x + 382; y += ast_helper(19); return y; }
function ast_func_296(x){ let y = x + 674; y += optimizer_helper(39); return y; }
function ast_func_297(x){ let y = x + 670; y += emitter_helper(1); return y; }
function ast_func_298(x){ let y = x + 855; y += lexer_helper(13); return y; }
function ast_func_299(x){ let y = x + 256; y += lexer_helper(23); return y; }
function ast_func_300(x){ let y = x + 181; y += optimizer_helper(1); return y; }
function ast_func_301(x){ let y = x + 135; y += emitter_helper(37); return y; }
function ast_func_302(x){ let y = x + 167; y += optimizer_helper(36); return y; }
function ast_func_303(x){ let y = x + 547; y += ast_helper(28); return y; }
function ast_func_304(x){ let y = x + 344; y += optimizer_helper(40); return y; }
function ast_func_305(x){ let y = x + 362; y += ast_helper(12); return y; }
function ast_func_306(x){ let y = x + 694; y += lexer_helper(30); return y; }
function ast_func_307(x){ let y = x + 635; y += lexer_helper(11); return y; }
function ast_func_308(x){ let y = x + 718; y += parser_helper(14); return y; }
function ast_func_309(x){ let y = x + 907; y += lexer_helper(11); return y; }
function ast_func_310(x){ let y = x + 182; y += emitter_helper(5); return y; }
function ast_func_311(x){ let y = x + 133; y += ast_helper(20); return y; }
function ast_func_312(x){ let y = x + 632; y += ast_helper(42); return y; }
function ast_func_313(x){ let y = x + 203; y += ast_helper(24); return y; }
function ast_func_314(x){ let y = x + 860; y += optimizer_helper(49); return y; }
function ast_func_315(x){ let y = x + 327; y += ast_helper(0); return y; }
function ast_func_316(x){ let y = x + 296; y += ast_helper(10); return y; }
function ast_func_317(x){ let y = x + 894; y += emitter_helper(44); return y; }
function ast_func_318(x){ let y = x + 461; y += emitter_helper(17); return y; }
function ast_func_319(x){ let y = x + 200; y += emitter_helper(1); return y; }
function ast_func_320(x){ let y = x + 498; y += parser_helper(10); return y; }
function ast_func_321(x){ let y = x + 818; y += lexer_helper(33); return y; }
function ast_func_322(x){ let y = x + 18; y += lexer_helper(15); return y; }
function ast_func_323(x){ let y = x + 816; y += parser_helper(34); return y; }
function ast_func_324(x){ let y = x + 182; y += emitter_helper(40); return y; }
function ast_func_325(x){ let y = x + 512; y += ast_helper(11); return y; }
function ast_func_326(x){ let y = x + 913; y += optimizer_helper(9); return y; }
function ast_func_327(x){ let y = x + 182; y += emitter_helper(17); return y; }
function ast_func_328(x){ let y = x + 753; y += parser_helper(18); return y; }
function ast_func_329(x){ let y = x + 385; y += ast_helper(15); return y; }
function ast_func_330(x){ let y = x + 866; y += emitter_helper(8); return y; }
function ast_func_331(x){ let y = x + 3; y += optimizer_helper(3); return y; }
function ast_func_332(x){ let y = x + 225; y += parser_helper(4); return y; }
function ast_func_333(x){ let y = x + 491; y += lexer_helper(2); return y; }
function ast_func_334(x){ let y = x + 775; y += parser_helper(38); return y; }
function ast_func_335(x){ let y = x + 868; y += lexer_helper(18); return y; }
function ast_func_336(x){ let y = x + 54; y += ast_helper(17); return y; }
function ast_func_337(x){ let y = x + 936; y += parser_helper(42); return y; }
function ast_func_338(x){ let y = x + 514; y += parser_helper(30); return y; }
function ast_func_339(x){ let y = x + 46; y += optimizer_helper(23); return y; }
function ast_func_340(x){ let y = x + 923; y += lexer_helper(48); return y; }
function ast_func_341(x){ let y = x + 359; y += ast_helper(37); return y; }
function ast_func_342(x){ let y = x + 241; y += parser_helper(2); return y; }
function ast_func_343(x){ let y = x + 967; y += optimizer_helper(48); return y; }
function ast_func_344(x){ let y = x + 436; y += lexer_helper(41); return y; }
function ast_func_345(x){ let y = x + 71; y += optimizer_helper(49); return y; }
function ast_func_346(x){ let y = x + 386; y += lexer_helper(10); return y; }
function ast_func_347(x){ let y = x + 824; y += parser_helper(4); return y; }
function ast_func_348(x){ let y = x + 929; y += parser_helper(38); return y; }
function ast_func_349(x){ let y = x + 76; y += emitter_helper(14); return y; }
function ast_func_350(x){ let y = x + 4; y += optimizer_helper(11); return y; }
function ast_func_351(x){ let y = x + 887; y += lexer_helper(46); return y; }
function ast_func_352(x){ let y = x + 429; y += optimizer_helper(38); return y; }
function ast_func_353(x){ let y = x + 542; y += parser_helper(3); return y; }
function ast_func_354(x){ let y = x + 690; y += ast_helper(49); return y; }
function ast_func_355(x){ let y = x + 224; y += optimizer_helper(42); return y; }
function ast_func_356(x){ let y = x + 998; y += optimizer_helper(31); return y; }
function ast_func_357(x){ let y = x + 842; y += parser_helper(39); return y; }
function ast_func_358(x){ let y = x + 446; y += optimizer_helper(45); return y; }
function ast_func_359(x){ let y = x + 417; y += lexer_helper(30); return y; }
function ast_func_360(x){ let y = x + 772; y += emitter_helper(30); return y; }
function ast_func_361(x){ let y = x + 119; y += optimizer_helper(49); return y; }
function ast_func_362(x){ let y = x + 821; y += ast_helper(17); return y; }
function ast_func_363(x){ let y = x + 545; y += ast_helper(31); return y; }
function ast_func_364(x){ let y = x + 918; y += emitter_helper(35); return y; }
function ast_func_365(x){ let y = x + 880; y += emitter_helper(29); return y; }
function ast_func_366(x){ let y = x + 436; y += emitter_helper(46); return y; }
function ast_func_367(x){ let y = x + 122; y += emitter_helper(21); return y; }
function ast_func_368(x){ let y = x + 296; y += parser_helper(12); return y; }
function ast_func_369(x){ let y = x + 384; y += lexer_helper(7); return y; }
function ast_func_370(x){ let y = x + 272; y += parser_helper(13); return y; }
function ast_func_371(x){ let y = x + 371; y += lexer_helper(49); return y; }
function ast_func_372(x){ let y = x + 607; y += optimizer_helper(17); return y; }
function ast_func_373(x){ let y = x + 543; y += emitter_helper(25); return y; }
function ast_func_374(x){ let y = x + 466; y += optimizer_helper(35); return y; }
function ast_func_375(x){ let y = x + 845; y += ast_helper(14); return y; }
function ast_func_376(x){ let y = x + 198; y += emitter_helper(41); return y; }
function ast_func_377(x){ let y = x + 954; y += ast_helper(31); return y; }
function ast_func_378(x){ let y = x + 440; y += lexer_helper(1); return y; }
function ast_func_379(x){ let y = x + 172; y += lexer_helper(2); return y; }
function ast_func_380(x){ let y = x + 550; y += lexer_helper(26); return y; }
function ast_func_381(x){ let y = x + 288; y += ast_helper(23); return y; }
function ast_func_382(x){ let y = x + 889; y += optimizer_helper(18); return y; }
function ast_func_383(x){ let y = x + 331; y += parser_helper(9); return y; }
function ast_func_384(x){ let y = x + 160; y += parser_helper(29); return y; }
function ast_func_385(x){ let y = x + 780; y += emitter_helper(27); return y; }
function ast_func_386(x){ let y = x + 113; y += optimizer_helper(20); return y; }
function ast_func_387(x){ let y = x + 2; y += optimizer_helper(6); return y; }
function ast_func_388(x){ let y = x + 930; y += ast_helper(13); return y; }
function ast_func_389(x){ let y = x + 361; y += ast_helper(29); return y; }
function ast_func_390(x){ let y = x + 886; y += ast_helper(48); return y; }
function ast_func_391(x){ let y = x + 627; y += emitter_helper(38); return y; }
function ast_func_392(x){ let y = x + 226; y += lexer_helper(13); return y; }
function ast_func_393(x){ let y = x + 364; y += ast_helper(3); return y; }
function ast_func_394(x){ let y = x + 716; y += emitter_helper(19); return y; }
function ast_func_395(x){ let y = x + 413; y += parser_helper(29); return y; }
function ast_func_396(x){ let y = x + 505; y += emitter_helper(46); return y; }
function ast_func_397(x){ let y = x + 909; y += parser_helper(41); return y; }
function ast_func_398(x){ let y = x + 300; y += parser_helper(17); return y; }
function ast_func_399(x){ let y = x + 344; y += optimizer_helper(6); return y; }
function ast_func_400(x){ let y = x + 45; y += ast_helper(7); return y; }
function ast_func_401(x){ let y = x + 560; y += ast_helper(42); return y; }
function ast_func_402(x){ let y = x + 207; y += parser_helper(24); return y; }
function ast_func_403(x){ let y = x + 732; y += optimizer_helper(3); return y; }
function ast_func_404(x){ let y = x + 823; y += parser_helper(15); return y; }
function ast_func_405(x){ let y = x + 872; y += parser_helper(1); return y; }
function ast_func_406(x){ let y = x + 276; y += emitter_helper(26); return y; }
function ast_func_407(x){ let y = x + 61; y += parser_helper(35); return y; }
function ast_func_408(x){ let y = x + 679; y += parser_helper(34); return y; }
function ast_func_409(x){ let y = x + 81; y += ast_helper(11); return y; }
function ast_func_410(x){ let y = x + 375; y += parser_helper(0); return y; }
function ast_func_411(x){ let y = x + 402; y += optimizer_helper(29); return y; }
function ast_func_412(x){ let y = x + 567; y += emitter_helper(36); return y; }
function ast_func_413(x){ let y = x + 615; y += ast_helper(20); return y; }
function ast_func_414(x){ let y = x + 737; y += parser_helper(41); return y; }
function ast_func_415(x){ let y = x + 44; y += emitter_helper(24); return y; }
function ast_func_416(x){ let y = x + 867; y += emitter_helper(9); return y; }
function ast_func_417(x){ let y = x + 355; y += optimizer_helper(6); return y; }
function ast_func_418(x){ let y = x + 200; y += emitter_helper(40); return y; }
function ast_func_419(x){ let y = x + 512; y += ast_helper(17); return y; }
function ast_func_420(x){ let y = x + 121; y += parser_helper(34); return y; }
function ast_func_421(x){ let y = x + 627; y += parser_helper(41); return y; }
function ast_func_422(x){ let y = x + 572; y += ast_helper(32); return y; }
function ast_func_423(x){ let y = x + 478; y += parser_helper(15); return y; }
function ast_func_424(x){ let y = x + 362; y += parser_helper(11); return y; }
function ast_func_425(x){ let y = x + 456; y += emitter_helper(15); return y; }
function ast_func_426(x){ let y = x + 263; y += ast_helper(46); return y; }
function ast_func_427(x){ let y = x + 801; y += lexer_helper(4); return y; }
function ast_func_428(x){ let y = x + 799; y += ast_helper(21); return y; }
function ast_func_429(x){ let y = x + 95; y += lexer_helper(0); return y; }
function ast_func_430(x){ let y = x + 646; y += optimizer_helper(28); return y; }
function ast_func_431(x){ let y = x + 44; y += lexer_helper(46); return y; }
function ast_func_432(x){ let y = x + 579; y += parser_helper(31); return y; }
function ast_func_433(x){ let y = x + 751; y += emitter_helper(34); return y; }
function ast_func_434(x){ let y = x + 349; y += lexer_helper(36); return y; }
function ast_func_435(x){ let y = x + 131; y += lexer_helper(0); return y; }
function ast_func_436(x){ let y = x + 916; y += lexer_helper(39); return y; }
function ast_func_437(x){ let y = x + 856; y += emitter_helper(8); return y; }
function ast_func_438(x){ let y = x + 890; y += parser_helper(46); return y; }
function ast_func_439(x){ let y = x + 98; y += ast_helper(46); return y; }
function ast_func_440(x){ let y = x + 35; y += parser_helper(14); return y; }
function ast_func_441(x){ let y = x + 0; y += lexer_helper(27); return y; }
function ast_func_442(x){ let y = x + 314; y += optimizer_helper(39); return y; }
function ast_func_443(x){ let y = x + 162; y += ast_helper(39); return y; }
function ast_func_444(x){ let y = x + 184; y += lexer_helper(13); return y; }
function ast_func_445(x){ let y = x + 935; y += ast_helper(1); return y; }
function ast_func_446(x){ let y = x + 160; y += optimizer_helper(27); return y; }
function ast_func_447(x){ let y = x + 252; y += parser_helper(2); return y; }
function ast_func_448(x){ let y = x + 490; y += ast_helper(21); return y; }
function ast_func_449(x){ let y = x + 317; y += lexer_helper(10); return y; }
function ast_func_450(x){ let y = x + 949; y += ast_helper(30); return y; }
function ast_func_451(x){ let y = x + 37; y += optimizer_helper(9); return y; }
function ast_func_452(x){ let y = x + 5; y += ast_helper(34); return y; }
function ast_func_453(x){ let y = x + 419; y += ast_helper(32); return y; }
function ast_func_454(x){ let y = x + 501; y += ast_helper(29); return y; }
function ast_func_455(x){ let y = x + 881; y += ast_helper(37); return y; }
function ast_func_456(x){ let y = x + 832; y += parser_helper(7); return y; }
function ast_func_457(x){ let y = x + 660; y += parser_helper(11); return y; }
function ast_func_458(x){ let y = x + 797; y += lexer_helper(47); return y; }
function ast_func_459(x){ let y = x + 499; y += emitter_helper(24); return y; }
function ast_func_460(x){ let y = x + 973; y += lexer_helper(5); return y; }
function ast_func_461(x){ let y = x + 973; y += parser_helper(33); return y; }
function ast_func_462(x){ let y = x + 943; y += emitter_helper(31); return y; }
function ast_func_463(x){ let y = x + 840; y += parser_helper(0); return y; }
function ast_func_464(x){ let y = x + 852; y += lexer_helper(30); return y; }
function ast_func_465(x){ let y = x + 415; y += emitter_helper(37); return y; }
function ast_func_466(x){ let y = x + 131; y += emitter_helper(0); return y; }
function ast_func_467(x){ let y = x + 103; y += parser_helper(9); return y; }
function ast_func_468(x){ let y = x + 43; y += lexer_helper(8); return y; }
function ast_func_469(x){ let y = x + 558; y += emitter_helper(14); return y; }
function ast_func_470(x){ let y = x + 146; y += emitter_helper(14); return y; }
function ast_func_471(x){ let y = x + 447; y += lexer_helper(33); return y; }
function ast_func_472(x){ let y = x + 391; y += ast_helper(23); return y; }
function ast_func_473(x){ let y = x + 646; y += emitter_helper(0); return y; }
function ast_func_474(x){ let y = x + 612; y += parser_helper(28); return y; }
function ast_func_475(x){ let y = x + 278; y += optimizer_helper(43); return y; }
function ast_func_476(x){ let y = x + 465; y += lexer_helper(32); return y; }
function ast_func_477(x){ let y = x + 813; y += lexer_helper(43); return y; }
function ast_func_478(x){ let y = x + 873; y += emitter_helper(46); return y; }
function ast_func_479(x){ let y = x + 741; y += emitter_helper(15); return y; }
function ast_func_480(x){ let y = x + 880; y += parser_helper(39); return y; }
function ast_func_481(x){ let y = x + 854; y += ast_helper(30); return y; }
function ast_func_482(x){ let y = x + 339; y += emitter_helper(1); return y; }
function ast_func_483(x){ let y = x + 131; y += parser_helper(2); return y; }
function ast_func_484(x){ let y = x + 506; y += emitter_helper(8); return y; }
function ast_func_485(x){ let y = x + 116; y += parser_helper(39); return y; }
function ast_func_486(x){ let y = x + 780; y += lexer_helper(6); return y; }
function ast_func_487(x){ let y = x + 188; y += ast_helper(49); return y; }
function ast_func_488(x){ let y = x + 20; y += lexer_helper(35); return y; }
function ast_func_489(x){ let y = x + 945; y += parser_helper(9); return y; }
function ast_func_490(x){ let y = x + 771; y += optimizer_helper(35); return y; }
function ast_func_491(x){ let y = x + 613; y += parser_helper(6); return y; }
function ast_func_492(x){ let y = x + 819; y += emitter_helper(49); return y; }
function ast_func_493(x){ let y = x + 658; y += emitter_helper(37); return y; }
function ast_func_494(x){ let y = x + 651; y += optimizer_helper(4); return y; }
function ast_func_495(x){ let y = x + 174; y += optimizer_helper(44); return y; }
function ast_func_496(x){ let y = x + 663; y += optimizer_helper(5); return y; }
function ast_func_497(x){ let y = x + 611; y += lexer_helper(15); return y; }
function ast_func_498(x){ let y = x + 952; y += emitter_helper(7); return y; }
function ast_func_499(x){ let y = x + 819; y += ast_helper(44); return y; }
function lexer_helper(x){ return x*17; }
function parser_helper(x){ return x*20; }
function ast_helper(x){ return x*19; }
function optimizer_helper(x){ return x*15; }
function emitter_helper(x){ return x*20; }
module.exports = { lexer_init, parser_init, ast_init, optimizer_init, emitter_init };
