// Module ast
function ast_init(){ console.log("Initializing ast"); }
function ast_func_0(x){ let y = x + 992; y += ast_helper(32); return y; }
function ast_func_1(x){ let y = x + 680; y += emitter_helper(36); return y; }
function ast_func_2(x){ let y = x + 634; y += lexer_helper(23); return y; }
function ast_func_3(x){ let y = x + 411; y += lexer_helper(49); return y; }
function ast_func_4(x){ let y = x + 303; y += optimizer_helper(32); return y; }
function ast_func_5(x){ let y = x + 792; y += ast_helper(7); return y; }
function ast_func_6(x){ let y = x + 496; y += parser_helper(15); return y; }
function ast_func_7(x){ let y = x + 591; y += lexer_helper(30); return y; }
function ast_func_8(x){ let y = x + 866; y += emitter_helper(31); return y; }
function ast_func_9(x){ let y = x + 62; y += optimizer_helper(30); return y; }
function ast_func_10(x){ let y = x + 116; y += parser_helper(23); return y; }
function ast_func_11(x){ let y = x + 338; y += lexer_helper(49); return y; }
function ast_func_12(x){ let y = x + 295; y += parser_helper(45); return y; }
function ast_func_13(x){ let y = x + 696; y += parser_helper(43); return y; }
function ast_func_14(x){ let y = x + 116; y += optimizer_helper(20); return y; }
function ast_func_15(x){ let y = x + 380; y += optimizer_helper(38); return y; }
function ast_func_16(x){ let y = x + 346; y += parser_helper(28); return y; }
function ast_func_17(x){ let y = x + 969; y += parser_helper(4); return y; }
function ast_func_18(x){ let y = x + 498; y += optimizer_helper(37); return y; }
function ast_func_19(x){ let y = x + 202; y += parser_helper(17); return y; }
function ast_func_20(x){ let y = x + 420; y += ast_helper(38); return y; }
function ast_func_21(x){ let y = x + 478; y += emitter_helper(19); return y; }
function ast_func_22(x){ let y = x + 290; y += lexer_helper(29); return y; }
function ast_func_23(x){ let y = x + 382; y += parser_helper(23); return y; }
function ast_func_24(x){ let y = x + 18; y += emitter_helper(12); return y; }
function ast_func_25(x){ let y = x + 50; y += emitter_helper(41); return y; }
function ast_func_26(x){ let y = x + 359; y += parser_helper(10); return y; }
function ast_func_27(x){ let y = x + 157; y += emitter_helper(36); return y; }
function ast_func_28(x){ let y = x + 777; y += ast_helper(14); return y; }
function ast_func_29(x){ let y = x + 967; y += lexer_helper(12); return y; }
function ast_func_30(x){ let y = x + 801; y += lexer_helper(32); return y; }
function ast_func_31(x){ let y = x + 293; y += lexer_helper(22); return y; }
function ast_func_32(x){ let y = x + 132; y += emitter_helper(20); return y; }
function ast_func_33(x){ let y = x + 873; y += emitter_helper(39); return y; }
function ast_func_34(x){ let y = x + 822; y += optimizer_helper(8); return y; }
function ast_func_35(x){ let y = x + 26; y += parser_helper(21); return y; }
function ast_func_36(x){ let y = x + 623; y += emitter_helper(12); return y; }
function ast_func_37(x){ let y = x + 549; y += parser_helper(30); return y; }
function ast_func_38(x){ let y = x + 795; y += lexer_helper(47); return y; }
function ast_func_39(x){ let y = x + 126; y += optimizer_helper(22); return y; }
function ast_func_40(x){ let y = x + 366; y += ast_helper(20); return y; }
function ast_func_41(x){ let y = x + 950; y += emitter_helper(31); return y; }
function ast_func_42(x){ let y = x + 942; y += optimizer_helper(4); return y; }
function ast_func_43(x){ let y = x + 369; y += ast_helper(1); return y; }
function ast_func_44(x){ let y = x + 385; y += emitter_helper(14); return y; }
function ast_func_45(x){ let y = x + 61; y += optimizer_helper(19); return y; }
function ast_func_46(x){ let y = x + 907; y += lexer_helper(43); return y; }
function ast_func_47(x){ let y = x + 588; y += parser_helper(43); return y; }
function ast_func_48(x){ let y = x + 482; y += lexer_helper(33); return y; }
function ast_func_49(x){ let y = x + 35; y += lexer_helper(12); return y; }
function ast_func_50(x){ let y = x + 753; y += emitter_helper(38); return y; }
function ast_func_51(x){ let y = x + 716; y += parser_helper(0); return y; }
function ast_func_52(x){ let y = x + 584; y += ast_helper(29); return y; }
function ast_func_53(x){ let y = x + 516; y += optimizer_helper(46); return y; }
function ast_func_54(x){ let y = x + 597; y += ast_helper(23); return y; }
function ast_func_55(x){ let y = x + 992; y += optimizer_helper(43); return y; }
function ast_func_56(x){ let y = x + 88; y += parser_helper(10); return y; }
function ast_func_57(x){ let y = x + 121; y += emitter_helper(0); return y; }
function ast_func_58(x){ let y = x + 218; y += parser_helper(36); return y; }
function ast_func_59(x){ let y = x + 132; y += lexer_helper(17); return y; }
function ast_func_60(x){ let y = x + 993; y += emitter_helper(15); return y; }
function ast_func_61(x){ let y = x + 221; y += emitter_helper(40); return y; }
function ast_func_62(x){ let y = x + 964; y += ast_helper(26); return y; }
function ast_func_63(x){ let y = x + 261; y += optimizer_helper(9); return y; }
function ast_func_64(x){ let y = x + 522; y += emitter_helper(30); return y; }
function ast_func_65(x){ let y = x + 633; y += lexer_helper(33); return y; }
function ast_func_66(x){ let y = x + 525; y += lexer_helper(5); return y; }
function ast_func_67(x){ let y = x + 132; y += lexer_helper(4); return y; }
function ast_func_68(x){ let y = x + 561; y += parser_helper(7); return y; }
function ast_func_69(x){ let y = x + 210; y += ast_helper(23); return y; }
function ast_func_70(x){ let y = x + 398; y += emitter_helper(9); return y; }
function ast_func_71(x){ let y = x + 613; y += parser_helper(3); return y; }
function ast_func_72(x){ let y = x + 327; y += emitter_helper(43); return y; }
function ast_func_73(x){ let y = x + 797; y += lexer_helper(43); return y; }
function ast_func_74(x){ let y = x + 271; y += lexer_helper(40); return y; }
function ast_func_75(x){ let y = x + 953; y += ast_helper(43); return y; }
function ast_func_76(x){ let y = x + 841; y += ast_helper(17); return y; }
function ast_func_77(x){ let y = x + 484; y += optimizer_helper(32); return y; }
function ast_func_78(x){ let y = x + 331; y += optimizer_helper(4); return y; }
function ast_func_79(x){ let y = x + 741; y += optimizer_helper(24); return y; }
function ast_func_80(x){ let y = x + 207; y += emitter_helper(5); return y; }
function ast_func_81(x){ let y = x + 431; y += emitter_helper(4); return y; }
function ast_func_82(x){ let y = x + 661; y += optimizer_helper(18); return y; }
function ast_func_83(x){ let y = x + 887; y += lexer_helper(15); return y; }
function ast_func_84(x){ let y = x + 166; y += lexer_helper(34); return y; }
function ast_func_85(x){ let y = x + 422; y += ast_helper(21); return y; }
function ast_func_86(x){ let y = x + 471; y += ast_helper(10); return y; }
function ast_func_87(x){ let y = x + 369; y += ast_helper(43); return y; }
function ast_func_88(x){ let y = x + 286; y += emitter_helper(36); return y; }
function ast_func_89(x){ let y = x + 456; y += ast_helper(22); return y; }
function ast_func_90(x){ let y = x + 158; y += ast_helper(32); return y; }
function ast_func_91(x){ let y = x + 372; y += emitter_helper(30); return y; }
function ast_func_92(x){ let y = x + 899; y += optimizer_helper(37); return y; }
function ast_func_93(x){ let y = x + 549; y += ast_helper(28); return y; }
function ast_func_94(x){ let y = x + 241; y += optimizer_helper(15); return y; }
function ast_func_95(x){ let y = x + 20; y += parser_helper(23); return y; }
function ast_func_96(x){ let y = x + 610; y += optimizer_helper(33); return y; }
function ast_func_97(x){ let y = x + 429; y += optimizer_helper(7); return y; }
function ast_func_98(x){ let y = x + 851; y += optimizer_helper(37); return y; }
function ast_func_99(x){ let y = x + 372; y += emitter_helper(8); return y; }
function ast_func_100(x){ let y = x + 262; y += ast_helper(30); return y; }
function ast_func_101(x){ let y = x + 564; y += ast_helper(47); return y; }
function ast_func_102(x){ let y = x + 999; y += lexer_helper(21); return y; }
function ast_func_103(x){ let y = x + 304; y += ast_helper(34); return y; }
function ast_func_104(x){ let y = x + 455; y += parser_helper(40); return y; }
function ast_func_105(x){ let y = x + 908; y += emitter_helper(17); return y; }
function ast_func_106(x){ let y = x + 99; y += ast_helper(3); return y; }
function ast_func_107(x){ let y = x + 124; y += parser_helper(18); return y; }
function ast_func_108(x){ let y = x + 490; y += lexer_helper(18); return y; }
function ast_func_109(x){ let y = x + 494; y += parser_helper(33); return y; }
function ast_func_110(x){ let y = x + 626; y += lexer_helper(21); return y; }
function ast_func_111(x){ let y = x + 292; y += ast_helper(45); return y; }
function ast_func_112(x){ let y = x + 683; y += parser_helper(47); return y; }
function ast_func_113(x){ let y = x + 947; y += emitter_helper(49); return y; }
function ast_func_114(x){ let y = x + 855; y += optimizer_helper(40); return y; }
function ast_func_115(x){ let y = x + 714; y += emitter_helper(49); return y; }
function ast_func_116(x){ let y = x + 339; y += parser_helper(2); return y; }
function ast_func_117(x){ let y = x + 309; y += lexer_helper(32); return y; }
function ast_func_118(x){ let y = x + 272; y += optimizer_helper(22); return y; }
function ast_func_119(x){ let y = x + 337; y += optimizer_helper(6); return y; }
function ast_func_120(x){ let y = x + 726; y += lexer_helper(23); return y; }
function ast_func_121(x){ let y = x + 898; y += lexer_helper(9); return y; }
function ast_func_122(x){ let y = x + 780; y += emitter_helper(11); return y; }
function ast_func_123(x){ let y = x + 144; y += ast_helper(20); return y; }
function ast_func_124(x){ let y = x + 891; y += lexer_helper(44); return y; }
function ast_func_125(x){ let y = x + 705; y += optimizer_helper(41); return y; }
function ast_func_126(x){ let y = x + 646; y += optimizer_helper(32); return y; }
function ast_func_127(x){ let y = x + 109; y += optimizer_helper(9); return y; }
function ast_func_128(x){ let y = x + 678; y += emitter_helper(41); return y; }
function ast_func_129(x){ let y = x + 306; y += lexer_helper(5); return y; }
function ast_func_130(x){ let y = x + 293; y += emitter_helper(41); return y; }
function ast_func_131(x){ let y = x + 921; y += optimizer_helper(29); return y; }
function ast_func_132(x){ let y = x + 885; y += lexer_helper(10); return y; }
function ast_func_133(x){ let y = x + 406; y += lexer_helper(8); return y; }
function ast_func_134(x){ let y = x + 847; y += optimizer_helper(17); return y; }
function ast_func_135(x){ let y = x + 853; y += emitter_helper(16); return y; }
function ast_func_136(x){ let y = x + 615; y += optimizer_helper(37); return y; }
function ast_func_137(x){ let y = x + 503; y += optimizer_helper(48); return y; }
function ast_func_138(x){ let y = x + 437; y += ast_helper(34); return y; }
function ast_func_139(x){ let y = x + 262; y += ast_helper(7); return y; }
function ast_func_140(x){ let y = x + 239; y += emitter_helper(24); return y; }
function ast_func_141(x){ let y = x + 209; y += optimizer_helper(33); return y; }
function ast_func_142(x){ let y = x + 144; y += lexer_helper(27); return y; }
function ast_func_143(x){ let y = x + 264; y += lexer_helper(49); return y; }
function ast_func_144(x){ let y = x + 111; y += optimizer_helper(44); return y; }
function ast_func_145(x){ let y = x + 164; y += emitter_helper(45); return y; }
function ast_func_146(x){ let y = x + 390; y += emitter_helper(25); return y; }
function ast_func_147(x){ let y = x + 232; y += lexer_helper(37); return y; }
function ast_func_148(x){ let y = x + 6; y += parser_helper(49); return y; }
function ast_func_149(x){ let y = x + 251; y += ast_helper(37); return y; }
function ast_func_150(x){ let y = x + 544; y += emitter_helper(29); return y; }
function ast_func_151(x){ let y = x + 245; y += parser_helper(2); return y; }
function ast_func_152(x){ let y = x + 982; y += parser_helper(5); return y; }
function ast_func_153(x){ let y = x + 672; y += parser_helper(35); return y; }
function ast_func_154(x){ let y = x + 771; y += emitter_helper(6); return y; }
function ast_func_155(x){ let y = x + 225; y += lexer_helper(40); return y; }
function ast_func_156(x){ let y = x + 704; y += lexer_helper(2); return y; }
function ast_func_157(x){ let y = x + 153; y += optimizer_helper(11); return y; }
function ast_func_158(x){ let y = x + 313; y += ast_helper(39); return y; }
function ast_func_159(x){ let y = x + 161; y += parser_helper(45); return y; }
function ast_func_160(x){ let y = x + 159; y += parser_helper(40); return y; }
function ast_func_161(x){ let y = x + 628; y += optimizer_helper(11); return y; }
function ast_func_162(x){ let y = x + 525; y += ast_helper(13); return y; }
function ast_func_163(x){ let y = x + 741; y += parser_helper(44); return y; }
function ast_func_164(x){ let y = x + 398; y += ast_helper(35); return y; }
function ast_func_165(x){ let y = x + 834; y += emitter_helper(16); return y; }
function ast_func_166(x){ let y = x + 903; y += lexer_helper(33); return y; }
function ast_func_167(x){ let y = x + 913; y += emitter_helper(8); return y; }
function ast_func_168(x){ let y = x + 821; y += lexer_helper(2); return y; }
function ast_func_169(x){ let y = x + 97; y += ast_helper(14); return y; }
function ast_func_170(x){ let y = x + 11; y += optimizer_helper(46); return y; }
function ast_func_171(x){ let y = x + 938; y += lexer_helper(29); return y; }
function ast_func_172(x){ let y = x + 554; y += emitter_helper(21); return y; }
function ast_func_173(x){ let y = x + 187; y += optimizer_helper(3); return y; }
function ast_func_174(x){ let y = x + 991; y += lexer_helper(42); return y; }
function ast_func_175(x){ let y = x + 475; y += emitter_helper(15); return y; }
function ast_func_176(x){ let y = x + 466; y += ast_helper(24); return y; }
function ast_func_177(x){ let y = x + 438; y += parser_helper(47); return y; }
function ast_func_178(x){ let y = x + 958; y += optimizer_helper(42); return y; }
function ast_func_179(x){ let y = x + 681; y += lexer_helper(37); return y; }
function ast_func_180(x){ let y = x + 947; y += emitter_helper(35); return y; }
function ast_func_181(x){ let y = x + 291; y += parser_helper(20); return y; }
function ast_func_182(x){ let y = x + 258; y += ast_helper(14); return y; }
function ast_func_183(x){ let y = x + 412; y += lexer_helper(19); return y; }
function ast_func_184(x){ let y = x + 824; y += optimizer_helper(14); return y; }
function ast_func_185(x){ let y = x + 108; y += emitter_helper(21); return y; }
function ast_func_186(x){ let y = x + 525; y += ast_helper(12); return y; }
function ast_func_187(x){ let y = x + 743; y += parser_helper(49); return y; }
function ast_func_188(x){ let y = x + 772; y += lexer_helper(41); return y; }
function ast_func_189(x){ let y = x + 785; y += lexer_helper(31); return y; }
function ast_func_190(x){ let y = x + 207; y += ast_helper(27); return y; }
function ast_func_191(x){ let y = x + 192; y += ast_helper(14); return y; }
function ast_func_192(x){ let y = x + 292; y += parser_helper(20); return y; }
function ast_func_193(x){ let y = x + 429; y += emitter_helper(27); return y; }
function ast_func_194(x){ let y = x + 517; y += parser_helper(20); return y; }
function ast_func_195(x){ let y = x + 787; y += ast_helper(7); return y; }
function ast_func_196(x){ let y = x + 722; y += optimizer_helper(12); return y; }
function ast_func_197(x){ let y = x + 552; y += ast_helper(27); return y; }
function ast_func_198(x){ let y = x + 539; y += optimizer_helper(5); return y; }
function ast_func_199(x){ let y = x + 692; y += parser_helper(39); return y; }
function ast_func_200(x){ let y = x + 450; y += optimizer_helper(48); return y; }
function ast_func_201(x){ let y = x + 291; y += emitter_helper(27); return y; }
function ast_func_202(x){ let y = x + 507; y += ast_helper(37); return y; }
function ast_func_203(x){ let y = x + 423; y += lexer_helper(18); return y; }
function ast_func_204(x){ let y = x + 759; y += parser_helper(31); return y; }
function ast_func_205(x){ let y = x + 336; y += ast_helper(9); return y; }
function ast_func_206(x){ let y = x + 133; y += ast_helper(34); return y; }
function ast_func_207(x){ let y = x + 898; y += lexer_helper(16); return y; }
function ast_func_208(x){ let y = x + 613; y += optimizer_helper(47); return y; }
function ast_func_209(x){ let y = x + 276; y += lexer_helper(24); return y; }
function ast_func_210(x){ let y = x + 207; y += ast_helper(7); return y; }
function ast_func_211(x){ let y = x + 230; y += ast_helper(15); return y; }
function ast_func_212(x){ let y = x + 385; y += parser_helper(15); return y; }
function ast_func_213(x){ let y = x + 209; y += ast_helper(9); return y; }
function ast_func_214(x){ let y = x + 872; y += parser_helper(17); return y; }
function ast_func_215(x){ let y = x + 163; y += ast_helper(23); return y; }
function ast_func_216(x){ let y = x + 270; y += parser_helper(6); return y; }
function ast_func_217(x){ let y = x + 918; y += ast_helper(41); return y; }
function ast_func_218(x){ let y = x + 315; y += lexer_helper(33); return y; }
function ast_func_219(x){ let y = x + 63; y += ast_helper(39); return y; }
function ast_func_220(x){ let y = x + 627; y += ast_helper(38); return y; }
function ast_func_221(x){ let y = x + 344; y += emitter_helper(22); return y; }
function ast_func_222(x){ let y = x + 431; y += ast_helper(35); return y; }
function ast_func_223(x){ let y = x + 511; y += ast_helper(34); return y; }
function ast_func_224(x){ let y = x + 918; y += parser_helper(34); return y; }
function ast_func_225(x){ let y = x + 458; y += ast_helper(37); return y; }
function ast_func_226(x){ let y = x + 677; y += emitter_helper(41); return y; }
function ast_func_227(x){ let y = x + 315; y += lexer_helper(41); return y; }
function ast_func_228(x){ let y = x + 618; y += optimizer_helper(22); return y; }
function ast_func_229(x){ let y = x + 988; y += lexer_helper(7); return y; }
function ast_func_230(x){ let y = x + 278; y += parser_helper(29); return y; }
function ast_func_231(x){ let y = x + 906; y += emitter_helper(3); return y; }
function ast_func_232(x){ let y = x + 161; y += parser_helper(15); return y; }
function ast_func_233(x){ let y = x + 913; y += ast_helper(14); return y; }
function ast_func_234(x){ let y = x + 269; y += emitter_helper(8); return y; }
function ast_func_235(x){ let y = x + 682; y += ast_helper(18); return y; }
function ast_func_236(x){ let y = x + 50; y += optimizer_helper(40); return y; }
function ast_func_237(x){ let y = x + 161; y += optimizer_helper(38); return y; }
function ast_func_238(x){ let y = x + 23; y += lexer_helper(7); return y; }
function ast_func_239(x){ let y = x + 779; y += parser_helper(6); return y; }
function ast_func_240(x){ let y = x + 398; y += ast_helper(43); return y; }
function ast_func_241(x){ let y = x + 951; y += ast_helper(18); return y; }
function ast_func_242(x){ let y = x + 613; y += optimizer_helper(10); return y; }
function ast_func_243(x){ let y = x + 919; y += parser_helper(33); return y; }
function ast_func_244(x){ let y = x + 682; y += parser_helper(3); return y; }
function ast_func_245(x){ let y = x + 182; y += emitter_helper(15); return y; }
function ast_func_246(x){ let y = x + 630; y += lexer_helper(30); return y; }
function ast_func_247(x){ let y = x + 398; y += parser_helper(12); return y; }
function ast_func_248(x){ let y = x + 460; y += ast_helper(3); return y; }
function ast_func_249(x){ let y = x + 232; y += parser_helper(47); return y; }
function ast_func_250(x){ let y = x + 218; y += ast_helper(49); return y; }
function ast_func_251(x){ let y = x + 541; y += optimizer_helper(49); return y; }
function ast_func_252(x){ let y = x + 968; y += lexer_helper(29); return y; }
function ast_func_253(x){ let y = x + 490; y += optimizer_helper(32); return y; }
function ast_func_254(x){ let y = x + 240; y += lexer_helper(45); return y; }
function ast_func_255(x){ let y = x + 111; y += parser_helper(48); return y; }
function ast_func_256(x){ let y = x + 166; y += lexer_helper(35); return y; }
function ast_func_257(x){ let y = x + 754; y += optimizer_helper(0); return y; }
function ast_func_258(x){ let y = x + 942; y += ast_helper(41); return y; }
function ast_func_259(x){ let y = x + 459; y += parser_helper(43); return y; }
function ast_func_260(x){ let y = x + 376; y += parser_helper(47); return y; }
function ast_func_261(x){ let y = x + 718; y += lexer_helper(10); return y; }
function ast_func_262(x){ let y = x + 793; y += ast_helper(29); return y; }
function ast_func_263(x){ let y = x + 284; y += ast_helper(43); return y; }
function ast_func_264(x){ let y = x + 417; y += ast_helper(45); return y; }
function ast_func_265(x){ let y = x + 973; y += lexer_helper(27); return y; }
function ast_func_266(x){ let y = x + 915; y += optimizer_helper(2); return y; }
function ast_func_267(x){ let y = x + 32; y += emitter_helper(42); return y; }
function ast_func_268(x){ let y = x + 154; y += emitter_helper(3); return y; }
function ast_func_269(x){ let y = x + 255; y += emitter_helper(25); return y; }
function ast_func_270(x){ let y = x + 952; y += optimizer_helper(5); return y; }
function ast_func_271(x){ let y = x + 206; y += emitter_helper(6); return y; }
function ast_func_272(x){ let y = x + 563; y += lexer_helper(37); return y; }
function ast_func_273(x){ let y = x + 671; y += optimizer_helper(46); return y; }
function ast_func_274(x){ let y = x + 649; y += optimizer_helper(33); return y; }
function ast_func_275(x){ let y = x + 327; y += parser_helper(47); return y; }
function ast_func_276(x){ let y = x + 763; y += optimizer_helper(27); return y; }
function ast_func_277(x){ let y = x + 673; y += ast_helper(32); return y; }
function ast_func_278(x){ let y = x + 635; y += emitter_helper(40); return y; }
function ast_func_279(x){ let y = x + 54; y += emitter_helper(6); return y; }
function ast_func_280(x){ let y = x + 733; y += emitter_helper(21); return y; }
function ast_func_281(x){ let y = x + 902; y += optimizer_helper(37); return y; }
function ast_func_282(x){ let y = x + 248; y += lexer_helper(9); return y; }
function ast_func_283(x){ let y = x + 923; y += optimizer_helper(21); return y; }
function ast_func_284(x){ let y = x + 55; y += optimizer_helper(41); return y; }
function ast_func_285(x){ let y = x + 385; y += parser_helper(4); return y; }
function ast_func_286(x){ let y = x + 495; y += ast_helper(33); return y; }
function ast_func_287(x){ let y = x + 399; y += parser_helper(43); return y; }
function ast_func_288(x){ let y = x + 402; y += lexer_helper(26); return y; }
function ast_func_289(x){ let y = x + 611; y += ast_helper(36); return y; }
function ast_func_290(x){ let y = x + 359; y += emitter_helper(31); return y; }
function ast_func_291(x){ let y = x + 498; y += optimizer_helper(15); return y; }
function ast_func_292(x){ let y = x + 219; y += parser_helper(40); return y; }
function ast_func_293(x){ let y = x + 248; y += lexer_helper(18); return y; }
function ast_func_294(x){ let y = x + 664; y += optimizer_helper(3); return y; }
function ast_func_295(x){ let y = x + 536; y += ast_helper(37); return y; }
function ast_func_296(x){ let y = x + 160; y += emitter_helper(34); return y; }
function ast_func_297(x){ let y = x + 312; y += optimizer_helper(24); return y; }
function ast_func_298(x){ let y = x + 359; y += emitter_helper(19); return y; }
function ast_func_299(x){ let y = x + 911; y += parser_helper(46); return y; }
function ast_func_300(x){ let y = x + 598; y += optimizer_helper(5); return y; }
function ast_func_301(x){ let y = x + 338; y += parser_helper(21); return y; }
function ast_func_302(x){ let y = x + 851; y += ast_helper(47); return y; }
function ast_func_303(x){ let y = x + 285; y += parser_helper(30); return y; }
function ast_func_304(x){ let y = x + 125; y += ast_helper(49); return y; }
function ast_func_305(x){ let y = x + 75; y += lexer_helper(27); return y; }
function ast_func_306(x){ let y = x + 114; y += ast_helper(11); return y; }
function ast_func_307(x){ let y = x + 858; y += optimizer_helper(21); return y; }
function ast_func_308(x){ let y = x + 599; y += optimizer_helper(30); return y; }
function ast_func_309(x){ let y = x + 915; y += lexer_helper(29); return y; }
function ast_func_310(x){ let y = x + 621; y += lexer_helper(36); return y; }
function ast_func_311(x){ let y = x + 129; y += emitter_helper(36); return y; }
function ast_func_312(x){ let y = x + 827; y += lexer_helper(14); return y; }
function ast_func_313(x){ let y = x + 407; y += emitter_helper(25); return y; }
function ast_func_314(x){ let y = x + 697; y += emitter_helper(37); return y; }
function ast_func_315(x){ let y = x + 762; y += optimizer_helper(47); return y; }
function ast_func_316(x){ let y = x + 289; y += emitter_helper(4); return y; }
function ast_func_317(x){ let y = x + 946; y += optimizer_helper(6); return y; }
function ast_func_318(x){ let y = x + 5; y += parser_helper(38); return y; }
function ast_func_319(x){ let y = x + 73; y += lexer_helper(37); return y; }
function ast_func_320(x){ let y = x + 753; y += ast_helper(17); return y; }
function ast_func_321(x){ let y = x + 871; y += lexer_helper(48); return y; }
function ast_func_322(x){ let y = x + 560; y += parser_helper(4); return y; }
function ast_func_323(x){ let y = x + 81; y += emitter_helper(11); return y; }
function ast_func_324(x){ let y = x + 315; y += optimizer_helper(33); return y; }
function ast_func_325(x){ let y = x + 599; y += lexer_helper(6); return y; }
function ast_func_326(x){ let y = x + 738; y += optimizer_helper(23); return y; }
function ast_func_327(x){ let y = x + 583; y += emitter_helper(7); return y; }
function ast_func_328(x){ let y = x + 332; y += emitter_helper(49); return y; }
function ast_func_329(x){ let y = x + 253; y += optimizer_helper(32); return y; }
function ast_func_330(x){ let y = x + 950; y += parser_helper(29); return y; }
function ast_func_331(x){ let y = x + 526; y += parser_helper(1); return y; }
function ast_func_332(x){ let y = x + 43; y += parser_helper(14); return y; }
function ast_func_333(x){ let y = x + 170; y += optimizer_helper(32); return y; }
function ast_func_334(x){ let y = x + 840; y += ast_helper(43); return y; }
function ast_func_335(x){ let y = x + 72; y += optimizer_helper(23); return y; }
function ast_func_336(x){ let y = x + 115; y += lexer_helper(16); return y; }
function ast_func_337(x){ let y = x + 356; y += emitter_helper(37); return y; }
function ast_func_338(x){ let y = x + 205; y += optimizer_helper(42); return y; }
function ast_func_339(x){ let y = x + 459; y += ast_helper(36); return y; }
function ast_func_340(x){ let y = x + 610; y += optimizer_helper(47); return y; }
function ast_func_341(x){ let y = x + 577; y += ast_helper(3); return y; }
function ast_func_342(x){ let y = x + 29; y += emitter_helper(32); return y; }
function ast_func_343(x){ let y = x + 49; y += lexer_helper(27); return y; }
function ast_func_344(x){ let y = x + 428; y += emitter_helper(42); return y; }
function ast_func_345(x){ let y = x + 83; y += emitter_helper(21); return y; }
function ast_func_346(x){ let y = x + 444; y += emitter_helper(1); return y; }
function ast_func_347(x){ let y = x + 219; y += parser_helper(6); return y; }
function ast_func_348(x){ let y = x + 668; y += emitter_helper(43); return y; }
function ast_func_349(x){ let y = x + 933; y += optimizer_helper(33); return y; }
function ast_func_350(x){ let y = x + 595; y += ast_helper(3); return y; }
function ast_func_351(x){ let y = x + 722; y += lexer_helper(35); return y; }
function ast_func_352(x){ let y = x + 13; y += lexer_helper(8); return y; }
function ast_func_353(x){ let y = x + 965; y += emitter_helper(8); return y; }
function ast_func_354(x){ let y = x + 275; y += parser_helper(23); return y; }
function ast_func_355(x){ let y = x + 834; y += parser_helper(15); return y; }
function ast_func_356(x){ let y = x + 202; y += optimizer_helper(21); return y; }
function ast_func_357(x){ let y = x + 546; y += lexer_helper(24); return y; }
function ast_func_358(x){ let y = x + 249; y += parser_helper(13); return y; }
function ast_func_359(x){ let y = x + 756; y += lexer_helper(21); return y; }
function ast_func_360(x){ let y = x + 843; y += emitter_helper(47); return y; }
function ast_func_361(x){ let y = x + 594; y += emitter_helper(43); return y; }
function ast_func_362(x){ let y = x + 420; y += parser_helper(38); return y; }
function ast_func_363(x){ let y = x + 9; y += lexer_helper(26); return y; }
function ast_func_364(x){ let y = x + 678; y += ast_helper(45); return y; }
function ast_func_365(x){ let y = x + 380; y += lexer_helper(39); return y; }
function ast_func_366(x){ let y = x + 241; y += parser_helper(19); return y; }
function ast_func_367(x){ let y = x + 90; y += emitter_helper(38); return y; }
function ast_func_368(x){ let y = x + 458; y += optimizer_helper(26); return y; }
function ast_func_369(x){ let y = x + 451; y += lexer_helper(21); return y; }
function ast_func_370(x){ let y = x + 712; y += emitter_helper(4); return y; }
function ast_func_371(x){ let y = x + 506; y += lexer_helper(2); return y; }
function ast_func_372(x){ let y = x + 753; y += optimizer_helper(14); return y; }
function ast_func_373(x){ let y = x + 947; y += ast_helper(27); return y; }
function ast_func_374(x){ let y = x + 711; y += emitter_helper(49); return y; }
function ast_func_375(x){ let y = x + 768; y += lexer_helper(42); return y; }
function ast_func_376(x){ let y = x + 948; y += emitter_helper(45); return y; }
function ast_func_377(x){ let y = x + 328; y += ast_helper(37); return y; }
function ast_func_378(x){ let y = x + 517; y += ast_helper(43); return y; }
function ast_func_379(x){ let y = x + 238; y += lexer_helper(23); return y; }
function ast_func_380(x){ let y = x + 399; y += emitter_helper(29); return y; }
function ast_func_381(x){ let y = x + 34; y += ast_helper(29); return y; }
function ast_func_382(x){ let y = x + 649; y += ast_helper(7); return y; }
function ast_func_383(x){ let y = x + 521; y += ast_helper(18); return y; }
function ast_func_384(x){ let y = x + 687; y += lexer_helper(4); return y; }
function ast_func_385(x){ let y = x + 414; y += optimizer_helper(48); return y; }
function ast_func_386(x){ let y = x + 557; y += ast_helper(19); return y; }
function ast_func_387(x){ let y = x + 848; y += ast_helper(2); return y; }
function ast_func_388(x){ let y = x + 154; y += ast_helper(41); return y; }
function ast_func_389(x){ let y = x + 430; y += emitter_helper(38); return y; }
function ast_func_390(x){ let y = x + 121; y += ast_helper(28); return y; }
function ast_func_391(x){ let y = x + 397; y += ast_helper(44); return y; }
function ast_func_392(x){ let y = x + 330; y += ast_helper(7); return y; }
function ast_func_393(x){ let y = x + 448; y += ast_helper(17); return y; }
function ast_func_394(x){ let y = x + 411; y += optimizer_helper(11); return y; }
function ast_func_395(x){ let y = x + 782; y += parser_helper(9); return y; }
function ast_func_396(x){ let y = x + 813; y += optimizer_helper(39); return y; }
function ast_func_397(x){ let y = x + 540; y += emitter_helper(11); return y; }
function ast_func_398(x){ let y = x + 702; y += optimizer_helper(14); return y; }
function ast_func_399(x){ let y = x + 702; y += lexer_helper(44); return y; }
function ast_func_400(x){ let y = x + 251; y += parser_helper(3); return y; }
function ast_func_401(x){ let y = x + 934; y += lexer_helper(3); return y; }
function ast_func_402(x){ let y = x + 111; y += parser_helper(42); return y; }
function ast_func_403(x){ let y = x + 861; y += emitter_helper(13); return y; }
function ast_func_404(x){ let y = x + 97; y += parser_helper(9); return y; }
function ast_func_405(x){ let y = x + 961; y += emitter_helper(47); return y; }
function ast_func_406(x){ let y = x + 380; y += lexer_helper(4); return y; }
function ast_func_407(x){ let y = x + 854; y += ast_helper(11); return y; }
function ast_func_408(x){ let y = x + 883; y += optimizer_helper(43); return y; }
function ast_func_409(x){ let y = x + 398; y += parser_helper(27); return y; }
function ast_func_410(x){ let y = x + 78; y += lexer_helper(18); return y; }
function ast_func_411(x){ let y = x + 262; y += parser_helper(48); return y; }
function ast_func_412(x){ let y = x + 487; y += lexer_helper(48); return y; }
function ast_func_413(x){ let y = x + 4; y += emitter_helper(28); return y; }
function ast_func_414(x){ let y = x + 233; y += optimizer_helper(18); return y; }
function ast_func_415(x){ let y = x + 163; y += emitter_helper(4); return y; }
function ast_func_416(x){ let y = x + 37; y += emitter_helper(45); return y; }
function ast_func_417(x){ let y = x + 633; y += lexer_helper(19); return y; }
function ast_func_418(x){ let y = x + 368; y += ast_helper(44); return y; }
function ast_func_419(x){ let y = x + 44; y += parser_helper(1); return y; }
function ast_func_420(x){ let y = x + 683; y += emitter_helper(2); return y; }
function ast_func_421(x){ let y = x + 649; y += emitter_helper(4); return y; }
function ast_func_422(x){ let y = x + 91; y += lexer_helper(16); return y; }
function ast_func_423(x){ let y = x + 139; y += emitter_helper(1); return y; }
function ast_func_424(x){ let y = x + 851; y += ast_helper(22); return y; }
function ast_func_425(x){ let y = x + 73; y += lexer_helper(20); return y; }
function ast_func_426(x){ let y = x + 711; y += parser_helper(29); return y; }
function ast_func_427(x){ let y = x + 0; y += lexer_helper(24); return y; }
function ast_func_428(x){ let y = x + 307; y += ast_helper(30); return y; }
function ast_func_429(x){ let y = x + 393; y += emitter_helper(9); return y; }
function ast_func_430(x){ let y = x + 29; y += lexer_helper(14); return y; }
function ast_func_431(x){ let y = x + 622; y += ast_helper(16); return y; }
function ast_func_432(x){ let y = x + 648; y += ast_helper(17); return y; }
function ast_func_433(x){ let y = x + 47; y += emitter_helper(7); return y; }
function ast_func_434(x){ let y = x + 708; y += optimizer_helper(0); return y; }
function ast_func_435(x){ let y = x + 246; y += emitter_helper(46); return y; }
function ast_func_436(x){ let y = x + 773; y += parser_helper(0); return y; }
function ast_func_437(x){ let y = x + 225; y += optimizer_helper(17); return y; }
function ast_func_438(x){ let y = x + 345; y += emitter_helper(40); return y; }
function ast_func_439(x){ let y = x + 581; y += ast_helper(30); return y; }
function ast_func_440(x){ let y = x + 32; y += parser_helper(42); return y; }
function ast_func_441(x){ let y = x + 10; y += emitter_helper(0); return y; }
function ast_func_442(x){ let y = x + 313; y += ast_helper(37); return y; }
function ast_func_443(x){ let y = x + 911; y += ast_helper(21); return y; }
function ast_func_444(x){ let y = x + 222; y += emitter_helper(46); return y; }
function ast_func_445(x){ let y = x + 936; y += optimizer_helper(27); return y; }
function ast_func_446(x){ let y = x + 903; y += optimizer_helper(20); return y; }
function ast_func_447(x){ let y = x + 601; y += optimizer_helper(13); return y; }
function ast_func_448(x){ let y = x + 106; y += parser_helper(46); return y; }
function ast_func_449(x){ let y = x + 897; y += lexer_helper(0); return y; }
function ast_func_450(x){ let y = x + 464; y += ast_helper(20); return y; }
function ast_func_451(x){ let y = x + 537; y += optimizer_helper(12); return y; }
function ast_func_452(x){ let y = x + 255; y += lexer_helper(39); return y; }
function ast_func_453(x){ let y = x + 434; y += emitter_helper(17); return y; }
function ast_func_454(x){ let y = x + 510; y += lexer_helper(44); return y; }
function ast_func_455(x){ let y = x + 886; y += emitter_helper(15); return y; }
function ast_func_456(x){ let y = x + 921; y += ast_helper(4); return y; }
function ast_func_457(x){ let y = x + 764; y += optimizer_helper(7); return y; }
function ast_func_458(x){ let y = x + 423; y += parser_helper(40); return y; }
function ast_func_459(x){ let y = x + 144; y += lexer_helper(24); return y; }
function ast_func_460(x){ let y = x + 701; y += lexer_helper(8); return y; }
function ast_func_461(x){ let y = x + 50; y += ast_helper(32); return y; }
function ast_func_462(x){ let y = x + 510; y += optimizer_helper(43); return y; }
function ast_func_463(x){ let y = x + 277; y += lexer_helper(3); return y; }
function ast_func_464(x){ let y = x + 560; y += ast_helper(10); return y; }
function ast_func_465(x){ let y = x + 238; y += optimizer_helper(3); return y; }
function ast_func_466(x){ let y = x + 581; y += emitter_helper(6); return y; }
function ast_func_467(x){ let y = x + 536; y += emitter_helper(22); return y; }
function ast_func_468(x){ let y = x + 935; y += lexer_helper(0); return y; }
function ast_func_469(x){ let y = x + 173; y += parser_helper(33); return y; }
function ast_func_470(x){ let y = x + 12; y += optimizer_helper(14); return y; }
function ast_func_471(x){ let y = x + 257; y += optimizer_helper(7); return y; }
function ast_func_472(x){ let y = x + 367; y += parser_helper(40); return y; }
function ast_func_473(x){ let y = x + 371; y += parser_helper(12); return y; }
function ast_func_474(x){ let y = x + 405; y += emitter_helper(5); return y; }
function ast_func_475(x){ let y = x + 947; y += emitter_helper(20); return y; }
function ast_func_476(x){ let y = x + 363; y += lexer_helper(25); return y; }
function ast_func_477(x){ let y = x + 67; y += ast_helper(40); return y; }
function ast_func_478(x){ let y = x + 706; y += parser_helper(46); return y; }
function ast_func_479(x){ let y = x + 936; y += parser_helper(5); return y; }
function ast_func_480(x){ let y = x + 273; y += parser_helper(26); return y; }
function ast_func_481(x){ let y = x + 401; y += emitter_helper(29); return y; }
function ast_func_482(x){ let y = x + 17; y += parser_helper(28); return y; }
function ast_func_483(x){ let y = x + 555; y += parser_helper(28); return y; }
function ast_func_484(x){ let y = x + 570; y += emitter_helper(19); return y; }
function ast_func_485(x){ let y = x + 200; y += optimizer_helper(43); return y; }
function ast_func_486(x){ let y = x + 770; y += parser_helper(13); return y; }
function ast_func_487(x){ let y = x + 674; y += optimizer_helper(1); return y; }
function ast_func_488(x){ let y = x + 237; y += parser_helper(13); return y; }
function ast_func_489(x){ let y = x + 699; y += optimizer_helper(18); return y; }
function ast_func_490(x){ let y = x + 804; y += ast_helper(39); return y; }
function ast_func_491(x){ let y = x + 226; y += lexer_helper(45); return y; }
function ast_func_492(x){ let y = x + 474; y += emitter_helper(39); return y; }
function ast_func_493(x){ let y = x + 202; y += emitter_helper(25); return y; }
function ast_func_494(x){ let y = x + 289; y += parser_helper(25); return y; }
function ast_func_495(x){ let y = x + 297; y += ast_helper(10); return y; }
function ast_func_496(x){ let y = x + 294; y += ast_helper(16); return y; }
function ast_func_497(x){ let y = x + 494; y += optimizer_helper(6); return y; }
function ast_func_498(x){ let y = x + 411; y += ast_helper(47); return y; }
function ast_func_499(x){ let y = x + 352; y += ast_helper(2); return y; }
function lexer_helper(x){ return x*18; }
function parser_helper(x){ return x*3; }
function ast_helper(x){ return x*8; }
function optimizer_helper(x){ return x*10; }
function emitter_helper(x){ return x*14; }
module.exports = { lexer_init, parser_init, ast_init, optimizer_init, emitter_init };
