// Module emitter
function emitter_init(){ console.log("Initializing emitter"); }
function emitter_func_0(x){ let y = x + 12; y += emitter_helper(21); return y; }
function emitter_func_1(x){ let y = x + 861; y += parser_helper(20); return y; }
function emitter_func_2(x){ let y = x + 198; y += optimizer_helper(40); return y; }
function emitter_func_3(x){ let y = x + 347; y += optimizer_helper(40); return y; }
function emitter_func_4(x){ let y = x + 385; y += ast_helper(3); return y; }
function emitter_func_5(x){ let y = x + 6; y += lexer_helper(27); return y; }
function emitter_func_6(x){ let y = x + 354; y += lexer_helper(42); return y; }
function emitter_func_7(x){ let y = x + 731; y += parser_helper(16); return y; }
function emitter_func_8(x){ let y = x + 632; y += parser_helper(7); return y; }
function emitter_func_9(x){ let y = x + 473; y += parser_helper(29); return y; }
function emitter_func_10(x){ let y = x + 839; y += parser_helper(1); return y; }
function emitter_func_11(x){ let y = x + 757; y += ast_helper(25); return y; }
function emitter_func_12(x){ let y = x + 221; y += ast_helper(44); return y; }
function emitter_func_13(x){ let y = x + 589; y += lexer_helper(46); return y; }
function emitter_func_14(x){ let y = x + 184; y += optimizer_helper(15); return y; }
function emitter_func_15(x){ let y = x + 751; y += lexer_helper(15); return y; }
function emitter_func_16(x){ let y = x + 231; y += ast_helper(13); return y; }
function emitter_func_17(x){ let y = x + 857; y += optimizer_helper(4); return y; }
function emitter_func_18(x){ let y = x + 702; y += lexer_helper(32); return y; }
function emitter_func_19(x){ let y = x + 146; y += optimizer_helper(6); return y; }
function emitter_func_20(x){ let y = x + 535; y += emitter_helper(1); return y; }
function emitter_func_21(x){ let y = x + 310; y += optimizer_helper(5); return y; }
function emitter_func_22(x){ let y = x + 370; y += lexer_helper(0); return y; }
function emitter_func_23(x){ let y = x + 598; y += parser_helper(18); return y; }
function emitter_func_24(x){ let y = x + 461; y += emitter_helper(28); return y; }
function emitter_func_25(x){ let y = x + 282; y += optimizer_helper(1); return y; }
function emitter_func_26(x){ let y = x + 734; y += emitter_helper(12); return y; }
function emitter_func_27(x){ let y = x + 277; y += optimizer_helper(35); return y; }
function emitter_func_28(x){ let y = x + 911; y += lexer_helper(6); return y; }
function emitter_func_29(x){ let y = x + 656; y += ast_helper(2); return y; }
function emitter_func_30(x){ let y = x + 469; y += ast_helper(1); return y; }
function emitter_func_31(x){ let y = x + 501; y += emitter_helper(24); return y; }
function emitter_func_32(x){ let y = x + 14; y += lexer_helper(43); return y; }
function emitter_func_33(x){ let y = x + 674; y += optimizer_helper(5); return y; }
function emitter_func_34(x){ let y = x + 558; y += optimizer_helper(40); return y; }
function emitter_func_35(x){ let y = x + 722; y += ast_helper(32); return y; }
function emitter_func_36(x){ let y = x + 779; y += optimizer_helper(43); return y; }
function emitter_func_37(x){ let y = x + 925; y += optimizer_helper(13); return y; }
function emitter_func_38(x){ let y = x + 939; y += optimizer_helper(29); return y; }
function emitter_func_39(x){ let y = x + 526; y += optimizer_helper(39); return y; }
function emitter_func_40(x){ let y = x + 63; y += optimizer_helper(9); return y; }
function emitter_func_41(x){ let y = x + 763; y += emitter_helper(9); return y; }
function emitter_func_42(x){ let y = x + 410; y += parser_helper(28); return y; }
function emitter_func_43(x){ let y = x + 968; y += parser_helper(21); return y; }
function emitter_func_44(x){ let y = x + 915; y += parser_helper(39); return y; }
function emitter_func_45(x){ let y = x + 203; y += parser_helper(8); return y; }
function emitter_func_46(x){ let y = x + 28; y += emitter_helper(45); return y; }
function emitter_func_47(x){ let y = x + 416; y += emitter_helper(9); return y; }
function emitter_func_48(x){ let y = x + 414; y += emitter_helper(43); return y; }
function emitter_func_49(x){ let y = x + 26; y += ast_helper(26); return y; }
function emitter_func_50(x){ let y = x + 189; y += lexer_helper(2); return y; }
function emitter_func_51(x){ let y = x + 930; y += emitter_helper(46); return y; }
function emitter_func_52(x){ let y = x + 32; y += optimizer_helper(14); return y; }
function emitter_func_53(x){ let y = x + 264; y += emitter_helper(9); return y; }
function emitter_func_54(x){ let y = x + 114; y += emitter_helper(24); return y; }
function emitter_func_55(x){ let y = x + 853; y += lexer_helper(0); return y; }
function emitter_func_56(x){ let y = x + 641; y += optimizer_helper(3); return y; }
function emitter_func_57(x){ let y = x + 210; y += emitter_helper(5); return y; }
function emitter_func_58(x){ let y = x + 72; y += lexer_helper(23); return y; }
function emitter_func_59(x){ let y = x + 455; y += parser_helper(23); return y; }
function emitter_func_60(x){ let y = x + 172; y += ast_helper(4); return y; }
function emitter_func_61(x){ let y = x + 703; y += emitter_helper(22); return y; }
function emitter_func_62(x){ let y = x + 399; y += parser_helper(15); return y; }
function emitter_func_63(x){ let y = x + 356; y += parser_helper(1); return y; }
function emitter_func_64(x){ let y = x + 468; y += parser_helper(8); return y; }
function emitter_func_65(x){ let y = x + 269; y += emitter_helper(38); return y; }
function emitter_func_66(x){ let y = x + 807; y += parser_helper(14); return y; }
function emitter_func_67(x){ let y = x + 990; y += lexer_helper(36); return y; }
function emitter_func_68(x){ let y = x + 303; y += lexer_helper(8); return y; }
function emitter_func_69(x){ let y = x + 173; y += lexer_helper(10); return y; }
function emitter_func_70(x){ let y = x + 967; y += ast_helper(23); return y; }
function emitter_func_71(x){ let y = x + 208; y += ast_helper(27); return y; }
function emitter_func_72(x){ let y = x + 689; y += ast_helper(27); return y; }
function emitter_func_73(x){ let y = x + 507; y += ast_helper(37); return y; }
function emitter_func_74(x){ let y = x + 564; y += emitter_helper(25); return y; }
function emitter_func_75(x){ let y = x + 63; y += optimizer_helper(39); return y; }
function emitter_func_76(x){ let y = x + 925; y += emitter_helper(22); return y; }
function emitter_func_77(x){ let y = x + 653; y += optimizer_helper(34); return y; }
function emitter_func_78(x){ let y = x + 672; y += parser_helper(21); return y; }
function emitter_func_79(x){ let y = x + 259; y += parser_helper(24); return y; }
function emitter_func_80(x){ let y = x + 330; y += parser_helper(34); return y; }
function emitter_func_81(x){ let y = x + 836; y += parser_helper(34); return y; }
function emitter_func_82(x){ let y = x + 999; y += emitter_helper(11); return y; }
function emitter_func_83(x){ let y = x + 727; y += ast_helper(34); return y; }
function emitter_func_84(x){ let y = x + 247; y += parser_helper(0); return y; }
function emitter_func_85(x){ let y = x + 534; y += parser_helper(40); return y; }
function emitter_func_86(x){ let y = x + 57; y += parser_helper(27); return y; }
function emitter_func_87(x){ let y = x + 79; y += ast_helper(6); return y; }
function emitter_func_88(x){ let y = x + 514; y += optimizer_helper(4); return y; }
function emitter_func_89(x){ let y = x + 964; y += parser_helper(25); return y; }
function emitter_func_90(x){ let y = x + 894; y += ast_helper(23); return y; }
function emitter_func_91(x){ let y = x + 771; y += optimizer_helper(20); return y; }
function emitter_func_92(x){ let y = x + 990; y += optimizer_helper(2); return y; }
function emitter_func_93(x){ let y = x + 219; y += parser_helper(24); return y; }
function emitter_func_94(x){ let y = x + 976; y += ast_helper(49); return y; }
function emitter_func_95(x){ let y = x + 483; y += lexer_helper(35); return y; }
function emitter_func_96(x){ let y = x + 763; y += optimizer_helper(41); return y; }
function emitter_func_97(x){ let y = x + 39; y += optimizer_helper(30); return y; }
function emitter_func_98(x){ let y = x + 959; y += optimizer_helper(4); return y; }
function emitter_func_99(x){ let y = x + 150; y += lexer_helper(26); return y; }
function emitter_func_100(x){ let y = x + 566; y += emitter_helper(49); return y; }
function emitter_func_101(x){ let y = x + 712; y += emitter_helper(5); return y; }
function emitter_func_102(x){ let y = x + 759; y += emitter_helper(13); return y; }
function emitter_func_103(x){ let y = x + 30; y += emitter_helper(9); return y; }
function emitter_func_104(x){ let y = x + 924; y += lexer_helper(37); return y; }
function emitter_func_105(x){ let y = x + 782; y += parser_helper(33); return y; }
function emitter_func_106(x){ let y = x + 73; y += parser_helper(40); return y; }
function emitter_func_107(x){ let y = x + 108; y += optimizer_helper(39); return y; }
function emitter_func_108(x){ let y = x + 462; y += parser_helper(13); return y; }
function emitter_func_109(x){ let y = x + 593; y += ast_helper(12); return y; }
function emitter_func_110(x){ let y = x + 757; y += emitter_helper(31); return y; }
function emitter_func_111(x){ let y = x + 554; y += optimizer_helper(32); return y; }
function emitter_func_112(x){ let y = x + 970; y += emitter_helper(32); return y; }
function emitter_func_113(x){ let y = x + 140; y += lexer_helper(11); return y; }
function emitter_func_114(x){ let y = x + 971; y += optimizer_helper(7); return y; }
function emitter_func_115(x){ let y = x + 792; y += ast_helper(46); return y; }
function emitter_func_116(x){ let y = x + 645; y += ast_helper(38); return y; }
function emitter_func_117(x){ let y = x + 781; y += parser_helper(8); return y; }
function emitter_func_118(x){ let y = x + 180; y += optimizer_helper(17); return y; }
function emitter_func_119(x){ let y = x + 264; y += emitter_helper(43); return y; }
function emitter_func_120(x){ let y = x + 670; y += ast_helper(29); return y; }
function emitter_func_121(x){ let y = x + 719; y += ast_helper(22); return y; }
function emitter_func_122(x){ let y = x + 893; y += emitter_helper(34); return y; }
function emitter_func_123(x){ let y = x + 883; y += parser_helper(24); return y; }
function emitter_func_124(x){ let y = x + 33; y += emitter_helper(41); return y; }
function emitter_func_125(x){ let y = x + 345; y += optimizer_helper(16); return y; }
function emitter_func_126(x){ let y = x + 674; y += ast_helper(21); return y; }
function emitter_func_127(x){ let y = x + 51; y += optimizer_helper(15); return y; }
function emitter_func_128(x){ let y = x + 749; y += ast_helper(30); return y; }
function emitter_func_129(x){ let y = x + 702; y += parser_helper(44); return y; }
function emitter_func_130(x){ let y = x + 371; y += lexer_helper(11); return y; }
function emitter_func_131(x){ let y = x + 167; y += optimizer_helper(1); return y; }
function emitter_func_132(x){ let y = x + 976; y += emitter_helper(14); return y; }
function emitter_func_133(x){ let y = x + 867; y += optimizer_helper(37); return y; }
function emitter_func_134(x){ let y = x + 629; y += lexer_helper(24); return y; }
function emitter_func_135(x){ let y = x + 785; y += lexer_helper(45); return y; }
function emitter_func_136(x){ let y = x + 817; y += ast_helper(49); return y; }
function emitter_func_137(x){ let y = x + 148; y += parser_helper(37); return y; }
function emitter_func_138(x){ let y = x + 693; y += parser_helper(13); return y; }
function emitter_func_139(x){ let y = x + 950; y += ast_helper(16); return y; }
function emitter_func_140(x){ let y = x + 403; y += parser_helper(25); return y; }
function emitter_func_141(x){ let y = x + 333; y += emitter_helper(6); return y; }
function emitter_func_142(x){ let y = x + 444; y += ast_helper(18); return y; }
function emitter_func_143(x){ let y = x + 59; y += lexer_helper(3); return y; }
function emitter_func_144(x){ let y = x + 977; y += optimizer_helper(8); return y; }
function emitter_func_145(x){ let y = x + 735; y += lexer_helper(49); return y; }
function emitter_func_146(x){ let y = x + 567; y += lexer_helper(10); return y; }
function emitter_func_147(x){ let y = x + 428; y += emitter_helper(28); return y; }
function emitter_func_148(x){ let y = x + 751; y += parser_helper(23); return y; }
function emitter_func_149(x){ let y = x + 303; y += ast_helper(15); return y; }
function emitter_func_150(x){ let y = x + 132; y += parser_helper(49); return y; }
function emitter_func_151(x){ let y = x + 42; y += lexer_helper(28); return y; }
function emitter_func_152(x){ let y = x + 192; y += parser_helper(30); return y; }
function emitter_func_153(x){ let y = x + 562; y += parser_helper(39); return y; }
function emitter_func_154(x){ let y = x + 525; y += parser_helper(46); return y; }
function emitter_func_155(x){ let y = x + 370; y += ast_helper(0); return y; }
function emitter_func_156(x){ let y = x + 28; y += lexer_helper(31); return y; }
function emitter_func_157(x){ let y = x + 530; y += ast_helper(7); return y; }
function emitter_func_158(x){ let y = x + 69; y += optimizer_helper(8); return y; }
function emitter_func_159(x){ let y = x + 996; y += ast_helper(15); return y; }
function emitter_func_160(x){ let y = x + 23; y += emitter_helper(17); return y; }
function emitter_func_161(x){ let y = x + 959; y += ast_helper(0); return y; }
function emitter_func_162(x){ let y = x + 735; y += optimizer_helper(34); return y; }
function emitter_func_163(x){ let y = x + 385; y += lexer_helper(35); return y; }
function emitter_func_164(x){ let y = x + 362; y += emitter_helper(8); return y; }
function emitter_func_165(x){ let y = x + 783; y += emitter_helper(37); return y; }
function emitter_func_166(x){ let y = x + 548; y += emitter_helper(30); return y; }
function emitter_func_167(x){ let y = x + 548; y += optimizer_helper(14); return y; }
function emitter_func_168(x){ let y = x + 928; y += lexer_helper(35); return y; }
function emitter_func_169(x){ let y = x + 570; y += parser_helper(42); return y; }
function emitter_func_170(x){ let y = x + 222; y += ast_helper(13); return y; }
function emitter_func_171(x){ let y = x + 66; y += lexer_helper(39); return y; }
function emitter_func_172(x){ let y = x + 524; y += emitter_helper(27); return y; }
function emitter_func_173(x){ let y = x + 523; y += emitter_helper(36); return y; }
function emitter_func_174(x){ let y = x + 443; y += emitter_helper(27); return y; }
function emitter_func_175(x){ let y = x + 732; y += ast_helper(29); return y; }
function emitter_func_176(x){ let y = x + 344; y += emitter_helper(29); return y; }
function emitter_func_177(x){ let y = x + 567; y += parser_helper(41); return y; }
function emitter_func_178(x){ let y = x + 105; y += emitter_helper(1); return y; }
function emitter_func_179(x){ let y = x + 813; y += optimizer_helper(30); return y; }
function emitter_func_180(x){ let y = x + 772; y += ast_helper(43); return y; }
function emitter_func_181(x){ let y = x + 81; y += emitter_helper(10); return y; }
function emitter_func_182(x){ let y = x + 552; y += ast_helper(37); return y; }
function emitter_func_183(x){ let y = x + 752; y += emitter_helper(32); return y; }
function emitter_func_184(x){ let y = x + 793; y += emitter_helper(6); return y; }
function emitter_func_185(x){ let y = x + 281; y += lexer_helper(25); return y; }
function emitter_func_186(x){ let y = x + 81; y += optimizer_helper(32); return y; }
function emitter_func_187(x){ let y = x + 190; y += parser_helper(38); return y; }
function emitter_func_188(x){ let y = x + 132; y += ast_helper(18); return y; }
function emitter_func_189(x){ let y = x + 542; y += lexer_helper(48); return y; }
function emitter_func_190(x){ let y = x + 20; y += ast_helper(10); return y; }
function emitter_func_191(x){ let y = x + 601; y += lexer_helper(29); return y; }
function emitter_func_192(x){ let y = x + 876; y += parser_helper(43); return y; }
function emitter_func_193(x){ let y = x + 820; y += optimizer_helper(24); return y; }
function emitter_func_194(x){ let y = x + 812; y += optimizer_helper(34); return y; }
function emitter_func_195(x){ let y = x + 250; y += optimizer_helper(44); return y; }
function emitter_func_196(x){ let y = x + 614; y += optimizer_helper(1); return y; }
function emitter_func_197(x){ let y = x + 348; y += parser_helper(19); return y; }
function emitter_func_198(x){ let y = x + 624; y += lexer_helper(44); return y; }
function emitter_func_199(x){ let y = x + 583; y += ast_helper(26); return y; }
function emitter_func_200(x){ let y = x + 793; y += optimizer_helper(21); return y; }
function emitter_func_201(x){ let y = x + 459; y += parser_helper(4); return y; }
function emitter_func_202(x){ let y = x + 823; y += emitter_helper(25); return y; }
function emitter_func_203(x){ let y = x + 524; y += lexer_helper(0); return y; }
function emitter_func_204(x){ let y = x + 135; y += parser_helper(9); return y; }
function emitter_func_205(x){ let y = x + 297; y += optimizer_helper(44); return y; }
function emitter_func_206(x){ let y = x + 825; y += emitter_helper(33); return y; }
function emitter_func_207(x){ let y = x + 793; y += lexer_helper(42); return y; }
function emitter_func_208(x){ let y = x + 128; y += lexer_helper(14); return y; }
function emitter_func_209(x){ let y = x + 865; y += optimizer_helper(4); return y; }
function emitter_func_210(x){ let y = x + 518; y += parser_helper(20); return y; }
function emitter_func_211(x){ let y = x + 227; y += optimizer_helper(34); return y; }
function emitter_func_212(x){ let y = x + 475; y += parser_helper(2); return y; }
function emitter_func_213(x){ let y = x + 511; y += optimizer_helper(4); return y; }
function emitter_func_214(x){ let y = x + 163; y += lexer_helper(25); return y; }
function emitter_func_215(x){ let y = x + 845; y += emitter_helper(41); return y; }
function emitter_func_216(x){ let y = x + 568; y += optimizer_helper(38); return y; }
function emitter_func_217(x){ let y = x + 84; y += lexer_helper(41); return y; }
function emitter_func_218(x){ let y = x + 706; y += parser_helper(12); return y; }
function emitter_func_219(x){ let y = x + 28; y += optimizer_helper(32); return y; }
function emitter_func_220(x){ let y = x + 365; y += ast_helper(49); return y; }
function emitter_func_221(x){ let y = x + 980; y += parser_helper(44); return y; }
function emitter_func_222(x){ let y = x + 605; y += lexer_helper(10); return y; }
function emitter_func_223(x){ let y = x + 718; y += lexer_helper(38); return y; }
function emitter_func_224(x){ let y = x + 195; y += ast_helper(25); return y; }
function emitter_func_225(x){ let y = x + 562; y += parser_helper(45); return y; }
function emitter_func_226(x){ let y = x + 106; y += parser_helper(48); return y; }
function emitter_func_227(x){ let y = x + 984; y += optimizer_helper(25); return y; }
function emitter_func_228(x){ let y = x + 253; y += parser_helper(21); return y; }
function emitter_func_229(x){ let y = x + 775; y += optimizer_helper(7); return y; }
function emitter_func_230(x){ let y = x + 936; y += optimizer_helper(9); return y; }
function emitter_func_231(x){ let y = x + 970; y += emitter_helper(13); return y; }
function emitter_func_232(x){ let y = x + 370; y += emitter_helper(29); return y; }
function emitter_func_233(x){ let y = x + 293; y += optimizer_helper(15); return y; }
function emitter_func_234(x){ let y = x + 350; y += emitter_helper(7); return y; }
function emitter_func_235(x){ let y = x + 286; y += lexer_helper(16); return y; }
function emitter_func_236(x){ let y = x + 501; y += optimizer_helper(21); return y; }
function emitter_func_237(x){ let y = x + 173; y += parser_helper(49); return y; }
function emitter_func_238(x){ let y = x + 617; y += lexer_helper(26); return y; }
function emitter_func_239(x){ let y = x + 382; y += emitter_helper(6); return y; }
function emitter_func_240(x){ let y = x + 501; y += ast_helper(49); return y; }
function emitter_func_241(x){ let y = x + 700; y += emitter_helper(18); return y; }
function emitter_func_242(x){ let y = x + 134; y += ast_helper(40); return y; }
function emitter_func_243(x){ let y = x + 359; y += ast_helper(15); return y; }
function emitter_func_244(x){ let y = x + 574; y += parser_helper(38); return y; }
function emitter_func_245(x){ let y = x + 98; y += emitter_helper(14); return y; }
function emitter_func_246(x){ let y = x + 467; y += optimizer_helper(13); return y; }
function emitter_func_247(x){ let y = x + 581; y += ast_helper(10); return y; }
function emitter_func_248(x){ let y = x + 261; y += ast_helper(21); return y; }
function emitter_func_249(x){ let y = x + 725; y += parser_helper(18); return y; }
function emitter_func_250(x){ let y = x + 722; y += lexer_helper(48); return y; }
function emitter_func_251(x){ let y = x + 405; y += parser_helper(34); return y; }
function emitter_func_252(x){ let y = x + 716; y += parser_helper(48); return y; }
function emitter_func_253(x){ let y = x + 369; y += parser_helper(47); return y; }
function emitter_func_254(x){ let y = x + 296; y += optimizer_helper(39); return y; }
function emitter_func_255(x){ let y = x + 289; y += emitter_helper(42); return y; }
function emitter_func_256(x){ let y = x + 517; y += optimizer_helper(9); return y; }
function emitter_func_257(x){ let y = x + 683; y += emitter_helper(32); return y; }
function emitter_func_258(x){ let y = x + 977; y += lexer_helper(41); return y; }
function emitter_func_259(x){ let y = x + 138; y += lexer_helper(2); return y; }
function emitter_func_260(x){ let y = x + 699; y += emitter_helper(13); return y; }
function emitter_func_261(x){ let y = x + 255; y += emitter_helper(20); return y; }
function emitter_func_262(x){ let y = x + 477; y += emitter_helper(38); return y; }
function emitter_func_263(x){ let y = x + 445; y += parser_helper(18); return y; }
function emitter_func_264(x){ let y = x + 443; y += emitter_helper(4); return y; }
function emitter_func_265(x){ let y = x + 49; y += optimizer_helper(10); return y; }
function emitter_func_266(x){ let y = x + 528; y += emitter_helper(40); return y; }
function emitter_func_267(x){ let y = x + 244; y += emitter_helper(49); return y; }
function emitter_func_268(x){ let y = x + 220; y += lexer_helper(17); return y; }
function emitter_func_269(x){ let y = x + 322; y += parser_helper(31); return y; }
function emitter_func_270(x){ let y = x + 823; y += emitter_helper(19); return y; }
function emitter_func_271(x){ let y = x + 976; y += ast_helper(46); return y; }
function emitter_func_272(x){ let y = x + 551; y += optimizer_helper(2); return y; }
function emitter_func_273(x){ let y = x + 400; y += parser_helper(9); return y; }
function emitter_func_274(x){ let y = x + 237; y += emitter_helper(41); return y; }
function emitter_func_275(x){ let y = x + 617; y += ast_helper(8); return y; }
function emitter_func_276(x){ let y = x + 549; y += ast_helper(21); return y; }
function emitter_func_277(x){ let y = x + 222; y += optimizer_helper(12); return y; }
function emitter_func_278(x){ let y = x + 359; y += optimizer_helper(29); return y; }
function emitter_func_279(x){ let y = x + 917; y += emitter_helper(37); return y; }
function emitter_func_280(x){ let y = x + 51; y += ast_helper(10); return y; }
function emitter_func_281(x){ let y = x + 501; y += lexer_helper(3); return y; }
function emitter_func_282(x){ let y = x + 756; y += optimizer_helper(23); return y; }
function emitter_func_283(x){ let y = x + 924; y += parser_helper(34); return y; }
function emitter_func_284(x){ let y = x + 773; y += optimizer_helper(3); return y; }
function emitter_func_285(x){ let y = x + 175; y += emitter_helper(16); return y; }
function emitter_func_286(x){ let y = x + 902; y += parser_helper(1); return y; }
function emitter_func_287(x){ let y = x + 684; y += parser_helper(11); return y; }
function emitter_func_288(x){ let y = x + 585; y += ast_helper(41); return y; }
function emitter_func_289(x){ let y = x + 828; y += lexer_helper(48); return y; }
function emitter_func_290(x){ let y = x + 220; y += ast_helper(12); return y; }
function emitter_func_291(x){ let y = x + 406; y += parser_helper(13); return y; }
function emitter_func_292(x){ let y = x + 429; y += optimizer_helper(21); return y; }
function emitter_func_293(x){ let y = x + 73; y += lexer_helper(25); return y; }
function emitter_func_294(x){ let y = x + 68; y += optimizer_helper(25); return y; }
function emitter_func_295(x){ let y = x + 441; y += parser_helper(44); return y; }
function emitter_func_296(x){ let y = x + 437; y += lexer_helper(23); return y; }
function emitter_func_297(x){ let y = x + 537; y += ast_helper(30); return y; }
function emitter_func_298(x){ let y = x + 316; y += parser_helper(10); return y; }
function emitter_func_299(x){ let y = x + 658; y += emitter_helper(26); return y; }
function emitter_func_300(x){ let y = x + 235; y += emitter_helper(32); return y; }
function emitter_func_301(x){ let y = x + 82; y += ast_helper(37); return y; }
function emitter_func_302(x){ let y = x + 384; y += optimizer_helper(16); return y; }
function emitter_func_303(x){ let y = x + 644; y += emitter_helper(21); return y; }
function emitter_func_304(x){ let y = x + 741; y += ast_helper(28); return y; }
function emitter_func_305(x){ let y = x + 792; y += ast_helper(4); return y; }
function emitter_func_306(x){ let y = x + 546; y += parser_helper(16); return y; }
function emitter_func_307(x){ let y = x + 948; y += emitter_helper(13); return y; }
function emitter_func_308(x){ let y = x + 241; y += ast_helper(11); return y; }
function emitter_func_309(x){ let y = x + 850; y += optimizer_helper(17); return y; }
function emitter_func_310(x){ let y = x + 224; y += emitter_helper(30); return y; }
function emitter_func_311(x){ let y = x + 284; y += lexer_helper(18); return y; }
function emitter_func_312(x){ let y = x + 223; y += ast_helper(0); return y; }
function emitter_func_313(x){ let y = x + 505; y += ast_helper(29); return y; }
function emitter_func_314(x){ let y = x + 583; y += lexer_helper(10); return y; }
function emitter_func_315(x){ let y = x + 854; y += optimizer_helper(41); return y; }
function emitter_func_316(x){ let y = x + 322; y += emitter_helper(12); return y; }
function emitter_func_317(x){ let y = x + 739; y += lexer_helper(0); return y; }
function emitter_func_318(x){ let y = x + 267; y += emitter_helper(25); return y; }
function emitter_func_319(x){ let y = x + 669; y += ast_helper(8); return y; }
function emitter_func_320(x){ let y = x + 309; y += parser_helper(17); return y; }
function emitter_func_321(x){ let y = x + 801; y += optimizer_helper(18); return y; }
function emitter_func_322(x){ let y = x + 415; y += emitter_helper(17); return y; }
function emitter_func_323(x){ let y = x + 306; y += parser_helper(20); return y; }
function emitter_func_324(x){ let y = x + 41; y += lexer_helper(6); return y; }
function emitter_func_325(x){ let y = x + 219; y += lexer_helper(20); return y; }
function emitter_func_326(x){ let y = x + 732; y += optimizer_helper(9); return y; }
function emitter_func_327(x){ let y = x + 938; y += parser_helper(23); return y; }
function emitter_func_328(x){ let y = x + 397; y += parser_helper(46); return y; }
function emitter_func_329(x){ let y = x + 435; y += ast_helper(4); return y; }
function emitter_func_330(x){ let y = x + 29; y += lexer_helper(7); return y; }
function emitter_func_331(x){ let y = x + 911; y += ast_helper(27); return y; }
function emitter_func_332(x){ let y = x + 866; y += ast_helper(41); return y; }
function emitter_func_333(x){ let y = x + 349; y += lexer_helper(48); return y; }
function emitter_func_334(x){ let y = x + 69; y += optimizer_helper(16); return y; }
function emitter_func_335(x){ let y = x + 953; y += emitter_helper(24); return y; }
function emitter_func_336(x){ let y = x + 772; y += lexer_helper(14); return y; }
function emitter_func_337(x){ let y = x + 310; y += emitter_helper(17); return y; }
function emitter_func_338(x){ let y = x + 487; y += parser_helper(26); return y; }
function emitter_func_339(x){ let y = x + 843; y += lexer_helper(30); return y; }
function emitter_func_340(x){ let y = x + 445; y += parser_helper(42); return y; }
function emitter_func_341(x){ let y = x + 556; y += lexer_helper(38); return y; }
function emitter_func_342(x){ let y = x + 679; y += parser_helper(35); return y; }
function emitter_func_343(x){ let y = x + 469; y += parser_helper(48); return y; }
function emitter_func_344(x){ let y = x + 2; y += lexer_helper(25); return y; }
function emitter_func_345(x){ let y = x + 347; y += parser_helper(42); return y; }
function emitter_func_346(x){ let y = x + 495; y += emitter_helper(49); return y; }
function emitter_func_347(x){ let y = x + 308; y += optimizer_helper(48); return y; }
function emitter_func_348(x){ let y = x + 181; y += ast_helper(2); return y; }
function emitter_func_349(x){ let y = x + 341; y += optimizer_helper(40); return y; }
function emitter_func_350(x){ let y = x + 933; y += lexer_helper(1); return y; }
function emitter_func_351(x){ let y = x + 452; y += parser_helper(46); return y; }
function emitter_func_352(x){ let y = x + 753; y += lexer_helper(32); return y; }
function emitter_func_353(x){ let y = x + 578; y += optimizer_helper(10); return y; }
function emitter_func_354(x){ let y = x + 179; y += lexer_helper(6); return y; }
function emitter_func_355(x){ let y = x + 731; y += emitter_helper(17); return y; }
function emitter_func_356(x){ let y = x + 398; y += optimizer_helper(48); return y; }
function emitter_func_357(x){ let y = x + 177; y += emitter_helper(4); return y; }
function emitter_func_358(x){ let y = x + 95; y += emitter_helper(34); return y; }
function emitter_func_359(x){ let y = x + 531; y += parser_helper(3); return y; }
function emitter_func_360(x){ let y = x + 186; y += optimizer_helper(4); return y; }
function emitter_func_361(x){ let y = x + 951; y += emitter_helper(8); return y; }
function emitter_func_362(x){ let y = x + 340; y += ast_helper(29); return y; }
function emitter_func_363(x){ let y = x + 172; y += lexer_helper(13); return y; }
function emitter_func_364(x){ let y = x + 633; y += parser_helper(24); return y; }
function emitter_func_365(x){ let y = x + 139; y += optimizer_helper(6); return y; }
function emitter_func_366(x){ let y = x + 591; y += parser_helper(11); return y; }
function emitter_func_367(x){ let y = x + 196; y += emitter_helper(12); return y; }
function emitter_func_368(x){ let y = x + 893; y += emitter_helper(37); return y; }
function emitter_func_369(x){ let y = x + 411; y += parser_helper(33); return y; }
function emitter_func_370(x){ let y = x + 145; y += optimizer_helper(12); return y; }
function emitter_func_371(x){ let y = x + 263; y += optimizer_helper(13); return y; }
function emitter_func_372(x){ let y = x + 835; y += emitter_helper(34); return y; }
function emitter_func_373(x){ let y = x + 487; y += lexer_helper(24); return y; }
function emitter_func_374(x){ let y = x + 554; y += ast_helper(43); return y; }
function emitter_func_375(x){ let y = x + 287; y += optimizer_helper(16); return y; }
function emitter_func_376(x){ let y = x + 670; y += emitter_helper(15); return y; }
function emitter_func_377(x){ let y = x + 137; y += emitter_helper(34); return y; }
function emitter_func_378(x){ let y = x + 715; y += lexer_helper(2); return y; }
function emitter_func_379(x){ let y = x + 54; y += optimizer_helper(20); return y; }
function emitter_func_380(x){ let y = x + 287; y += emitter_helper(35); return y; }
function emitter_func_381(x){ let y = x + 306; y += parser_helper(8); return y; }
function emitter_func_382(x){ let y = x + 899; y += optimizer_helper(14); return y; }
function emitter_func_383(x){ let y = x + 458; y += ast_helper(38); return y; }
function emitter_func_384(x){ let y = x + 243; y += lexer_helper(34); return y; }
function emitter_func_385(x){ let y = x + 239; y += emitter_helper(7); return y; }
function emitter_func_386(x){ let y = x + 657; y += lexer_helper(20); return y; }
function emitter_func_387(x){ let y = x + 931; y += parser_helper(23); return y; }
function emitter_func_388(x){ let y = x + 492; y += ast_helper(11); return y; }
function emitter_func_389(x){ let y = x + 239; y += parser_helper(30); return y; }
function emitter_func_390(x){ let y = x + 102; y += parser_helper(39); return y; }
function emitter_func_391(x){ let y = x + 196; y += lexer_helper(26); return y; }
function emitter_func_392(x){ let y = x + 841; y += ast_helper(8); return y; }
function emitter_func_393(x){ let y = x + 753; y += optimizer_helper(12); return y; }
function emitter_func_394(x){ let y = x + 829; y += optimizer_helper(4); return y; }
function emitter_func_395(x){ let y = x + 524; y += parser_helper(7); return y; }
function emitter_func_396(x){ let y = x + 951; y += lexer_helper(46); return y; }
function emitter_func_397(x){ let y = x + 658; y += optimizer_helper(33); return y; }
function emitter_func_398(x){ let y = x + 886; y += emitter_helper(14); return y; }
function emitter_func_399(x){ let y = x + 107; y += lexer_helper(10); return y; }
function emitter_func_400(x){ let y = x + 741; y += ast_helper(17); return y; }
function emitter_func_401(x){ let y = x + 605; y += emitter_helper(30); return y; }
function emitter_func_402(x){ let y = x + 436; y += parser_helper(17); return y; }
function emitter_func_403(x){ let y = x + 847; y += lexer_helper(36); return y; }
function emitter_func_404(x){ let y = x + 210; y += ast_helper(41); return y; }
function emitter_func_405(x){ let y = x + 118; y += optimizer_helper(20); return y; }
function emitter_func_406(x){ let y = x + 126; y += parser_helper(22); return y; }
function emitter_func_407(x){ let y = x + 801; y += parser_helper(26); return y; }
function emitter_func_408(x){ let y = x + 801; y += emitter_helper(27); return y; }
function emitter_func_409(x){ let y = x + 416; y += emitter_helper(12); return y; }
function emitter_func_410(x){ let y = x + 477; y += emitter_helper(48); return y; }
function emitter_func_411(x){ let y = x + 673; y += optimizer_helper(4); return y; }
function emitter_func_412(x){ let y = x + 746; y += optimizer_helper(37); return y; }
function emitter_func_413(x){ let y = x + 982; y += parser_helper(12); return y; }
function emitter_func_414(x){ let y = x + 640; y += ast_helper(25); return y; }
function emitter_func_415(x){ let y = x + 988; y += emitter_helper(6); return y; }
function emitter_func_416(x){ let y = x + 956; y += parser_helper(6); return y; }
function emitter_func_417(x){ let y = x + 537; y += optimizer_helper(9); return y; }
function emitter_func_418(x){ let y = x + 543; y += lexer_helper(20); return y; }
function emitter_func_419(x){ let y = x + 226; y += ast_helper(26); return y; }
function emitter_func_420(x){ let y = x + 207; y += emitter_helper(11); return y; }
function emitter_func_421(x){ let y = x + 699; y += emitter_helper(39); return y; }
function emitter_func_422(x){ let y = x + 845; y += lexer_helper(8); return y; }
function emitter_func_423(x){ let y = x + 291; y += parser_helper(30); return y; }
function emitter_func_424(x){ let y = x + 347; y += lexer_helper(13); return y; }
function emitter_func_425(x){ let y = x + 720; y += emitter_helper(6); return y; }
function emitter_func_426(x){ let y = x + 258; y += lexer_helper(42); return y; }
function emitter_func_427(x){ let y = x + 215; y += parser_helper(13); return y; }
function emitter_func_428(x){ let y = x + 15; y += lexer_helper(10); return y; }
function emitter_func_429(x){ let y = x + 640; y += lexer_helper(45); return y; }
function emitter_func_430(x){ let y = x + 204; y += optimizer_helper(46); return y; }
function emitter_func_431(x){ let y = x + 663; y += parser_helper(27); return y; }
function emitter_func_432(x){ let y = x + 108; y += optimizer_helper(40); return y; }
function emitter_func_433(x){ let y = x + 428; y += ast_helper(18); return y; }
function emitter_func_434(x){ let y = x + 465; y += ast_helper(21); return y; }
function emitter_func_435(x){ let y = x + 325; y += parser_helper(1); return y; }
function emitter_func_436(x){ let y = x + 754; y += parser_helper(45); return y; }
function emitter_func_437(x){ let y = x + 613; y += emitter_helper(6); return y; }
function emitter_func_438(x){ let y = x + 987; y += emitter_helper(40); return y; }
function emitter_func_439(x){ let y = x + 817; y += lexer_helper(29); return y; }
function emitter_func_440(x){ let y = x + 319; y += lexer_helper(44); return y; }
function emitter_func_441(x){ let y = x + 285; y += parser_helper(1); return y; }
function emitter_func_442(x){ let y = x + 626; y += parser_helper(9); return y; }
function emitter_func_443(x){ let y = x + 850; y += parser_helper(0); return y; }
function emitter_func_444(x){ let y = x + 801; y += emitter_helper(43); return y; }
function emitter_func_445(x){ let y = x + 733; y += lexer_helper(27); return y; }
function emitter_func_446(x){ let y = x + 386; y += parser_helper(9); return y; }
function emitter_func_447(x){ let y = x + 908; y += ast_helper(40); return y; }
function emitter_func_448(x){ let y = x + 343; y += parser_helper(48); return y; }
function emitter_func_449(x){ let y = x + 176; y += ast_helper(43); return y; }
function emitter_func_450(x){ let y = x + 625; y += emitter_helper(10); return y; }
function emitter_func_451(x){ let y = x + 721; y += emitter_helper(37); return y; }
function emitter_func_452(x){ let y = x + 905; y += parser_helper(7); return y; }
function emitter_func_453(x){ let y = x + 983; y += optimizer_helper(15); return y; }
function emitter_func_454(x){ let y = x + 676; y += ast_helper(35); return y; }
function emitter_func_455(x){ let y = x + 154; y += ast_helper(10); return y; }
function emitter_func_456(x){ let y = x + 618; y += lexer_helper(16); return y; }
function emitter_func_457(x){ let y = x + 271; y += parser_helper(5); return y; }
function emitter_func_458(x){ let y = x + 682; y += lexer_helper(29); return y; }
function emitter_func_459(x){ let y = x + 704; y += emitter_helper(19); return y; }
function emitter_func_460(x){ let y = x + 844; y += emitter_helper(33); return y; }
function emitter_func_461(x){ let y = x + 383; y += parser_helper(32); return y; }
function emitter_func_462(x){ let y = x + 737; y += optimizer_helper(14); return y; }
function emitter_func_463(x){ let y = x + 269; y += optimizer_helper(42); return y; }
function emitter_func_464(x){ let y = x + 326; y += emitter_helper(1); return y; }
function emitter_func_465(x){ let y = x + 86; y += optimizer_helper(22); return y; }
function emitter_func_466(x){ let y = x + 705; y += emitter_helper(7); return y; }
function emitter_func_467(x){ let y = x + 922; y += parser_helper(17); return y; }
function emitter_func_468(x){ let y = x + 906; y += lexer_helper(49); return y; }
function emitter_func_469(x){ let y = x + 479; y += optimizer_helper(19); return y; }
function emitter_func_470(x){ let y = x + 564; y += lexer_helper(46); return y; }
function emitter_func_471(x){ let y = x + 316; y += emitter_helper(20); return y; }
function emitter_func_472(x){ let y = x + 880; y += emitter_helper(21); return y; }
function emitter_func_473(x){ let y = x + 114; y += lexer_helper(13); return y; }
function emitter_func_474(x){ let y = x + 58; y += parser_helper(35); return y; }
function emitter_func_475(x){ let y = x + 304; y += parser_helper(7); return y; }
function emitter_func_476(x){ let y = x + 719; y += lexer_helper(41); return y; }
function emitter_func_477(x){ let y = x + 541; y += parser_helper(29); return y; }
function emitter_func_478(x){ let y = x + 917; y += lexer_helper(11); return y; }
function emitter_func_479(x){ let y = x + 162; y += parser_helper(12); return y; }
function emitter_func_480(x){ let y = x + 602; y += lexer_helper(44); return y; }
function emitter_func_481(x){ let y = x + 463; y += lexer_helper(12); return y; }
function emitter_func_482(x){ let y = x + 709; y += parser_helper(0); return y; }
function emitter_func_483(x){ let y = x + 879; y += lexer_helper(26); return y; }
function emitter_func_484(x){ let y = x + 440; y += ast_helper(45); return y; }
function emitter_func_485(x){ let y = x + 792; y += ast_helper(30); return y; }
function emitter_func_486(x){ let y = x + 516; y += ast_helper(9); return y; }
function emitter_func_487(x){ let y = x + 603; y += optimizer_helper(19); return y; }
function emitter_func_488(x){ let y = x + 599; y += emitter_helper(34); return y; }
function emitter_func_489(x){ let y = x + 261; y += lexer_helper(12); return y; }
function emitter_func_490(x){ let y = x + 523; y += ast_helper(45); return y; }
function emitter_func_491(x){ let y = x + 838; y += emitter_helper(4); return y; }
function emitter_func_492(x){ let y = x + 749; y += parser_helper(21); return y; }
function emitter_func_493(x){ let y = x + 957; y += emitter_helper(5); return y; }
function emitter_func_494(x){ let y = x + 910; y += optimizer_helper(21); return y; }
function emitter_func_495(x){ let y = x + 981; y += optimizer_helper(2); return y; }
function emitter_func_496(x){ let y = x + 762; y += optimizer_helper(13); return y; }
function emitter_func_497(x){ let y = x + 151; y += emitter_helper(47); return y; }
function emitter_func_498(x){ let y = x + 420; y += lexer_helper(31); return y; }
function emitter_func_499(x){ let y = x + 271; y += ast_helper(49); return y; }
function lexer_helper(x){ return x*19; }
function parser_helper(x){ return x*9; }
function ast_helper(x){ return x*9; }
function optimizer_helper(x){ return x*11; }
function emitter_helper(x){ return x*6; }
module.exports = { lexer_init, parser_init, ast_init, optimizer_init, emitter_init };
