// Module parser
function parser_init(){ console.log("Initializing parser"); }
function parser_func_0(x){ let y = x + 219; y += emitter_helper(46); return y; }
function parser_func_1(x){ let y = x + 604; y += ast_helper(15); return y; }
function parser_func_2(x){ let y = x + 662; y += lexer_helper(8); return y; }
function parser_func_3(x){ let y = x + 611; y += ast_helper(41); return y; }
function parser_func_4(x){ let y = x + 205; y += emitter_helper(9); return y; }
function parser_func_5(x){ let y = x + 755; y += lexer_helper(11); return y; }
function parser_func_6(x){ let y = x + 636; y += lexer_helper(7); return y; }
function parser_func_7(x){ let y = x + 831; y += parser_helper(1); return y; }
function parser_func_8(x){ let y = x + 643; y += emitter_helper(19); return y; }
function parser_func_9(x){ let y = x + 762; y += lexer_helper(33); return y; }
function parser_func_10(x){ let y = x + 363; y += ast_helper(38); return y; }
function parser_func_11(x){ let y = x + 884; y += emitter_helper(8); return y; }
function parser_func_12(x){ let y = x + 263; y += emitter_helper(10); return y; }
function parser_func_13(x){ let y = x + 179; y += ast_helper(12); return y; }
function parser_func_14(x){ let y = x + 471; y += ast_helper(24); return y; }
function parser_func_15(x){ let y = x + 651; y += emitter_helper(24); return y; }
function parser_func_16(x){ let y = x + 50; y += optimizer_helper(31); return y; }
function parser_func_17(x){ let y = x + 272; y += optimizer_helper(35); return y; }
function parser_func_18(x){ let y = x + 605; y += optimizer_helper(17); return y; }
function parser_func_19(x){ let y = x + 58; y += lexer_helper(38); return y; }
function parser_func_20(x){ let y = x + 597; y += optimizer_helper(5); return y; }
function parser_func_21(x){ let y = x + 335; y += emitter_helper(6); return y; }
function parser_func_22(x){ let y = x + 824; y += optimizer_helper(29); return y; }
function parser_func_23(x){ let y = x + 824; y += lexer_helper(0); return y; }
function parser_func_24(x){ let y = x + 700; y += ast_helper(30); return y; }
function parser_func_25(x){ let y = x + 623; y += lexer_helper(46); return y; }
function parser_func_26(x){ let y = x + 782; y += ast_helper(7); return y; }
function parser_func_27(x){ let y = x + 60; y += optimizer_helper(13); return y; }
function parser_func_28(x){ let y = x + 15; y += lexer_helper(21); return y; }
function parser_func_29(x){ let y = x + 680; y += emitter_helper(10); return y; }
function parser_func_30(x){ let y = x + 327; y += optimizer_helper(10); return y; }
function parser_func_31(x){ let y = x + 738; y += optimizer_helper(30); return y; }
function parser_func_32(x){ let y = x + 131; y += lexer_helper(9); return y; }
function parser_func_33(x){ let y = x + 370; y += emitter_helper(28); return y; }
function parser_func_34(x){ let y = x + 155; y += parser_helper(13); return y; }
function parser_func_35(x){ let y = x + 521; y += ast_helper(6); return y; }
function parser_func_36(x){ let y = x + 281; y += optimizer_helper(43); return y; }
function parser_func_37(x){ let y = x + 61; y += lexer_helper(15); return y; }
function parser_func_38(x){ let y = x + 518; y += emitter_helper(15); return y; }
function parser_func_39(x){ let y = x + 972; y += ast_helper(17); return y; }
function parser_func_40(x){ let y = x + 102; y += parser_helper(39); return y; }
function parser_func_41(x){ let y = x + 815; y += lexer_helper(33); return y; }
function parser_func_42(x){ let y = x + 763; y += optimizer_helper(47); return y; }
function parser_func_43(x){ let y = x + 428; y += optimizer_helper(20); return y; }
function parser_func_44(x){ let y = x + 169; y += lexer_helper(45); return y; }
function parser_func_45(x){ let y = x + 963; y += emitter_helper(14); return y; }
function parser_func_46(x){ let y = x + 321; y += lexer_helper(13); return y; }
function parser_func_47(x){ let y = x + 638; y += ast_helper(24); return y; }
function parser_func_48(x){ let y = x + 216; y += parser_helper(3); return y; }
function parser_func_49(x){ let y = x + 596; y += emitter_helper(0); return y; }
function parser_func_50(x){ let y = x + 821; y += emitter_helper(30); return y; }
function parser_func_51(x){ let y = x + 865; y += ast_helper(21); return y; }
function parser_func_52(x){ let y = x + 64; y += optimizer_helper(0); return y; }
function parser_func_53(x){ let y = x + 858; y += emitter_helper(20); return y; }
function parser_func_54(x){ let y = x + 30; y += lexer_helper(42); return y; }
function parser_func_55(x){ let y = x + 860; y += emitter_helper(44); return y; }
function parser_func_56(x){ let y = x + 444; y += lexer_helper(47); return y; }
function parser_func_57(x){ let y = x + 171; y += optimizer_helper(0); return y; }
function parser_func_58(x){ let y = x + 131; y += ast_helper(8); return y; }
function parser_func_59(x){ let y = x + 738; y += lexer_helper(8); return y; }
function parser_func_60(x){ let y = x + 171; y += emitter_helper(18); return y; }
function parser_func_61(x){ let y = x + 910; y += ast_helper(20); return y; }
function parser_func_62(x){ let y = x + 155; y += optimizer_helper(16); return y; }
function parser_func_63(x){ let y = x + 57; y += parser_helper(4); return y; }
function parser_func_64(x){ let y = x + 174; y += emitter_helper(15); return y; }
function parser_func_65(x){ let y = x + 356; y += lexer_helper(5); return y; }
function parser_func_66(x){ let y = x + 446; y += ast_helper(38); return y; }
function parser_func_67(x){ let y = x + 677; y += emitter_helper(10); return y; }
function parser_func_68(x){ let y = x + 367; y += ast_helper(11); return y; }
function parser_func_69(x){ let y = x + 116; y += ast_helper(30); return y; }
function parser_func_70(x){ let y = x + 696; y += parser_helper(12); return y; }
function parser_func_71(x){ let y = x + 334; y += ast_helper(40); return y; }
function parser_func_72(x){ let y = x + 844; y += lexer_helper(10); return y; }
function parser_func_73(x){ let y = x + 622; y += optimizer_helper(1); return y; }
function parser_func_74(x){ let y = x + 578; y += ast_helper(9); return y; }
function parser_func_75(x){ let y = x + 785; y += ast_helper(28); return y; }
function parser_func_76(x){ let y = x + 476; y += optimizer_helper(12); return y; }
function parser_func_77(x){ let y = x + 28; y += lexer_helper(20); return y; }
function parser_func_78(x){ let y = x + 921; y += ast_helper(10); return y; }
function parser_func_79(x){ let y = x + 705; y += ast_helper(29); return y; }
function parser_func_80(x){ let y = x + 172; y += emitter_helper(34); return y; }
function parser_func_81(x){ let y = x + 421; y += emitter_helper(8); return y; }
function parser_func_82(x){ let y = x + 892; y += emitter_helper(48); return y; }
function parser_func_83(x){ let y = x + 449; y += emitter_helper(36); return y; }
function parser_func_84(x){ let y = x + 393; y += lexer_helper(4); return y; }
function parser_func_85(x){ let y = x + 326; y += ast_helper(26); return y; }
function parser_func_86(x){ let y = x + 734; y += optimizer_helper(4); return y; }
function parser_func_87(x){ let y = x + 319; y += emitter_helper(48); return y; }
function parser_func_88(x){ let y = x + 255; y += parser_helper(25); return y; }
function parser_func_89(x){ let y = x + 3; y += emitter_helper(28); return y; }
function parser_func_90(x){ let y = x + 489; y += optimizer_helper(37); return y; }
function parser_func_91(x){ let y = x + 32; y += lexer_helper(17); return y; }
function parser_func_92(x){ let y = x + 442; y += optimizer_helper(46); return y; }
function parser_func_93(x){ let y = x + 650; y += lexer_helper(44); return y; }
function parser_func_94(x){ let y = x + 352; y += lexer_helper(28); return y; }
function parser_func_95(x){ let y = x + 862; y += lexer_helper(6); return y; }
function parser_func_96(x){ let y = x + 988; y += optimizer_helper(14); return y; }
function parser_func_97(x){ let y = x + 951; y += lexer_helper(36); return y; }
function parser_func_98(x){ let y = x + 886; y += optimizer_helper(17); return y; }
function parser_func_99(x){ let y = x + 484; y += parser_helper(36); return y; }
function parser_func_100(x){ let y = x + 41; y += emitter_helper(36); return y; }
function parser_func_101(x){ let y = x + 38; y += emitter_helper(31); return y; }
function parser_func_102(x){ let y = x + 777; y += ast_helper(14); return y; }
function parser_func_103(x){ let y = x + 651; y += ast_helper(8); return y; }
function parser_func_104(x){ let y = x + 496; y += lexer_helper(47); return y; }
function parser_func_105(x){ let y = x + 76; y += ast_helper(46); return y; }
function parser_func_106(x){ let y = x + 474; y += parser_helper(38); return y; }
function parser_func_107(x){ let y = x + 218; y += lexer_helper(31); return y; }
function parser_func_108(x){ let y = x + 685; y += optimizer_helper(29); return y; }
function parser_func_109(x){ let y = x + 396; y += optimizer_helper(31); return y; }
function parser_func_110(x){ let y = x + 477; y += optimizer_helper(26); return y; }
function parser_func_111(x){ let y = x + 897; y += optimizer_helper(16); return y; }
function parser_func_112(x){ let y = x + 350; y += parser_helper(3); return y; }
function parser_func_113(x){ let y = x + 565; y += lexer_helper(49); return y; }
function parser_func_114(x){ let y = x + 755; y += parser_helper(11); return y; }
function parser_func_115(x){ let y = x + 135; y += optimizer_helper(1); return y; }
function parser_func_116(x){ let y = x + 867; y += optimizer_helper(21); return y; }
function parser_func_117(x){ let y = x + 340; y += optimizer_helper(31); return y; }
function parser_func_118(x){ let y = x + 183; y += lexer_helper(17); return y; }
function parser_func_119(x){ let y = x + 193; y += optimizer_helper(36); return y; }
function parser_func_120(x){ let y = x + 118; y += parser_helper(3); return y; }
function parser_func_121(x){ let y = x + 608; y += lexer_helper(23); return y; }
function parser_func_122(x){ let y = x + 326; y += lexer_helper(21); return y; }
function parser_func_123(x){ let y = x + 204; y += lexer_helper(48); return y; }
function parser_func_124(x){ let y = x + 166; y += lexer_helper(10); return y; }
function parser_func_125(x){ let y = x + 530; y += lexer_helper(46); return y; }
function parser_func_126(x){ let y = x + 17; y += optimizer_helper(13); return y; }
function parser_func_127(x){ let y = x + 977; y += lexer_helper(44); return y; }
function parser_func_128(x){ let y = x + 86; y += ast_helper(9); return y; }
function parser_func_129(x){ let y = x + 731; y += parser_helper(27); return y; }
function parser_func_130(x){ let y = x + 489; y += parser_helper(25); return y; }
function parser_func_131(x){ let y = x + 933; y += emitter_helper(29); return y; }
function parser_func_132(x){ let y = x + 731; y += emitter_helper(3); return y; }
function parser_func_133(x){ let y = x + 250; y += optimizer_helper(20); return y; }
function parser_func_134(x){ let y = x + 87; y += emitter_helper(13); return y; }
function parser_func_135(x){ let y = x + 289; y += optimizer_helper(14); return y; }
function parser_func_136(x){ let y = x + 835; y += emitter_helper(45); return y; }
function parser_func_137(x){ let y = x + 567; y += ast_helper(16); return y; }
function parser_func_138(x){ let y = x + 344; y += lexer_helper(5); return y; }
function parser_func_139(x){ let y = x + 220; y += parser_helper(38); return y; }
function parser_func_140(x){ let y = x + 466; y += ast_helper(8); return y; }
function parser_func_141(x){ let y = x + 422; y += optimizer_helper(30); return y; }
function parser_func_142(x){ let y = x + 732; y += parser_helper(17); return y; }
function parser_func_143(x){ let y = x + 102; y += ast_helper(34); return y; }
function parser_func_144(x){ let y = x + 300; y += ast_helper(38); return y; }
function parser_func_145(x){ let y = x + 481; y += optimizer_helper(39); return y; }
function parser_func_146(x){ let y = x + 960; y += lexer_helper(8); return y; }
function parser_func_147(x){ let y = x + 44; y += optimizer_helper(17); return y; }
function parser_func_148(x){ let y = x + 673; y += parser_helper(17); return y; }
function parser_func_149(x){ let y = x + 599; y += optimizer_helper(46); return y; }
function parser_func_150(x){ let y = x + 487; y += ast_helper(40); return y; }
function parser_func_151(x){ let y = x + 925; y += lexer_helper(7); return y; }
function parser_func_152(x){ let y = x + 353; y += emitter_helper(45); return y; }
function parser_func_153(x){ let y = x + 64; y += emitter_helper(10); return y; }
function parser_func_154(x){ let y = x + 480; y += ast_helper(25); return y; }
function parser_func_155(x){ let y = x + 402; y += ast_helper(2); return y; }
function parser_func_156(x){ let y = x + 711; y += lexer_helper(19); return y; }
function parser_func_157(x){ let y = x + 276; y += optimizer_helper(37); return y; }
function parser_func_158(x){ let y = x + 300; y += optimizer_helper(33); return y; }
function parser_func_159(x){ let y = x + 722; y += lexer_helper(40); return y; }
function parser_func_160(x){ let y = x + 51; y += optimizer_helper(20); return y; }
function parser_func_161(x){ let y = x + 244; y += emitter_helper(45); return y; }
function parser_func_162(x){ let y = x + 513; y += ast_helper(46); return y; }
function parser_func_163(x){ let y = x + 315; y += parser_helper(36); return y; }
function parser_func_164(x){ let y = x + 703; y += parser_helper(14); return y; }
function parser_func_165(x){ let y = x + 29; y += optimizer_helper(20); return y; }
function parser_func_166(x){ let y = x + 659; y += optimizer_helper(8); return y; }
function parser_func_167(x){ let y = x + 501; y += optimizer_helper(37); return y; }
function parser_func_168(x){ let y = x + 220; y += ast_helper(20); return y; }
function parser_func_169(x){ let y = x + 502; y += emitter_helper(36); return y; }
function parser_func_170(x){ let y = x + 869; y += ast_helper(25); return y; }
function parser_func_171(x){ let y = x + 850; y += optimizer_helper(22); return y; }
function parser_func_172(x){ let y = x + 554; y += optimizer_helper(41); return y; }
function parser_func_173(x){ let y = x + 609; y += lexer_helper(34); return y; }
function parser_func_174(x){ let y = x + 920; y += parser_helper(23); return y; }
function parser_func_175(x){ let y = x + 774; y += lexer_helper(42); return y; }
function parser_func_176(x){ let y = x + 478; y += ast_helper(10); return y; }
function parser_func_177(x){ let y = x + 71; y += optimizer_helper(41); return y; }
function parser_func_178(x){ let y = x + 95; y += emitter_helper(48); return y; }
function parser_func_179(x){ let y = x + 553; y += emitter_helper(29); return y; }
function parser_func_180(x){ let y = x + 270; y += ast_helper(0); return y; }
function parser_func_181(x){ let y = x + 908; y += ast_helper(11); return y; }
function parser_func_182(x){ let y = x + 690; y += parser_helper(41); return y; }
function parser_func_183(x){ let y = x + 559; y += emitter_helper(3); return y; }
function parser_func_184(x){ let y = x + 575; y += optimizer_helper(11); return y; }
function parser_func_185(x){ let y = x + 449; y += emitter_helper(22); return y; }
function parser_func_186(x){ let y = x + 142; y += parser_helper(21); return y; }
function parser_func_187(x){ let y = x + 676; y += emitter_helper(16); return y; }
function parser_func_188(x){ let y = x + 514; y += lexer_helper(24); return y; }
function parser_func_189(x){ let y = x + 306; y += ast_helper(44); return y; }
function parser_func_190(x){ let y = x + 675; y += ast_helper(32); return y; }
function parser_func_191(x){ let y = x + 432; y += lexer_helper(34); return y; }
function parser_func_192(x){ let y = x + 433; y += ast_helper(0); return y; }
function parser_func_193(x){ let y = x + 486; y += lexer_helper(7); return y; }
function parser_func_194(x){ let y = x + 174; y += emitter_helper(8); return y; }
function parser_func_195(x){ let y = x + 729; y += emitter_helper(5); return y; }
function parser_func_196(x){ let y = x + 9; y += emitter_helper(26); return y; }
function parser_func_197(x){ let y = x + 478; y += ast_helper(11); return y; }
function parser_func_198(x){ let y = x + 575; y += parser_helper(40); return y; }
function parser_func_199(x){ let y = x + 679; y += parser_helper(28); return y; }
function parser_func_200(x){ let y = x + 78; y += emitter_helper(22); return y; }
function parser_func_201(x){ let y = x + 590; y += ast_helper(40); return y; }
function parser_func_202(x){ let y = x + 175; y += optimizer_helper(42); return y; }
function parser_func_203(x){ let y = x + 437; y += parser_helper(3); return y; }
function parser_func_204(x){ let y = x + 650; y += lexer_helper(36); return y; }
function parser_func_205(x){ let y = x + 274; y += emitter_helper(17); return y; }
function parser_func_206(x){ let y = x + 644; y += ast_helper(38); return y; }
function parser_func_207(x){ let y = x + 69; y += lexer_helper(35); return y; }
function parser_func_208(x){ let y = x + 50; y += optimizer_helper(13); return y; }
function parser_func_209(x){ let y = x + 808; y += lexer_helper(1); return y; }
function parser_func_210(x){ let y = x + 459; y += parser_helper(14); return y; }
function parser_func_211(x){ let y = x + 767; y += parser_helper(15); return y; }
function parser_func_212(x){ let y = x + 73; y += lexer_helper(3); return y; }
function parser_func_213(x){ let y = x + 347; y += emitter_helper(22); return y; }
function parser_func_214(x){ let y = x + 83; y += optimizer_helper(38); return y; }
function parser_func_215(x){ let y = x + 8; y += emitter_helper(39); return y; }
function parser_func_216(x){ let y = x + 539; y += emitter_helper(28); return y; }
function parser_func_217(x){ let y = x + 781; y += ast_helper(41); return y; }
function parser_func_218(x){ let y = x + 497; y += parser_helper(0); return y; }
function parser_func_219(x){ let y = x + 964; y += parser_helper(10); return y; }
function parser_func_220(x){ let y = x + 572; y += ast_helper(15); return y; }
function parser_func_221(x){ let y = x + 35; y += optimizer_helper(31); return y; }
function parser_func_222(x){ let y = x + 53; y += emitter_helper(49); return y; }
function parser_func_223(x){ let y = x + 885; y += lexer_helper(44); return y; }
function parser_func_224(x){ let y = x + 314; y += emitter_helper(38); return y; }
function parser_func_225(x){ let y = x + 601; y += ast_helper(15); return y; }
function parser_func_226(x){ let y = x + 300; y += lexer_helper(27); return y; }
function parser_func_227(x){ let y = x + 640; y += lexer_helper(12); return y; }
function parser_func_228(x){ let y = x + 179; y += lexer_helper(19); return y; }
function parser_func_229(x){ let y = x + 20; y += optimizer_helper(30); return y; }
function parser_func_230(x){ let y = x + 361; y += ast_helper(11); return y; }
function parser_func_231(x){ let y = x + 301; y += ast_helper(39); return y; }
function parser_func_232(x){ let y = x + 342; y += parser_helper(34); return y; }
function parser_func_233(x){ let y = x + 456; y += emitter_helper(40); return y; }
function parser_func_234(x){ let y = x + 247; y += emitter_helper(5); return y; }
function parser_func_235(x){ let y = x + 988; y += optimizer_helper(26); return y; }
function parser_func_236(x){ let y = x + 306; y += lexer_helper(32); return y; }
function parser_func_237(x){ let y = x + 224; y += emitter_helper(9); return y; }
function parser_func_238(x){ let y = x + 49; y += ast_helper(16); return y; }
function parser_func_239(x){ let y = x + 84; y += parser_helper(40); return y; }
function parser_func_240(x){ let y = x + 515; y += emitter_helper(46); return y; }
function parser_func_241(x){ let y = x + 150; y += lexer_helper(29); return y; }
function parser_func_242(x){ let y = x + 23; y += ast_helper(6); return y; }
function parser_func_243(x){ let y = x + 499; y += ast_helper(39); return y; }
function parser_func_244(x){ let y = x + 812; y += parser_helper(23); return y; }
function parser_func_245(x){ let y = x + 780; y += lexer_helper(27); return y; }
function parser_func_246(x){ let y = x + 984; y += lexer_helper(26); return y; }
function parser_func_247(x){ let y = x + 430; y += lexer_helper(23); return y; }
function parser_func_248(x){ let y = x + 523; y += emitter_helper(5); return y; }
function parser_func_249(x){ let y = x + 387; y += parser_helper(23); return y; }
function parser_func_250(x){ let y = x + 406; y += ast_helper(38); return y; }
function parser_func_251(x){ let y = x + 46; y += lexer_helper(33); return y; }
function parser_func_252(x){ let y = x + 38; y += parser_helper(11); return y; }
function parser_func_253(x){ let y = x + 424; y += ast_helper(36); return y; }
function parser_func_254(x){ let y = x + 448; y += ast_helper(29); return y; }
function parser_func_255(x){ let y = x + 324; y += ast_helper(25); return y; }
function parser_func_256(x){ let y = x + 347; y += ast_helper(46); return y; }
function parser_func_257(x){ let y = x + 588; y += parser_helper(12); return y; }
function parser_func_258(x){ let y = x + 827; y += emitter_helper(10); return y; }
function parser_func_259(x){ let y = x + 706; y += optimizer_helper(0); return y; }
function parser_func_260(x){ let y = x + 55; y += parser_helper(45); return y; }
function parser_func_261(x){ let y = x + 133; y += optimizer_helper(22); return y; }
function parser_func_262(x){ let y = x + 370; y += parser_helper(4); return y; }
function parser_func_263(x){ let y = x + 949; y += parser_helper(21); return y; }
function parser_func_264(x){ let y = x + 942; y += parser_helper(17); return y; }
function parser_func_265(x){ let y = x + 818; y += optimizer_helper(25); return y; }
function parser_func_266(x){ let y = x + 928; y += parser_helper(6); return y; }
function parser_func_267(x){ let y = x + 426; y += optimizer_helper(6); return y; }
function parser_func_268(x){ let y = x + 208; y += emitter_helper(38); return y; }
function parser_func_269(x){ let y = x + 545; y += lexer_helper(0); return y; }
function parser_func_270(x){ let y = x + 915; y += emitter_helper(24); return y; }
function parser_func_271(x){ let y = x + 938; y += emitter_helper(28); return y; }
function parser_func_272(x){ let y = x + 712; y += emitter_helper(36); return y; }
function parser_func_273(x){ let y = x + 913; y += emitter_helper(38); return y; }
function parser_func_274(x){ let y = x + 723; y += ast_helper(24); return y; }
function parser_func_275(x){ let y = x + 360; y += optimizer_helper(31); return y; }
function parser_func_276(x){ let y = x + 926; y += emitter_helper(19); return y; }
function parser_func_277(x){ let y = x + 133; y += ast_helper(11); return y; }
function parser_func_278(x){ let y = x + 738; y += lexer_helper(8); return y; }
function parser_func_279(x){ let y = x + 877; y += emitter_helper(27); return y; }
function parser_func_280(x){ let y = x + 364; y += optimizer_helper(32); return y; }
function parser_func_281(x){ let y = x + 709; y += optimizer_helper(43); return y; }
function parser_func_282(x){ let y = x + 878; y += optimizer_helper(3); return y; }
function parser_func_283(x){ let y = x + 725; y += parser_helper(1); return y; }
function parser_func_284(x){ let y = x + 410; y += parser_helper(0); return y; }
function parser_func_285(x){ let y = x + 417; y += parser_helper(14); return y; }
function parser_func_286(x){ let y = x + 426; y += emitter_helper(36); return y; }
function parser_func_287(x){ let y = x + 885; y += emitter_helper(30); return y; }
function parser_func_288(x){ let y = x + 876; y += emitter_helper(6); return y; }
function parser_func_289(x){ let y = x + 521; y += ast_helper(13); return y; }
function parser_func_290(x){ let y = x + 225; y += emitter_helper(37); return y; }
function parser_func_291(x){ let y = x + 116; y += ast_helper(40); return y; }
function parser_func_292(x){ let y = x + 450; y += ast_helper(27); return y; }
function parser_func_293(x){ let y = x + 275; y += lexer_helper(47); return y; }
function parser_func_294(x){ let y = x + 773; y += optimizer_helper(18); return y; }
function parser_func_295(x){ let y = x + 392; y += ast_helper(10); return y; }
function parser_func_296(x){ let y = x + 343; y += parser_helper(28); return y; }
function parser_func_297(x){ let y = x + 620; y += optimizer_helper(41); return y; }
function parser_func_298(x){ let y = x + 248; y += emitter_helper(46); return y; }
function parser_func_299(x){ let y = x + 387; y += optimizer_helper(3); return y; }
function parser_func_300(x){ let y = x + 335; y += parser_helper(35); return y; }
function parser_func_301(x){ let y = x + 5; y += parser_helper(17); return y; }
function parser_func_302(x){ let y = x + 245; y += parser_helper(21); return y; }
function parser_func_303(x){ let y = x + 123; y += emitter_helper(48); return y; }
function parser_func_304(x){ let y = x + 536; y += lexer_helper(34); return y; }
function parser_func_305(x){ let y = x + 895; y += lexer_helper(14); return y; }
function parser_func_306(x){ let y = x + 364; y += parser_helper(13); return y; }
function parser_func_307(x){ let y = x + 810; y += ast_helper(23); return y; }
function parser_func_308(x){ let y = x + 325; y += ast_helper(35); return y; }
function parser_func_309(x){ let y = x + 52; y += ast_helper(3); return y; }
function parser_func_310(x){ let y = x + 780; y += parser_helper(45); return y; }
function parser_func_311(x){ let y = x + 508; y += parser_helper(19); return y; }
function parser_func_312(x){ let y = x + 913; y += parser_helper(5); return y; }
function parser_func_313(x){ let y = x + 893; y += lexer_helper(3); return y; }
function parser_func_314(x){ let y = x + 920; y += lexer_helper(45); return y; }
function parser_func_315(x){ let y = x + 945; y += lexer_helper(21); return y; }
function parser_func_316(x){ let y = x + 578; y += lexer_helper(45); return y; }
function parser_func_317(x){ let y = x + 676; y += lexer_helper(29); return y; }
function parser_func_318(x){ let y = x + 511; y += parser_helper(18); return y; }
function parser_func_319(x){ let y = x + 990; y += emitter_helper(49); return y; }
function parser_func_320(x){ let y = x + 823; y += optimizer_helper(33); return y; }
function parser_func_321(x){ let y = x + 69; y += emitter_helper(43); return y; }
function parser_func_322(x){ let y = x + 421; y += lexer_helper(6); return y; }
function parser_func_323(x){ let y = x + 234; y += optimizer_helper(27); return y; }
function parser_func_324(x){ let y = x + 62; y += lexer_helper(7); return y; }
function parser_func_325(x){ let y = x + 441; y += emitter_helper(6); return y; }
function parser_func_326(x){ let y = x + 701; y += ast_helper(37); return y; }
function parser_func_327(x){ let y = x + 496; y += emitter_helper(34); return y; }
function parser_func_328(x){ let y = x + 371; y += optimizer_helper(11); return y; }
function parser_func_329(x){ let y = x + 925; y += emitter_helper(41); return y; }
function parser_func_330(x){ let y = x + 393; y += lexer_helper(42); return y; }
function parser_func_331(x){ let y = x + 459; y += lexer_helper(14); return y; }
function parser_func_332(x){ let y = x + 978; y += parser_helper(23); return y; }
function parser_func_333(x){ let y = x + 962; y += ast_helper(36); return y; }
function parser_func_334(x){ let y = x + 215; y += lexer_helper(26); return y; }
function parser_func_335(x){ let y = x + 180; y += ast_helper(31); return y; }
function parser_func_336(x){ let y = x + 654; y += ast_helper(30); return y; }
function parser_func_337(x){ let y = x + 179; y += lexer_helper(12); return y; }
function parser_func_338(x){ let y = x + 237; y += emitter_helper(8); return y; }
function parser_func_339(x){ let y = x + 691; y += ast_helper(33); return y; }
function parser_func_340(x){ let y = x + 31; y += emitter_helper(15); return y; }
function parser_func_341(x){ let y = x + 520; y += parser_helper(43); return y; }
function parser_func_342(x){ let y = x + 173; y += parser_helper(18); return y; }
function parser_func_343(x){ let y = x + 61; y += optimizer_helper(21); return y; }
function parser_func_344(x){ let y = x + 526; y += ast_helper(48); return y; }
function parser_func_345(x){ let y = x + 686; y += parser_helper(30); return y; }
function parser_func_346(x){ let y = x + 540; y += parser_helper(7); return y; }
function parser_func_347(x){ let y = x + 685; y += ast_helper(49); return y; }
function parser_func_348(x){ let y = x + 214; y += parser_helper(46); return y; }
function parser_func_349(x){ let y = x + 91; y += optimizer_helper(8); return y; }
function parser_func_350(x){ let y = x + 852; y += parser_helper(33); return y; }
function parser_func_351(x){ let y = x + 60; y += optimizer_helper(34); return y; }
function parser_func_352(x){ let y = x + 989; y += emitter_helper(17); return y; }
function parser_func_353(x){ let y = x + 369; y += emitter_helper(5); return y; }
function parser_func_354(x){ let y = x + 26; y += ast_helper(9); return y; }
function parser_func_355(x){ let y = x + 240; y += optimizer_helper(27); return y; }
function parser_func_356(x){ let y = x + 218; y += optimizer_helper(12); return y; }
function parser_func_357(x){ let y = x + 693; y += ast_helper(26); return y; }
function parser_func_358(x){ let y = x + 358; y += parser_helper(36); return y; }
function parser_func_359(x){ let y = x + 791; y += ast_helper(5); return y; }
function parser_func_360(x){ let y = x + 281; y += lexer_helper(49); return y; }
function parser_func_361(x){ let y = x + 444; y += ast_helper(40); return y; }
function parser_func_362(x){ let y = x + 602; y += ast_helper(32); return y; }
function parser_func_363(x){ let y = x + 940; y += optimizer_helper(9); return y; }
function parser_func_364(x){ let y = x + 309; y += lexer_helper(39); return y; }
function parser_func_365(x){ let y = x + 62; y += optimizer_helper(8); return y; }
function parser_func_366(x){ let y = x + 808; y += emitter_helper(46); return y; }
function parser_func_367(x){ let y = x + 508; y += optimizer_helper(9); return y; }
function parser_func_368(x){ let y = x + 646; y += lexer_helper(17); return y; }
function parser_func_369(x){ let y = x + 205; y += lexer_helper(36); return y; }
function parser_func_370(x){ let y = x + 414; y += ast_helper(13); return y; }
function parser_func_371(x){ let y = x + 499; y += emitter_helper(47); return y; }
function parser_func_372(x){ let y = x + 149; y += emitter_helper(6); return y; }
function parser_func_373(x){ let y = x + 897; y += optimizer_helper(0); return y; }
function parser_func_374(x){ let y = x + 466; y += ast_helper(40); return y; }
function parser_func_375(x){ let y = x + 407; y += ast_helper(14); return y; }
function parser_func_376(x){ let y = x + 585; y += ast_helper(35); return y; }
function parser_func_377(x){ let y = x + 592; y += parser_helper(15); return y; }
function parser_func_378(x){ let y = x + 276; y += optimizer_helper(7); return y; }
function parser_func_379(x){ let y = x + 450; y += emitter_helper(31); return y; }
function parser_func_380(x){ let y = x + 837; y += emitter_helper(7); return y; }
function parser_func_381(x){ let y = x + 433; y += optimizer_helper(21); return y; }
function parser_func_382(x){ let y = x + 225; y += emitter_helper(40); return y; }
function parser_func_383(x){ let y = x + 660; y += parser_helper(14); return y; }
function parser_func_384(x){ let y = x + 600; y += emitter_helper(8); return y; }
function parser_func_385(x){ let y = x + 878; y += ast_helper(42); return y; }
function parser_func_386(x){ let y = x + 169; y += parser_helper(38); return y; }
function parser_func_387(x){ let y = x + 209; y += parser_helper(26); return y; }
function parser_func_388(x){ let y = x + 891; y += emitter_helper(28); return y; }
function parser_func_389(x){ let y = x + 950; y += lexer_helper(36); return y; }
function parser_func_390(x){ let y = x + 165; y += lexer_helper(10); return y; }
function parser_func_391(x){ let y = x + 689; y += lexer_helper(42); return y; }
function parser_func_392(x){ let y = x + 443; y += optimizer_helper(31); return y; }
function parser_func_393(x){ let y = x + 760; y += ast_helper(28); return y; }
function parser_func_394(x){ let y = x + 876; y += parser_helper(25); return y; }
function parser_func_395(x){ let y = x + 351; y += parser_helper(3); return y; }
function parser_func_396(x){ let y = x + 461; y += lexer_helper(37); return y; }
function parser_func_397(x){ let y = x + 113; y += ast_helper(35); return y; }
function parser_func_398(x){ let y = x + 416; y += emitter_helper(4); return y; }
function parser_func_399(x){ let y = x + 316; y += lexer_helper(9); return y; }
function parser_func_400(x){ let y = x + 509; y += lexer_helper(8); return y; }
function parser_func_401(x){ let y = x + 206; y += optimizer_helper(20); return y; }
function parser_func_402(x){ let y = x + 46; y += parser_helper(4); return y; }
function parser_func_403(x){ let y = x + 678; y += ast_helper(40); return y; }
function parser_func_404(x){ let y = x + 386; y += lexer_helper(35); return y; }
function parser_func_405(x){ let y = x + 433; y += parser_helper(28); return y; }
function parser_func_406(x){ let y = x + 682; y += parser_helper(32); return y; }
function parser_func_407(x){ let y = x + 556; y += optimizer_helper(13); return y; }
function parser_func_408(x){ let y = x + 412; y += emitter_helper(24); return y; }
function parser_func_409(x){ let y = x + 58; y += emitter_helper(1); return y; }
function parser_func_410(x){ let y = x + 899; y += ast_helper(25); return y; }
function parser_func_411(x){ let y = x + 617; y += ast_helper(47); return y; }
function parser_func_412(x){ let y = x + 103; y += ast_helper(31); return y; }
function parser_func_413(x){ let y = x + 621; y += parser_helper(13); return y; }
function parser_func_414(x){ let y = x + 536; y += parser_helper(8); return y; }
function parser_func_415(x){ let y = x + 382; y += optimizer_helper(25); return y; }
function parser_func_416(x){ let y = x + 187; y += ast_helper(15); return y; }
function parser_func_417(x){ let y = x + 434; y += parser_helper(5); return y; }
function parser_func_418(x){ let y = x + 332; y += optimizer_helper(28); return y; }
function parser_func_419(x){ let y = x + 78; y += optimizer_helper(7); return y; }
function parser_func_420(x){ let y = x + 12; y += emitter_helper(40); return y; }
function parser_func_421(x){ let y = x + 265; y += parser_helper(30); return y; }
function parser_func_422(x){ let y = x + 338; y += emitter_helper(5); return y; }
function parser_func_423(x){ let y = x + 160; y += parser_helper(2); return y; }
function parser_func_424(x){ let y = x + 436; y += parser_helper(25); return y; }
function parser_func_425(x){ let y = x + 635; y += ast_helper(42); return y; }
function parser_func_426(x){ let y = x + 975; y += ast_helper(37); return y; }
function parser_func_427(x){ let y = x + 192; y += emitter_helper(42); return y; }
function parser_func_428(x){ let y = x + 834; y += lexer_helper(47); return y; }
function parser_func_429(x){ let y = x + 603; y += lexer_helper(9); return y; }
function parser_func_430(x){ let y = x + 954; y += parser_helper(8); return y; }
function parser_func_431(x){ let y = x + 890; y += emitter_helper(13); return y; }
function parser_func_432(x){ let y = x + 370; y += ast_helper(30); return y; }
function parser_func_433(x){ let y = x + 400; y += optimizer_helper(32); return y; }
function parser_func_434(x){ let y = x + 147; y += parser_helper(41); return y; }
function parser_func_435(x){ let y = x + 860; y += optimizer_helper(32); return y; }
function parser_func_436(x){ let y = x + 290; y += lexer_helper(24); return y; }
function parser_func_437(x){ let y = x + 549; y += lexer_helper(7); return y; }
function parser_func_438(x){ let y = x + 426; y += optimizer_helper(38); return y; }
function parser_func_439(x){ let y = x + 913; y += ast_helper(41); return y; }
function parser_func_440(x){ let y = x + 770; y += lexer_helper(21); return y; }
function parser_func_441(x){ let y = x + 987; y += ast_helper(31); return y; }
function parser_func_442(x){ let y = x + 841; y += lexer_helper(27); return y; }
function parser_func_443(x){ let y = x + 571; y += emitter_helper(2); return y; }
function parser_func_444(x){ let y = x + 115; y += optimizer_helper(42); return y; }
function parser_func_445(x){ let y = x + 921; y += ast_helper(41); return y; }
function parser_func_446(x){ let y = x + 296; y += lexer_helper(6); return y; }
function parser_func_447(x){ let y = x + 237; y += lexer_helper(28); return y; }
function parser_func_448(x){ let y = x + 839; y += ast_helper(46); return y; }
function parser_func_449(x){ let y = x + 946; y += ast_helper(15); return y; }
function parser_func_450(x){ let y = x + 882; y += ast_helper(34); return y; }
function parser_func_451(x){ let y = x + 606; y += parser_helper(35); return y; }
function parser_func_452(x){ let y = x + 356; y += emitter_helper(15); return y; }
function parser_func_453(x){ let y = x + 547; y += ast_helper(38); return y; }
function parser_func_454(x){ let y = x + 510; y += optimizer_helper(11); return y; }
function parser_func_455(x){ let y = x + 628; y += emitter_helper(33); return y; }
function parser_func_456(x){ let y = x + 828; y += lexer_helper(37); return y; }
function parser_func_457(x){ let y = x + 495; y += ast_helper(11); return y; }
function parser_func_458(x){ let y = x + 796; y += optimizer_helper(49); return y; }
function parser_func_459(x){ let y = x + 723; y += optimizer_helper(41); return y; }
function parser_func_460(x){ let y = x + 286; y += parser_helper(22); return y; }
function parser_func_461(x){ let y = x + 966; y += lexer_helper(1); return y; }
function parser_func_462(x){ let y = x + 165; y += optimizer_helper(35); return y; }
function parser_func_463(x){ let y = x + 82; y += optimizer_helper(25); return y; }
function parser_func_464(x){ let y = x + 474; y += ast_helper(3); return y; }
function parser_func_465(x){ let y = x + 86; y += optimizer_helper(22); return y; }
function parser_func_466(x){ let y = x + 667; y += optimizer_helper(16); return y; }
function parser_func_467(x){ let y = x + 789; y += lexer_helper(37); return y; }
function parser_func_468(x){ let y = x + 108; y += lexer_helper(24); return y; }
function parser_func_469(x){ let y = x + 908; y += lexer_helper(7); return y; }
function parser_func_470(x){ let y = x + 827; y += optimizer_helper(15); return y; }
function parser_func_471(x){ let y = x + 855; y += emitter_helper(16); return y; }
function parser_func_472(x){ let y = x + 991; y += optimizer_helper(43); return y; }
function parser_func_473(x){ let y = x + 8; y += ast_helper(25); return y; }
function parser_func_474(x){ let y = x + 407; y += parser_helper(36); return y; }
function parser_func_475(x){ let y = x + 40; y += emitter_helper(11); return y; }
function parser_func_476(x){ let y = x + 475; y += lexer_helper(2); return y; }
function parser_func_477(x){ let y = x + 107; y += parser_helper(26); return y; }
function parser_func_478(x){ let y = x + 11; y += emitter_helper(12); return y; }
function parser_func_479(x){ let y = x + 59; y += optimizer_helper(39); return y; }
function parser_func_480(x){ let y = x + 335; y += ast_helper(38); return y; }
function parser_func_481(x){ let y = x + 425; y += emitter_helper(34); return y; }
function parser_func_482(x){ let y = x + 773; y += parser_helper(26); return y; }
function parser_func_483(x){ let y = x + 469; y += lexer_helper(5); return y; }
function parser_func_484(x){ let y = x + 82; y += emitter_helper(38); return y; }
function parser_func_485(x){ let y = x + 779; y += optimizer_helper(14); return y; }
function parser_func_486(x){ let y = x + 946; y += lexer_helper(21); return y; }
function parser_func_487(x){ let y = x + 539; y += parser_helper(25); return y; }
function parser_func_488(x){ let y = x + 688; y += parser_helper(15); return y; }
function parser_func_489(x){ let y = x + 106; y += lexer_helper(36); return y; }
function parser_func_490(x){ let y = x + 572; y += ast_helper(5); return y; }
function parser_func_491(x){ let y = x + 184; y += optimizer_helper(34); return y; }
function parser_func_492(x){ let y = x + 192; y += emitter_helper(21); return y; }
function parser_func_493(x){ let y = x + 771; y += parser_helper(6); return y; }
function parser_func_494(x){ let y = x + 554; y += emitter_helper(11); return y; }
function parser_func_495(x){ let y = x + 73; y += emitter_helper(28); return y; }
function parser_func_496(x){ let y = x + 255; y += ast_helper(11); return y; }
function parser_func_497(x){ let y = x + 515; y += ast_helper(37); return y; }
function parser_func_498(x){ let y = x + 372; y += ast_helper(8); return y; }
function parser_func_499(x){ let y = x + 38; y += parser_helper(6); return y; }
function lexer_helper(x){ return x*13; }
function parser_helper(x){ return x*17; }
function ast_helper(x){ return x*6; }
function optimizer_helper(x){ return x*14; }
function emitter_helper(x){ return x*20; }
module.exports = { lexer_init, parser_init, ast_init, optimizer_init, emitter_init };
